// Generated by scripts/generate-article-manifest.mjs. Do not edit.
import type { ComponentType } from "react";
import CommunicationIsGameplayStateArticle from "./communication-is-gameplay-state.mdx";
import CreationJudgmentRecoverableSystemsArticle from "./creation-judgment-recoverable-systems.mdx";
import FromTokensToWorkArticle from "./from-tokens-to-work.mdx";
import OneAuthorityThirteenTablesArticle from "./one-authority-thirteen-tables.mdx";
import ReplayWithoutSecondTruthStoreArticle from "./replay-without-second-truth-store.mdx";
import SmallerCoreStrongBaselinesArticle from "./smaller-core-strong-baselines.mdx";
import StationZeroAlpha1Article from "./station-zero-alpha-1.mdx";
import ThinHostWithoutHiddenPlannerArticle from "./thin-host-without-hidden-planner.mdx";
import TranscriptNotTaskDatabaseArticle from "./transcript-not-task-database.mdx";
import UnknownIsOperationalStateArticle from "./unknown-is-operational-state.mdx";
import WhatH1H5ProvedArticle from "./what-h1-h5-proved.mdx";
import WhyOrdivonNeedsAHarnessArticle from "./why-ordivon-needs-a-harness.mdx";
import WinningMoveLosesContestArticle from "./winning-move-loses-contest.mdx";
import TheFutureWillNotWaitArticle from "./the-future-will-not-wait.mdx";
import HostTaskContinuityArticle from "./host-task-continuity.mdx";
import LinkEdgeBoundaryArticle from "./link-edge-boundary.mdx";
import RuntimeAfterCoreArticle from "./runtime-after-core.mdx";
import OrdivonRuntimeReleaseArticle from "./ordivon-runtime-release.mdx";
import WhyOrdivonArticle from "./why-ordivon.mdx";
import { articleMetadata, type ArticleSlug } from "./generated-metadata";

const articleComponents: Record<ArticleSlug, ComponentType> = {
  "communication-is-gameplay-state": CommunicationIsGameplayStateArticle,
  "creation-judgment-recoverable-systems": CreationJudgmentRecoverableSystemsArticle,
  "from-tokens-to-work": FromTokensToWorkArticle,
  "one-authority-thirteen-tables": OneAuthorityThirteenTablesArticle,
  "replay-without-second-truth-store": ReplayWithoutSecondTruthStoreArticle,
  "smaller-core-strong-baselines": SmallerCoreStrongBaselinesArticle,
  "station-zero-alpha-1": StationZeroAlpha1Article,
  "thin-host-without-hidden-planner": ThinHostWithoutHiddenPlannerArticle,
  "transcript-not-task-database": TranscriptNotTaskDatabaseArticle,
  "unknown-is-operational-state": UnknownIsOperationalStateArticle,
  "what-h1-h5-proved": WhatH1H5ProvedArticle,
  "why-ordivon-needs-a-harness": WhyOrdivonNeedsAHarnessArticle,
  "winning-move-loses-contest": WinningMoveLosesContestArticle,
  "the-future-will-not-wait": TheFutureWillNotWaitArticle,
  "host-task-continuity": HostTaskContinuityArticle,
  "link-edge-boundary": LinkEdgeBoundaryArticle,
  "runtime-after-core": RuntimeAfterCoreArticle,
  "ordivon-runtime-release": OrdivonRuntimeReleaseArticle,
  "why-ordivon": WhyOrdivonArticle,
};

export const articleManifest = articleMetadata.map((metadata) => ({ ...metadata, Content: articleComponents[metadata.slug] }));
