import type { BoundaryDefinition, ProjectDefinition, QuestionDefinition, ResearchPlaneDefinition } from "@/lib/model/types";
import { harnessBoundary, harnessProject } from "./projects/generated-harness.ts";
import { securityProject } from "./projects/generated-security.ts";
import { gameProject } from "./projects/generated-game.ts";

export const siteUpdatedAt = "2026-08-12";
const portfolioUpdatedAt = "2026-08-12";

export const researchPlanes: ResearchPlaneDefinition[] = [
  {
    id: "system:computing", kind: "research-plane", slug: "computing", index: "R", title: "Computing", status: "active",
    summary: "The research, specification, and conformance root that tests which shared contracts deserve to survive.",
    thesis: "Keep only responsibilities that remain unowned after comparison with mature systems and materially different workloads.",
    question: "Which facts and contracts must remain stable when models, Hosts, Harnesses, tools, and execution backends change?",
    owns: ["Shared theory", "Research portfolio", "Promoted protocol", "Conformance evidence"],
    boundary: ["No production Tasks", "No physical Jobs", "No product maturity claims"],
    href: "/projects/computing", updatedAt: portfolioUpdatedAt,
  },
];

export const boundaries: BoundaryDefinition[] = [
  {
    id: "system:host", kind: "boundary", slug: "host", index: "01", title: "Host", maturity: "tested",
    summary: "The durable coordination boundary that preserves Task meaning, commitments, verification, and outcomes above replaceable Runs and processes.",
    thesis: "Replace the intelligence or process without replacing the Task.",
    question: "Which commitments and evidence must remain durable across cognition and execution replacement?",
    owns: ["Task continuity", "Journal and CAS", "Commitment admission", "Verification and outcomes"],
    boundary: ["No model–Tool loop", "No process ownership", "No domain-world truth"],
    href: "/projects/host", updatedAt: portfolioUpdatedAt,
  },
  harnessBoundary,
  {
    id: "system:runtime", kind: "boundary", slug: "runtime", index: "03", title: "Runtime", maturity: "tested",
    summary: "The physical execution boundary that owns durable local operation identity, process state, retained evidence, cancellation, and reconciliation.",
    thesis: "Commit one admitted operation to local reality without losing what happened.",
    question: "Which physical execution facts cannot safely be reconstructed after interruption?",
    owns: ["Workspaces", "Jobs and Runtime Attempts", "Process trees", "Artifacts and physical recovery"],
    boundary: ["No Task semantics", "No Provider policy", "No semantic completion"],
    href: "/projects/runtime", updatedAt: portfolioUpdatedAt,
  },
];

export const architectureRoles = [...researchPlanes, ...boundaries];

export const projects: ProjectDefinition[] = [
  {
    id: "project:host", kind: "project", slug: "host", title: "Ordivon Host", lifecycle: "active", group: "Core work system",
    label: "Durable Task continuity", category: "core-system", availability: "prototype", architectureRoleId: "system:host", publicPage: true,
    problem: "A model Run can end while the user's larger Task, accepted commitments, unresolved effects, and completion evidence still need to continue.",
    capability: "Persists generic Tasks, Journal/CAS state, commitment admission, verification records, and Task outcomes above replaceable Harness Runs and Runtime processes.",
    maturity: "Implemented engineering prototype", audience: "Builders of long-running Agent systems that need durable work state without a workflow platform or model monopoly.",
    latestProof: "The schema-v3 Host exposes operational inspection and conservative reconciliation, with 167 deterministic tests and extracted Harness ownership.", flagshipSlug: "host-task-continuity",
    summary: "The persistent coordination and commitment plane for Ordivon. Host keeps durable work legible while cognition and physical execution remain replaceable dependencies.",
    state: "Implemented and independently versioned. It is an engineering prototype, not a general workflow engine, policy platform, or multi-Agent scheduler.",
    evidence: [{ value: "167", label: "deterministic tests" }, { value: "v3", label: "operational state schema" }, { value: "0", label: "Harness tables owned" }],
    repository: "https://github.com/zycxfyh/ordivon-host", href: "/projects/host", updatedAt: portfolioUpdatedAt,
  },
  harnessProject,
  {
    id: "project:runtime", kind: "project", slug: "runtime", title: "Ordivon Runtime", lifecycle: "active", group: "Core work system",
    label: "Exact physical execution and recovery", category: "core-system", availability: "operational", architectureRoleId: "system:runtime", publicPage: true,
    problem: "A command can be admitted, partially execute, lose its response, time out, restart, or cross execution targets while a later Agent still needs exact physical evidence about what happened.",
    capability: "Owns exact Workspaces, durable Jobs and Attempts, immutable-input execution, provider commitments, Windows-native execution, cancellation, restart recovery, bounded Artifacts, exact replay, and reconciliation of uncertain local commits.",
    maturity: "Operational owner-trusted infrastructure under active high-pressure validation", audience: "Builders who need Agent actions to remain physically identifiable and recoverable after interruption without turning the executor into the Task or domain authority.",
    latestProof: "The P0–P5 foundation and HP0 compositional pressure survived capacity, cancellation, restart, provider identity, immutable-input, Windows-native, and uncertain-commit attacks; current production exposes a bounded Runtime MCP surface.",
    summary: "The physical authority for admitted local execution. Runtime proves what the machine executed and retained; it does not decide what that execution means for the Task or external world.",
    state: "Operational in the owner-trusted local environment. Exact execution and recovery are current capabilities; hostile-root isolation, arbitrary external-effect truth, and semantic Task completion remain outside Runtime.",
    evidence: [{ value: "36 / 36", label: "transactional real-system acceptance" }, { value: "80 / 80", label: "cancel-swarm trials" }, { value: "30 / 30", label: "restart-swarm trials" }],
    repository: "https://github.com/zycxfyh/ordivon-runtime", href: "/projects/runtime", updatedAt: portfolioUpdatedAt,
  },
  gameProject,
  {
    id: "project:world", kind: "project", slug: "world", title: "Ordivon World", lifecycle: "active", group: "Applications and capability",
    label: "Cross-owner relationships to external reality", category: "application", availability: "operational", publicPage: true, index: "05",
    thesis: "Keep native truth with native owners; retain only the cross-owner relationship whose loss makes external observation, transfer, or consequence unsafe to reconstruct.",
    question: "Which facts about an Agent's relationship to external reality cannot be owned cleanly by the Provider, Host, Runtime, Workstation, or domain on either side?",
    owns: ["Typed cross-owner resource and message relations", "Provider/consequence binding", "UNKNOWN external-consequence reconciliation", "Narrow observation-availability provenance"],
    boundary: ["No global external-truth database", "No universal provider router", "No duplicated Runtime or network ownership"],
    problem: "An Agent can interact with several external owners while responses are delayed, capabilities expire, execution targets change, or consequences become uncertain; neither endpoint alone always preserves the relationship needed for safe continuation.",
    capability: "Preserves the narrow cross-owner identities, availability facts, and reconciliation boundaries that survived high-pressure deletion while provider, Runtime, Host, Workstation, and domain truth remain owner-native.",
    maturity: "Operational minimal boundary after HP0–HP8 survival audit", audience: "Builders and researchers working on external Agent observation, transfer, and consequence where one side's native truth is not enough to reconstruct the relationship after interruption.",
    latestProof: "HP6–HP8 archived stale active-history material, deleted research-only ForeignEgress and EffectPath machinery, improved current retrieval from 7/9 to 9/9, and replayed the same 96 mixed-failure invocations with zero failures after contraction.", flagshipSlug: "world-got-smaller-and-got-clearer",
    summary: "The narrow relationship layer between independently authoritative systems. World does not own external reality; it preserves the cross-owner facts needed to reconnect to it safely.",
    state: "Minimal World is current. Historical research remains retrievable but no longer competes with present authority; deleted capabilities reopen only after a named current workload reproduces an unowned failure.",
    evidence: [{ value: "96 / 96", label: "post-contraction mixed-failure replay" }, { value: "7 → 9 / 9", label: "current retrieval accuracy" }, { value: "−779", label: "production Python LOC in HP8" }],
    repository: "https://github.com/zycxfyh/ordivon-world", href: "/projects/world", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "project:finance", kind: "project", slug: "finance", title: "Ordivon Finance", lifecycle: "active", group: "Applications and capability",
    label: "Agent-first capital research and financial effects", category: "application", availability: "prototype", publicPage: true, index: "06",
    thesis: "Let the Agent own capital judgment while deterministic machinery owns effect identity, admission, one-shot dispatch, evidence, and reconciliation.",
    question: "Can an Agent research and act on real capital without confusing a statistical winner, a permitted action, and a committed financial consequence?",
    owns: ["Finance-domain proposals and decisions", "Quantitative research evidence", "Financial effect admission", "Venue-effect reconciliation"],
    boundary: ["No universal quant DSL", "No live authorization from a model conclusion", "No hostile-root isolation claim for the same-machine profile"],
    problem: "Backtests, model judgments, API permissions, signer authority, order dispatch, and final venue consequences are different facts; collapsing them can turn research confidence into an unintended financial effect.",
    capability: "Combines an Agent-first quantitative research laboratory with a bounded C2/v3 financial-effect path whose current local profile preserves effect correctness while live submission remains disabled pending separate preparation and authorization.",
    maturity: "Implemented finance research/effect prototype; live submission disabled", audience: "Researchers and builders exploring Agent capital systems that need explicit separation between statistical evidence, semantic judgment, execution authority, and venue consequence.",
    latestProof: "QB3c froze the unchanged constitution-only treatment on a second sealed carrier and reversed the earlier favorable sign; QB6 then let one Agent request read-only execution evidence and update from more_research to no_op when the minimum QQQ contract required 32.9% of owner equity against a frozen 10% intent bound.",
    summary: "A domain laboratory for capital judgment, quantitative falsification, owner-conditioned research, and exact financial-effect boundaries. Finance does not turn a backtest or model preference into authority to move money.",
    state: "Research and local effect machinery are implemented. Current owner-conditioned judgment can terminate at no-op before simulation or effect machinery; the local C2/v3 submission surface remains disabled and real-venue submission is not publicly claimed as active capability.",
    evidence: [{ value: "36 / 36", label: "QB3c formal semantic trials" }, { value: "more research → no-op", label: "QB6 evidence-conditioned Agent sequence" }, { value: "0", label: "QB6 external financial writes" }],
    repository: "https://github.com/zycxfyh/ordivon-finance", href: "/projects/finance", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "project:computing", kind: "project", slug: "computing", title: "Ordivon Computing", lifecycle: "active", group: "Research and specification",
    label: "Cross-project science and world-model synthesis", category: "research", availability: "research", architectureRoleId: "system:computing", publicPage: true,
    problem: "A family of fast-changing Agent projects can mistake repeated vocabulary for a real invariant, promote local fixes too early, or preserve a theory after owner-native evidence has changed.",
    capability: "Runs cross-project falsification, strong-baseline comparison, research-frontier calibration, historical dogfood, and causal explanation studies; it promotes compact world-model priors while leaving current product truth with each owning repository.",
    maturity: "Active research, synthesis, and conformance root", audience: "Researchers and system designers asking which Agent-native distinctions survive independent domains, counterexamples, historical comparison, and deletion pressure.",
    latestProof: "EX3–EX7 froze 17 responsibility families across five independent surfaces and recorded 1,326/1,326 exact Agent decisions; compact causal prose matched richer representations at lower token burden. HD1–HD5 have now source-locked 200 historical innovation trajectories and 60 Deep Anchors across 1760–1969 while keeping the original theory frozen.", flagshipSlug: "history-did-not-prove-us-right",
    summary: "The scientific synthesis layer for Ordivon. Computing asks which distinctions recur, why they exist, and when they should be narrowed or deleted; it is not a global current-state authority.",
    state: "Active. Computing owns research synthesis and promoted world-model knowledge, while exact current implementation, operation, and domain truth remain in the projects that produce them.",
    evidence: [{ value: "1,326 / 1,326", label: "EX3–EX7 exact decisions" }, { value: "200", label: "source-locked historical trajectories" }, { value: "60", label: "historical Deep Anchors through HD5" }],
    repository: "https://github.com/zycxfyh/ordivon-computing", href: "/projects/computing", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "project:human", kind: "project", slug: "human", title: "Ordivon Human", lifecycle: "active", group: "Research and specification",
    label: "Human trajectories and practical autonomy", category: "research", availability: "research", publicPage: true, index: "07",
    thesis: "Study concrete human problems through bounded, conditional, privacy-preserving paths rather than a universal model or automated adviser.",
    question: "Can a practical path improve personal economic autonomy without hiding trade-offs, overclaiming evidence, or becoming individualized high-consequence advice?",
    owns: ["Human research questions", "Practical E-series paths", "Methods and limitations", "Ethical and privacy boundaries"],
    boundary: ["No personal scoring system", "No individual financial or medical advice", "No universal human model"],
    problem: "Abstract human research often fails to become actionable, while individualized advice can overclaim evidence and create privacy or high-consequence risk.",
    capability: "Completed a first bounded research cycle on sustainable personal economic autonomy, producing an E0–E9 practical path and six-case structural review.",
    maturity: "Completed first research cycle; conditional findings", audience: "Readers, practitioners, and researchers seeking explicit assumptions, examples, limitations, and reusable decision structure.",
    latestProof: "HUMAN-ECON-001 completed its admitted cycle without automatically expanding into E10 or a personal adviser product.",
    summary: "Problem-driven research into concrete human life trajectories. Human converts first-principles inquiry into practical paths while preserving conditions, limitations, and privacy.",
    state: "The first economic-autonomy cycle is complete. A new cycle begins only after another concrete problem is explicitly admitted; no continuous personal profile or recommendation service is active.",
    evidence: [{ value: "E0–E9", label: "practical path" }, { value: "6", label: "structural cases" }, { value: "1", label: "completed research cycle" }],
    repository: "https://github.com/zycxfyh/ordivon-human", href: "/projects/human", updatedAt: portfolioUpdatedAt,
  },
  securityProject,
  {
    id: "project:studio", kind: "project", slug: "studio", title: "Ordivon Studio", lifecycle: "active", group: "Applications and capability",
    label: "Cross-medium creation and empirical expression research", category: "application", availability: "research", publicPage: true, index: "09",
    thesis: "Expression changes what an observer can perceive and infer, so Agents must inspect the rendered artifact and ground creative claims in exact encounter evidence rather than one taste score.",
    question: "How can an Agent create and improve human-facing work at machine speed without turning internal preference, search winners, or model interpretation into creative truth?",
    owns: ["Cross-medium production cognition", "Rendered artifact perception", "Grounded meaning experiments", "Creative research validity and scoped priors"],
    boundary: ["No ownership of domain truth", "No universal taste or reward model", "No human-response claim from Agent-observer evidence"],
    problem: "Agent generation is cheap enough to create many plausible variants, but source correctness, visual polish, model preference, and even a statistically strong searched winner do not establish what the artifact communicates or whether the effect generalizes.",
    capability: "Provides a shared FRAME→BIND→EXPRESS→RENDER→AUDIT→DECIDE production cognition plus rich article/video/audio perception, evidence-grounded semantic probes, and a tested search/holdout discipline for bounded creative interventions.",
    maturity: "Active creative production and empirical research system", audience: "Agent builders, designers, writers, and researchers testing how generated artifacts carry meaning and how creative evidence should survive across media and encounters.",
    latestProof: "R4–R6 separated observability from explanatory power, grounding from ontology labels, and visible winners from search-aware evidence; a 5,000-candidate zero-effect search produced an apparently strong winner that failed corrected and pristine-holdout evidence.", flagshipSlug: "a-better-looking-result-can-still-be-noise",
    summary: "The expression laboratory for Ordivon. Studio helps Agents create, perceive, audit, and experimentally learn from real artifacts without claiming that one model score represents human taste or truth.",
    state: "Active research and production equipment. Agent-observer consequence has been tested on owned artifacts; human comprehension, preference, trust, memory, and behavior remain separate unproven claims.",
    evidence: [{ value: "5,000", label: "zero-effect candidates in R6 search attack" }, { value: "28", label: "official grounded-meaning Provider calls" }, { value: "97.92%", label: "replicated grounded Agent-observer acquisition" }],
    repository: "https://github.com/zycxfyh/ordivon-studio", href: "/projects/studio", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "project:web", kind: "project", slug: "web", title: "Ordivon Web", lifecycle: "active", group: "Publication",
    label: "Public orientation and dated interpretation", category: "publication", availability: "internal", publicPage: false,
    summary: "The public interface that explains the project family, organizes research and writing, and points back to owning repositories without copying their technical truth.",
    state: "Static publication and navigation layer; no CMS, live product database, or request-time application server.",
    evidence: [{ value: "static", label: "deployment model" }, { value: "MDX", label: "publication source" }, { value: "0", label: "live fact databases" }],
    repository: "https://github.com/zycxfyh/ordivon-web", updatedAt: siteUpdatedAt,
  },
];

export const questions: QuestionDefinition[] = [
  {
    id: "question:computing-smallest-core", kind: "question", slug: "smallest-agent-native-core", projectSlug: "computing",
    title: "Which Agent-native responsibilities remain after strong classical baselines?",
    summary: "Use mature workflow, retrieval, idempotency, and Provider systems to delete shared abstractions that do not own a distinct failure.",
    importance: "A proposed core becomes permanent inheritance and must survive stronger alternatives and multiple workloads.",
    hypothesis: "Task continuity belongs in Host, Agent Run semantics in Harness, physical execution truth in Runtime, and most other mechanics can remain in mature or domain-owning systems.",
    currentJudgment: "Answered within Round 1. Strong baselines reduced the proposed core; later Host and Harness extraction clarified the surviving ownership split without adding a universal Agent platform.",
    nextStep: "Use the result as an admission test for every new shared contract; reopen only when a materially different workload exposes an unowned non-bypassable responsibility.",
    falsifier: "A real workload repeatedly fails because a stable responsibility cannot remain in Host, Harness, Runtime, a mature system, or the owning domain.", state: "answered", href: "/research/smallest-agent-native-core", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:computing-async-join", kind: "question", slug: "async-waiting-and-join", projectSlug: "computing",
    title: "Which Task Runtime objects are required by asynchronous waiting and Join semantics?",
    summary: "Determine the smallest durable objects required when work waits, fans out, and later joins.",
    importance: "Without explicit waiting and Join semantics, a Host or Runtime will hide continuity inside process state, polling loops, or a workflow engine it does not own.",
    hypothesis: "A thin set of durable dependency edges, wait conditions, Join policy, and Ready Frontier state is sufficient; scheduling and workflow authoring can remain outside the core contracts.",
    currentJudgment: "Open. Round 1 showed that mature workflow engines can carry durable work mechanics, but no interrupted fan-out and fan-in workload has yet proved which semantic Join facts must remain visible above those mechanics.",
    nextStep: "Run one real Task that fans out across replaceable workers, waits through interruption, and joins without reconstructing admitted state.",
    falsifier: "If existing Task, Job, Outcome, workflow state, and typed relation objects express waiting and Join behavior without ambiguity or hidden durable facts, add nothing.", state: "open", href: "/research/async-waiting-and-join", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:computing-second-workload", kind: "question", slug: "contracts-across-a-second-workload", projectSlug: "computing",
    title: "Which contracts survive a second independent workload without being tailored to one repository?",
    summary: "Use unrelated applications to distinguish general contracts from local accommodations.",
    importance: "A contract that only explains the workload that produced it is documentation, not a shared computing boundary.",
    hypothesis: "Task continuity, Run evidence, physical execution identity, and recovery should survive materially different workloads through adapters.",
    currentJudgment: "Strongly supported but not closed. Game reused Host semantics and removed duplicate authority; Harness independently extracted. Another non-Game domain remains useful pressure.",
    nextStep: "Apply the current Host, Harness, and Runtime split to another domain and record every requested exception before promoting new fields.",
    falsifier: "Repeated workload-specific exceptions are required to preserve progress or verification.", state: "testing", href: "/research/contracts-across-a-second-workload", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:computing-calibrated-non-action", kind: "question", slug: "calibrated-non-action", projectSlug: "computing",
    title: "When should an Agent act, wait, observe, refuse, reconcile, or request a decision?",
    summary: "Treat non-action as a timed, evidence-bearing decision rather than the absence of Agent capability.",
    importance: "Acting too early can duplicate or commit the wrong Effect; waiting too long can lose a deadline, resource, or strategic option. Static approval-everywhere and model-only escalation both waste scarce attention or miss consequence boundaries.",
    hypothesis: "Host-local DecisionRequests, explicit UNKNOWN and wait states, deadlines, evidence requirements, and paired act/abstain evaluation can preserve authorized utility with fewer operator interruptions than uniform approval rules.",
    currentJudgment: "Testing with a stronger real-domain non-action case. Finance QB6 let one Agent request exact read-only evidence rather than infer missing execution facts, then update from more_research to no_op when the current minimum contract exceeded both the frozen 10% target and existing 25% canary bound; the branch ended before simulation, Decision, Proposal, or financial write.",
    nextStep: "Repeat evidence-conditioned act/abstain trajectories in materially different domains and with state changes that make a previously impossible action become expressible; retain new non-action state only if simpler owner-native evidence cannot reconstruct the same decision.",
    falsifier: "A simpler static policy or always-act baseline achieves equal authorized utility, timing, recovery, and operator cost with fewer persistent states.", state: "testing", href: "/research/calibrated-non-action", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:host-general-goal", kind: "question", slug: "host-general-repository-goal", projectSlug: "host",
    title: "Can Host complete a broader repository Goal without absorbing Harness or Runtime mechanics?",
    summary: "Test durable semantic continuity on open-ended engineering work while preserving the three-way ownership split.",
    importance: "Host matters only if commitments survive real decomposition, restart, replacement, and ambiguous effects.",
    hypothesis: "Host can own generic Task continuity and outcome admission while Harness owns Runs and Runtime owns physical execution.",
    currentJudgment: "Strongly supported but bounded. Deterministic and frozen repository workloads passed; a broader open-ended Goal remains outstanding.",
    nextStep: "Run one broader multi-step repository Goal through Host restart and Harness replacement while preserving unknown-effect handling and acceptance evidence.",
    falsifier: "Host must copy Run or process truth to continue correctly, or loses commitments when those facts remain with Harness and Runtime.", state: "testing", href: "/research/host-general-repository-goal", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:host-operational-surface", kind: "question", slug: "host-operational-surface", projectSlug: "host",
    title: "What operational surface is required before Host becomes dependable beyond architectural proof?",
    summary: "Pressure the current CLI, Doctor, backup, restore, and reconciliation through sustained operation.",
    importance: "A correct state model that cannot be inspected or recovered remains a laboratory artifact.",
    hypothesis: "The current small operational surface is sufficient; a general operations platform is unnecessary.",
    currentJudgment: "Testing. Schema-v3 operations, inspection, Doctor, backup/restore, and bounded reconciliation now exist; sustained long-lived operation remains the next pressure.",
    nextStep: "Operate Host through routine restart, backup, restore, state growth, and deliberately interrupted Tasks.",
    falsifier: "Ordinary service tooling plus the current Journal already exposes and recovers every required state, or a smaller surface proves sufficient.", state: "testing", href: "/research/host-operational-surface", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:host-harness-composition", kind: "question", slug: "harness-composition-and-completion", projectSlug: "harness",
    title: "Which Harness objects survive live Provider replacement without duplicating Host or Runtime state?",
    summary: "Preserve Provider-faithful execution while retaining only shared Run facts required for recovery and completion.",
    importance: "A shared Harness can erase Provider capabilities or create another Task database; direct adapters can duplicate Run evidence and recovery.",
    hypothesis: "Assignment, Run receipt, Tool-step evidence, recovery, and completion proposal survive while Provider Sessions remain local.",
    currentJudgment: "Answered by H1–H5 and later extraction. The durable Run boundary survived Codex and Hermes replacement; a universal Provider lifecycle did not.",
    nextStep: "Keep Provider lifecycles native and pressure only the current Harness public boundary through new adapters and workloads.",
    falsifier: "Direct Provider integrations remain equally correct with less repeated code, or the shared boundary destroys material Provider capability.", state: "answered", href: "/research/harness-composition-and-completion", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:ordivon-harness-v0", kind: "question", slug: "ordivon-harness-v0", projectSlug: "harness",
    title: "Does the caller-neutral Harness boundary remain valuable across different workloads and execution strategies?",
    summary: "Pressure immutable Run contracts, delegated execution mandates, Provider and Tool recovery, and completion proposals without reintroducing caller-specific persistence or a universal planner.",
    importance: "H3 removed the Host-backed product line, so Harness retention now depends on recurring caller-neutral execution and recovery value rather than compatibility with one upstream owner.",
    hypothesis: "Mandate-to-strategy-to-Run-contract compilation plus durable Provider and Tool continuity will transfer to another materially different caller or workload with small permanent cost.",
    currentJudgment: "Testing with stronger Agent-owned discovery evidence. P4 proved the Agent could select repository observations without caller-preselected source slices but required 203 admitted observations. P5 replaced count minimization with decision value per observation: one negative control used only the repository map and abstained ignorantly, while the accepted branch consumed exact external failure evidence plus six Agent-selected source/reference investigations, reduced admitted observations to 8 (25.375× fewer), and still lawfully abstained because no causal baseline-red source defect was established. Durable exact history remained separate from the compact current Working View; no RAG, Context scheduler, generic evaluator, or mutation authority was added.",
    nextStep: "Continue testing whether Agent-owned observation selection transfers to materially different discovery workloads while preserving exact provenance, compact Working Views, and bounded abstention. Treat model-call/token efficiency as a separate pressure: P5 still used 12 Provider calls and 239,953 tokens despite the 25.375× observation reduction.",
    falsifier: "Direct Provider and Runtime integration matches the same interruption recovery, evidence, bounded authority, and completion handoff with less permanent Harness machinery.", state: "testing", href: "/research/ordivon-harness-v0", updatedAt: "2026-08-08",
  },
  {
    id: "question:runtime-structured-effect", kind: "question", slug: "runtime-structured-effect", projectSlug: "runtime",
    title: "Which repeated physical operation deserves a dedicated structured Runtime contract?",
    summary: "Require stable identity, enforceable preconditions, receipts, reconciliation, and ambiguity behavior before promoting another Tool.",
    importance: "Every Runtime primitive becomes a durable compatibility and recovery obligation inside the physical boundary.",
    hypothesis: "Only repeated operations with unreconstructable physical facts should become structured Runtime contracts; opaque execution remains effect-opaque.",
    currentJudgment: "Testing after contraction. Structured Patch earned a contract; broader external semantics did not move into Runtime.",
    nextStep: "Evaluate new friction only after repeated real use demonstrates a physical fact that generic execution cannot safely preserve.",
    falsifier: "Generic execution plus owner-local receipts and direct reconciliation preserve the same result with less permanent machinery.", state: "testing", href: "/research/runtime-structured-effect", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:runtime-boundary-friction", kind: "question", slug: "runtime-boundary-friction", projectSlug: "runtime",
    title: "Which remaining friction belongs above Runtime rather than becoming another primitive?",
    summary: "Prevent semantic convenience, environment closure, or external-effect policy from expanding the physical execution authority without a reproduced unreconstructable fact.",
    importance: "Every Runtime primitive becomes permanent compatibility, recovery, and release debt inside the physical authority boundary.",
    hypothesis: "A new primitive is justified only when a repeated physical fact cannot be reconstructed safely after interruption or when generic execution cannot preserve its exact identity and replay semantics.",
    currentJudgment: "Strongly supported through P0–P5 and completed HP0. HP0-C added a storage-authority falsifier rather than a generic cleanup service: current execution used Workspace-scoped build targets while 16.84 GB of legacy source-scoped build cache remained falsely protected by repository-open state and an obsolete migrate path could still manufacture more unused bytes. After aligning retention with actual current consumers, production removed 11/11 legacy source_build candidates totaling 16,837,908,578 bytes with zero failures, zero Workspace-cache selections, preserved package-manager ownership and durable Artifact history, and remained healthy after prune.",
    nextStep: "Keep already-graduated execution and retention laws closed unless a new physical falsifier appears. Future ledger archival, package-cache pressure, and dirty-Workspace governance require separate owner-specific authority rather than age/size/high-watermark deletion rules.",
    falsifier: "A repeated failure cannot be recovered, replayed, or explained without a new durable Runtime-owned physical fact, or an existing structured effect cannot preserve correctness under a materially different execution target.", state: "testing", href: "/research/runtime-boundary-friction", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:world-correlated-recovery", kind: "question", slug: "world-correlated-recovery", projectSlug: "world",
    title: "Did a shared World Interaction improve correlated external recovery?",
    summary: "Record the negative result that direct owner-local integration carried the tested external recovery responsibilities.",
    importance: "A shared layer should exist only if it prevents a reproduced failure more cleanly than Provider-native receipts, Host state, and Runtime correlation.",
    hypothesis: "A shared World identity would be necessary to bind path and Provider execution across response loss.",
    currentJudgment: "Answered negatively. W1 and subsequent experiments did not justify a shared World authority; the active repository retains Provider-native and machine-local capabilities only.",
    nextStep: "Keep the question closed unless a new external workload reproduces an unowned failure that direct integration cannot reconcile.",
    falsifier: "A new workload repeatedly loses necessary continuity despite Provider-native receipts, Host correlation, Runtime evidence, and machine-local observation.", state: "answered", href: "/research/world-correlated-recovery", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:world-boundary-value", kind: "question", slug: "world-boundary-value", projectSlug: "world",
    title: "What remains valuable after the shared World layer is removed?",
    summary: "Separate retained operational capability from the rejected semantic project thesis.",
    importance: "Useful adapters and network tools should not reactivate a service, database, broker, or universal schema that failed its admission test.",
    hypothesis: "Cloudflare Provider operations and private network tooling can remain owner-local while shared World semantics stay deleted.",
    currentJudgment: "Answered for the current repository. Two capability families remain; the shared semantic authority is rejected and archived.",
    nextStep: "Maintain the retained capabilities against their own operational contracts; reopen shared architecture only after a reproduced cross-owner failure.",
    falsifier: "The retained capabilities require one recurring semantic fact that no Provider, Host, Runtime, network state, or caller can own directly.", state: "answered", href: "/research/world-boundary-value", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:computing-causal-explanation", kind: "question", slug: "causal-responsibility-explanation", projectSlug: "computing",
    title: "What is the smallest explanation that preserves the causal boundaries an Agent needs?",
    summary: "Compare compact owner-native causal prose with richer cards, relation vocabularies, and explicit diagnostic grammars before promoting another mandatory representation.",
    importance: "A research system can become harder to use when every useful distinction is serialized into default context, even when the richer representation adds no decision value.",
    hypothesis: "Compact causal prose is sufficient for ordinary Agent decisions when it states the relevant proof owner, semantic owner, consequence/currentness boundary, and material non-implications.",
    currentJudgment: "Answered on the EX3–EX7 Agent-facing surfaces. All treatments reached the same exact-action ceiling across 1,326 accepted decisions; richer representations added token burden, so the preregistered smallest-non-inferior rule selected compact prose.",
    nextStep: "Reopen only after a consequential failure under strong compact prose, or begin a separate human-comprehension program with human evidence rather than Agent proxies.",
    falsifier: "A harder open-ended or materially different decision surface repeatedly fails under compact causal prose while a frozen richer representation succeeds without introducing a new authority ambiguity.", state: "answered", href: "/research/causal-responsibility-explanation", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:world-minimal-boundary", kind: "question", slug: "world-minimal-boundary", projectSlug: "world",
    title: "Which World responsibilities still earn permanent ownership after deletion pressure?",
    summary: "Archive stale active-history material, delete research-only APIs, replay the same mixed failures, and retain only cross-owner reality relations whose absence recreates a current failure.",
    importance: "A broad World layer can duplicate Provider, Host, Runtime, Workstation, and domain truth while also making old research easier for an Agent to mistake for current authority.",
    hypothesis: "A narrow cross-owner relation and reconciliation boundary survives while routing, network mechanics, provider truth, and physical execution remain owner-native.",
    currentJudgment: "Answered for the current HP0–HP8 boundary. Current retrieval improved 7/9→9/9 after historical contraction, research-only ForeignEgress/EffectPath machinery was deleted, and the same 96 mixed-failure invocations passed after deletion.",
    nextStep: "Keep the boundary demand-triggered. Reopen only when a named current workload reproduces a cross-owner failure the remaining direct owners cannot preserve cleanly.",
    falsifier: "A real remote or multi-owner workload repeatedly loses necessary observation, transfer, currentness, or consequence continuity despite Provider-native evidence plus Host, Runtime, Workstation, and domain ownership.", state: "answered", href: "/research/world-minimal-boundary", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:finance-real-capital-agent", kind: "question", slug: "finance-real-capital-agent", projectSlug: "finance",
    title: "Can Agent capital judgment remain separate from financial effect authority?",
    summary: "Pressure quantitative research, proposal/decision semantics, signer and credential authority, one-shot dispatch, and venue reconciliation without turning a backtest or model conclusion into permission to trade.",
    importance: "Real-capital systems fail dangerously when predictive evidence, semantic judgment, API permission, dispatch identity, and final venue consequence are treated as the same state.",
    hypothesis: "Agent judgment can remain flexible while deterministic Finance/Executor machinery owns exact effect identity, admission, dispatch evidence, and reconciliation under explicit deployment assurance.",
    currentJudgment: "Testing with a narrower research/effect split. C2-L retained same-machine effect correctness while rejecting hostile-root isolation as universal. QB3c then rejected mandatory Quant Bedrock constitution injection after the unchanged treatment reversed sign on a second sealed carrier. QB6 showed owner-conditioned research can request read-only execution evidence and end in no-op before any transition or effect machinery.",
    nextStep: "Keep live submission disabled. Continue separating replicated research value, owner-conditioned usefulness, physical expressibility, semantic transition intent, and effect authority; any live canary still requires a separate explicit transition with current credential/signer/reconciliation evidence.",
    falsifier: "A simpler owner-native venue integration preserves the same effect identity, one-shot dispatch, evidence, and reconciliation with less permanent Finance machinery, or the Agent/effect boundary fails under a bounded canary.", state: "testing", href: "/research/finance-real-capital-agent", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:studio-creative-validity", kind: "question", slug: "creative-empirical-validity", projectSlug: "studio",
    title: "How do we know a creative improvement is not just a searched winner or model preference?",
    summary: "Separate richer perception, evidence-grounded meaning, real encounter, typed consequence, search history, and independent holdout before promoting a creative prior.",
    importance: "Agent-scale generation makes false winners cheap: a system can search until one variant looks exceptional and then mistake selection noise or one observer class for creative truth.",
    hypothesis: "Exact artifact identity, search-aware evidence, realized encounter, grounded consequence, and independent OOS support can support bounded creative learning without a universal reward model.",
    currentJudgment: "Testing after R4–R6. Rich perception earned medium-local equipment, grounding proved more stable than fine labels, and R6 showed a 5,000-candidate zero-effect search could manufacture an impressive winner that failed stronger evidence. One reveal-order effect replicated directionally on pristine content for one Agent-observer class.",
    nextStep: "Change observer class/provider and repeat frozen interventions across new artifact worlds. Introduce human evidence only when making a human comprehension, preference, trust, memory, or behavior claim.",
    falsifier: "A simpler production/evaluation loop reaches the same grounded and OOS conclusions without preserving search history or encounter identity, or the retained creative effect disappears consistently under independent observers and content.", state: "testing", href: "/research/creative-empirical-validity", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:computing-evidence-current-applicability", kind: "question", slug: "evidence-current-applicability", projectSlug: "computing",
    title: "When does valid evidence stop being current enough to govern a decision?",
    summary: "Separate evidence integrity from current applicability and test whether exact owner-native dependency or currentness revalidation is enough before inventing a generic freshness layer.",
    importance: "Authentic evidence can outlive the facts that made it actionable, while generation numbers, age, or browser success can also invalidate too much or prove too little.",
    hypothesis: "Many currentness decisions can remain owner-native: preserve exact evidence identity, bind the dependencies that matter to the claim, and revalidate those dependencies against the current authority before consequence.",
    currentJudgment: "Strongly supported but scoped. Security EC1 kept one old projection byte-identical while a metadata-only source advance remained APPLICABLE, a semantic dependency change produced STALE_NOT_APPLICABLE, and unavailable current authority produced UNKNOWN. World capability expiry and source-bound Web projection independently reproduce the same causal distinction under different owner-native currentness rules.",
    nextStep: "Pressure a materially different time-, lease-, revocation-, or cross-owner-currentness consumer. Add shared freshness machinery only if exact owner-local dependencies cannot express the reproduced failure cleanly.",
    falsifier: "Several independent domains repeatedly require the same cross-owner currentness fact that cannot remain with the evidence owner or be reconstructed from exact dependencies without duplicating authority.", state: "testing", href: "/research/evidence-current-applicability", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:finance-context-treatment-replication", kind: "question", slug: "context-treatment-replication", projectSlug: "finance",
    title: "When does a useful research constitution earn default Agent context?",
    summary: "Freeze context treatments before holdout reveal and require replicated marginal benefit before turning persuasive domain knowledge into mandatory prompt state.",
    importance: "A constitution can change Agent behavior, candidate selection, reasoning style, and apparent caution while still failing to improve the objective consistently across worlds.",
    hypothesis: "Domain knowledge should remain equipment, priors, baselines, and falsifiers unless an unchanged context treatment shows stable sealed benefit across materially different carriers after token and search cost are counted.",
    currentJudgment: "Answered for the current Quant Bedrock default-context claim. Constitution-only looked less bad than control on QB3b but remained negative; the unchanged treatment became materially worse than control on the second sealed QB3c carrier and used about 27.5% more Provider tokens. Mandatory injection has not earned default status.",
    nextStep: "Keep Quant Bedrock available as equipment rather than mandatory context. Reopen only with a frozen treatment that replicates benefit across additional carriers/providers without holdout-guided tuning and beats a simpler on-demand equipment path.",
    falsifier: "A frozen constitution treatment repeatedly improves sealed outcomes across independent carriers/providers at acceptable marginal cost, while equivalent on-demand retrieval or equipment does not recover the benefit.", state: "answered", href: "/research/context-treatment-replication", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:harness-provider-protocol-continuation", kind: "question", slug: "provider-protocol-continuation", projectSlug: "harness",
    title: "Which Provider-required state must survive a Tool turn without becoming Agent cognition?",
    summary: "Separate model-visible semantic history from opaque Provider continuation bytes whose authority comes from an exact prior Provider Tool result and lineage.",
    importance: "A semantic transcript can look complete while a native Provider still rejects the next request if protocol continuation is missing; copying opaque bytes into messages would blur cognition, privacy, and Provider authority.",
    hypothesis: "A small Adapter-bound continuation object can preserve Provider protocol continuity across crash/reopen while remaining hidden from Agent messages and without replaying the physical Tool effect.",
    currentJudgment: "Answered within Harness X2. A live Gemini falsifier returned 200 with the exact continuation and 400 INVALID_ARGUMENT when only the signature was stripped. A 940-byte continuation then survived crash/reopen, remained hidden from Agent messages, completed LIVE_CONTINUATION_OK, and caused zero Runtime redispatch. ProviderToolContinuation was the only new primitive earned across five pressured frontiers.",
    nextStep: "Keep the primitive Provider-neutral and small. Reopen abstraction only when another native Provider exposes a materially different continuation fact that cannot fit the same Adapter/turn/model-call authority and privacy boundary.",
    falsifier: "Official Provider stateful APIs or direct adapters preserve the same crash/reopen Tool continuation with less shared Harness machinery, or another Provider requires continuation semantics that invalidate the current authority shape.", state: "answered", href: "/research/provider-protocol-continuation", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:computing-semantic-order", kind: "question", slug: "semantic-order-and-canonicalization", projectSlug: "computing",
    title: "Does canonical evidence order make an Agent understand the evidence better?",
    summary: "Separate deterministic byte identity from semantic tractability, and falsify wire/evaluator ambiguity before attributing Agent errors to presentation order.",
    importance: "Stable sorting and maps are mechanically attractive enough to become permanent Context infrastructure even when the observed model variance actually comes from a broken Tool wire or ambiguous oracle.",
    hypothesis: "Canonicalization should be retained for owner-declared identity/replay needs but promoted as a model-facing representation only after an unambiguous prospective experiment beats raw presentation.",
    currentJudgment: "Answered for P11. Six unordered datasets collapsed 720 raw permutation digests to one stable identity, but after invalidating a truncated Tool-wire campaign and clarifying an ambiguous evaluator target, raw presentation scored 44/48 strict versus 42/48 stable list and 43/48 identity map. No semantic normalization advantage survived.",
    nextStep: "Use deterministic canonicalization only where owner semantics require stable identity. Reopen model-facing order machinery after a new unambiguous workload reproduces material order sensitivity that simpler evaluator/prompt clarification cannot remove.",
    falsifier: "Across independent clear-oracle workloads, one canonical representation repeatedly improves semantic accuracy over raw presentation and the gain survives Provider changes without erasing meaningful event order.", state: "answered", href: "/research/semantic-order-and-canonicalization", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:computing-historical-world-model", kind: "question", slug: "historical-world-model-dogfood", projectSlug: "computing",
    title: "Which Agent-era world-model laws survive historical out-of-distribution pressure?",
    summary: "Freeze the modern theory, reconstruct history before coding it, preserve failures and anti-cases, and let independent epochs narrow or contradict the candidate laws before any cross-era promotion.",
    importance: "A modern systems theory can appear universal if it chooses famous examples and retrospective labels after seeing the outcomes. Historical OOD pressure is useful only when the theory cannot move to fit the evidence.",
    hypothesis: "Materially different scientific and industrial worlds will repeatedly expose a smaller set of structural pressures while narrowing Agent-era laws that are domain-specific, over-general, or artifacts of our present taxonomy.",
    currentJudgment: "Testing after HD1–HD6. The campaign has source-locked 240 trajectories and 72 Deep Anchors across 1760–1999 with the original S1–S10/F1–F7 frozen. R1–R8 now recur across all six epochs, but HD6 weakened confidence in the current taxonomy: fresh independent exact agreement was only 64/120 (53.3%) and coarse applicability 77/120 (64.2%); removing repeated scaffold boilerplate improved these only to 60.8% and 67.5%. Six-epoch recurrence therefore strengthens Reality recurrence while measurement/taxonomy confidence remains deliberately unpromoted.",
    nextStep: "Complete HD7–HD8 through 2026 under the unchanged theory and stronger late-epoch leakage warnings, then run HD9 cross-era adversarial/redundancy/negation-condition review before promoting, merging, narrowing, or deleting any recurrent structure.",
    falsifier: "Later epochs produce clean contradictions, supposedly recurrent residuals disappear outside early industrial history, anti-laws prove Agent-era-specific, or independent coding/anti-case pressure shows that an apparent cross-era law was mainly a taxonomy artifact.", state: "testing", href: "/research/historical-world-model-dogfood", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:web-research-interface", kind: "question", slug: "web-research-interface", projectSlug: "web",
    title: "Can the public site explain changing research judgment without becoming a second fact system?",
    summary: "Use a stable project map, dated publications, Feynman-style causal explanation, and exact owner links while keeping rendered encounter evidence separate from technical truth.",
    importance: "A project directory without synthesis is opaque; a copied fact graph drifts; and technically correct source can still produce a misleading reader encounter.",
    hypothesis: "Public orientation can remain authored and progressively disclosed while repositories and research records retain technical truth and Web owns only explanation, navigation, rendering, and encounter evidence.",
    currentJudgment: "Testing after source-bound publication, ordinary-production, and R6 encounter work. Web now distinguishes current orientation from dated argument, can bind owner revisions without mirroring full implementation state, and has recorded exact Chromium assignment/exposure/pixel evidence for a controlled expression intervention.",
    nextStep: "Use the Feynman reconstruction in ordinary publication and observe whether fresh readers or Agents can identify Ordivon's purpose, project responsibilities, current maturity, evidence boundary, and next destination without first learning the internal ontology.",
    falsifier: "The authored model repeatedly drifts, a reader needs copied implementation detail to understand current responsibility, or rendered encounter evidence exposes a material implication that source-level validation consistently misses.", state: "testing", href: "/research/web-research-interface", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:game-agent-native-mechanics", kind: "question", slug: "game-agent-native-mechanics", projectSlug: "game",
    title: "Which game structures become possible only when Agents persist and act through one World history?",
    summary: "Separate genuinely Agent-native mechanics from classical systems with probabilistic dialogue attached.",
    importance: "Without a falsifiable distinction, Agent-native game design becomes a marketing label.",
    hypothesis: "Persistent roles, actor-local knowledge, typed communication, player doctrine, and recoverable commitments enable distinct play.",
    currentJudgment: "Testing with GX1 strategic-agency evidence. Selected Station Zero v3 states contain materially different reachable futures, but strategy existence, policy accessibility, and model realization are now separated. In the frozen Core-carrier state the model already saw the Core, primary objective, and legal extraction route yet chose cooling repair 36/36 across current/tag/order conditions; six live continuations completed the Core 0/6. A deterministic continuous-carrier commitment could complete it while a one-step deviation could not. A generic structured primaryObjective prototype was deleted after Candidate-order reversal deterministically changed tactics, so more explicit goal representation has not earned promotion.",
    nextStep: "Move to GX2 pressure-versus-strategic-collapse around already-proven strategy basins, and later human/live-Provider comparison. Do not manufacture agency with objective oracles, prescriptive Candidate prose, strategy routers, or scalar utility until those mechanisms survive state/world/presentation falsifiers.",
    falsifier: "The same player experience and mechanics can be reproduced by a simpler deterministic or single-Agent system with lower cost.", state: "testing", href: "/research/game-agent-native-mechanics", updatedAt: "2026-08-08",
  },
  {
    id: "question:human-economic-autonomy", kind: "question", slug: "human-economic-autonomy", projectSlug: "human",
    title: "What practical path can increase personal economic autonomy without materially reducing life quality?",
    summary: "Translate first-principles economic reasoning into a conditional, practical path with explicit trade-offs and no individualized advice claim.",
    importance: "People need usable decision structure, but universal prescriptions and personal scoring can obscure constraints, privacy, and high-consequence uncertainty.",
    hypothesis: "A staged E0–E9 path with simple cases, conditions, stopping rules, and structural review can improve practical reasoning without becoming an adviser product.",
    currentJudgment: "Answered for the first admitted cycle. HUMAN-ECON-001 produced the E0–E9 practical path and six-case review; conclusions remain conditional and do not automatically create E10.",
    nextStep: "Use and critique the completed path. Admit a new Human research cycle only when another concrete problem and boundary are explicit.",
    falsifier: "The path cannot guide decisions without individualized data, hides major quality-of-life costs, or adds complexity beyond ordinary planning tools.", state: "answered", href: "/research/human-economic-autonomy", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:security-adversarial-trajectory", kind: "question", slug: "security-adversarial-trajectory", projectSlug: "security",
    title: "Which Agent-native laws survive in persistent adversarial worlds?",
    summary: "Separate actor intent and observation, exact authority, physical consequence, sensor evidence, world truth, recovery ownership, and evaluation while autonomous opponents change the world over time.",
    importance: "Once actors can adapt, deceive, request consequential effects, and outlive one controller, one reward or action-success flag is not merely incomplete—it can collapse distinct authorities and make interruption or recovery unsafe.",
    hypothesis: "A thin Security domain layer for contested-world identity, asymmetric observation, exact RangeAuthority, independent truth/evidence, and adversarial evaluation remains necessary above mature simulation, hypervisor, Host, Harness, and Runtime mechanisms; broader Campaign, Organization, and distributed recovery structure should be admitted only after experiments force it.",
    currentJudgment: "Security now has an accepted AE0–AE2 adversarial-epistemics line above AF2/AF3. AE0 showed UNKNOWN can justify information acquisition; AE1 showed it can persist through a costly waiting opportunity; AE2 adds two independently sourced sensor observations that disagree while neither is world truth. With no source priority/history, one shared Defender policy refuses arbitrary source selection and requests adjudication; authoritative current world truth later resolves the current property while preserving the contradictory sensor history. Trust/Reputation, confidence, source-history, freshness, and a new communication core remain unforced.",
    nextStep: "Remove cheap adjudication or make repeated source history causally useful, then test whether provenance plus UNKNOWN still suffices before admitting the smallest durable source-reliability, confidence, freshness, or trust representation.",
    falsifier: "Mature range/simulation authority plus ordinary Host, Harness, Runtime, and source-native evidence express the same contested-world identity, consequence, recovery, and evaluation distinctions with fewer Security-specific contracts.", state: "testing", href: "/research/security-adversarial-trajectory", updatedAt: "2026-08-08",
  },
  {
    id: "question:security-opponent-state-transfer", kind: "question", slug: "opponent-state-transfer", projectSlug: "security",
    title: "Does compiled opponent state retain value across seeds, held-out policies, Context loss, and Harness replacement?",
    summary: "Distinguish durable strategic information from fixture-specific explanation and provider-specific reasoning style.",
    importance: "Round 1 improved local switch recognition and preserved richer hypotheses, but all retained model Trials failed the objective. Without transfer, opponent state is descriptive overhead rather than durable capability.",
    hypothesis: "Explicit opponent hypotheses and revisions will improve held-out switch recognition, resource timing, and objective completion when transcript Context is truncated or the Harness is replaced, provided the state is compiled from verified observations rather than model narrative alone.",
    currentJudgment: "Open after mixed Round 1 evidence. The local opponent-aware actor improved diagnosis and objective rate, one Codex strategic Trial recognized a switch, Hermes outcomes were unchanged, and no model Trial completed the genuine objective. No causal or transferable advantage is established.",
    nextStep: "Compare transcript-only and compiled-state conditions across multiple seeds, held-out opponent policies, bounded Context loss, and both Codex and Hermes Harness replacement.",
    falsifier: "A reactive policy or transcript-only Agent matches held-out objective, information, timing, and recovery outcomes with lower state and maintenance cost.", state: "testing", href: "/research/opponent-state-transfer", updatedAt: portfolioUpdatedAt,
  },
];

export function getArchitectureRoleById(id: string) { return architectureRoles.find((item) => item.id === id); }
export function getArchitectureRoleBySlug(slug: string) { return architectureRoles.find((item) => item.slug === slug); }
export function getBoundaryById(id: string) { return boundaries.find((item) => item.id === id); }
export function getResearchPlaneById(id: string) { return researchPlanes.find((item) => item.id === id); }
export function getProjectById(id: string) { return projects.find((item) => item.id === id); }
export function getProjectBySlug(slug: string) { return projects.find((item) => item.slug === slug); }
export function getQuestionById(id: string) { return questions.find((item) => item.id === id); }
export function getQuestionBySlug(slug: string) { return questions.find((item) => item.slug === slug); }
export function getProjectForQuestion(questionId: string) { const question = getQuestionById(questionId); return question ? getProjectBySlug(question.projectSlug) : undefined; }
