import type { BoundaryDefinition, ProjectDefinition, QuestionDefinition, ResearchPlaneDefinition } from "@/lib/model/types";

export const siteUpdatedAt = "2026-08-02";
const portfolioUpdatedAt = "2026-08-02";

export const researchPlanes: ResearchPlaneDefinition[] = [
  {
    id: "system:computing", kind: "research-plane", slug: "computing", index: "R", title: "Computing", status: "active",
    summary: "The research and conformance plane that tests which shared contracts deserve to survive.",
    thesis: "Keep cognition, Task continuity, semantic execution, and machine execution separable—and delete abstractions that mature systems already carry.",
    question: "Which facts and contracts must remain stable when models, Hosts, tools, and execution backends change?",
    owns: ["Stack model", "Semantic contracts", "Reference experiments", "Conformance"],
    boundary: ["No production Tasks", "No physical Jobs", "No place in the execution path"],
    href: "/projects/computing", updatedAt: portfolioUpdatedAt,
  },
];

export const boundaries: BoundaryDefinition[] = [
  {
    id: "system:host", kind: "boundary", slug: "host", index: "01", title: "Host", maturity: "tested",
    summary: "The semantic control boundary that keeps Goals and Tasks continuous above replaceable sessions and processes.",
    thesis: "Replace the model session without replacing the Task.",
    question: "Which semantic state must survive when cognition, transport, and execution processes are replaced?",
    owns: ["Goals and Tasks", "Host journal", "Cognition contexts", "Outcomes"],
    boundary: ["No process ownership", "No model monopoly", "No Runtime mechanics"],
    href: "/projects/host", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "system:runtime", kind: "boundary", slug: "runtime", index: "02", title: "Runtime", maturity: "tested",
    summary: "The physical effect boundary that owns durable local execution identity, process state, and retained evidence.",
    thesis: "Commit one Agent action to local reality without losing what happened.",
    question: "Which execution facts cannot safely be reconstructed after interruption?",
    owns: ["Workspaces", "Jobs and Attempts", "Process trees", "Artifacts"],
    boundary: ["Trusted-local, not a sandbox", "No Goal ownership", "No invented exactly-once claims"],
    href: "/projects/runtime", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "system:world", kind: "boundary", slug: "world", index: "03", title: "World", maturity: "tested",
    summary: "A carrier for provider-native external adapters and private network operator tools, not an independent semantic authority.",
    thesis: "Keep external truth in providers and source-native observations; add no shared World state without a reproduced unowned failure.",
    question: "Which adapter-local facts prevent duplicate external effects or workstation path damage?",
    owns: ["Cloudflare adapter code", "Provider-native receipts and artifacts", "Private VPN operator tools"],
    boundary: ["No World service or database", "No universal interaction schema", "No Task or provider authority"],
    href: "/projects/world", updatedAt: portfolioUpdatedAt,
  },
];

export const architectureRoles = [...researchPlanes, ...boundaries];

export const projects: ProjectDefinition[] = [
  {
    id: "project:computing", kind: "project", slug: "computing", title: "Ordivon Computing", lifecycle: "active", group: "Foundations",
    label: "Contracts that survive replacement", architectureRoleId: "system:computing", publicPage: true,
    problem: "Agent systems can accumulate shared abstractions faster than real workloads justify them.",
    capability: "Compares proposed contracts against mature baselines and keeps only the responsibilities that survive replacement, interruption, and a deletion test.",
    maturity: "Active research foundation",
    audience: "Agent-system designers deciding which boundaries deserve to become shared infrastructure.",
    latestProof: "Strong workflow, retrieval, idempotency, and provider baselines reduced the proposed core instead of validating a larger platform.",
    flagshipSlug: "smaller-core-strong-baselines",
    summary: "The research and conformance root for persistent work performed with probabilistic models. Computing defines the contracts that other projects test rather than becoming another production runtime.",
    state: "The model-to-work stack and Harness H1–H5 are closed as canonical research. Computing now distinguishes mature Provider Harnesses from the ready Ordivon Harness v0 construction question for bare model APIs.",
    evidence: [{ value: "H1–H5", label: "boundary stages closed" }, { value: "493,294", label: "H5 reported tokens" }, { value: "1", label: "ready Harness construction question" }],
    repository: "https://github.com/zycxfyh/ordivon-computing", href: "/projects/computing", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "project:host", kind: "project", slug: "host", title: "Ordivon Host", lifecycle: "active", group: "Agent system",
    label: "Task continuity above sessions", architectureRoleId: "system:host", publicPage: true,
    problem: "A capable model can finish one run while the user's larger task, accepted decisions, and unfinished work disappear with the session.",
    capability: "Preserves goals, tasks, accepted decisions, assignments, and completion evidence above replaceable model runs and local processes.",
    maturity: "Tested architectural core",
    audience: "Developers building long-running agents that must survive restart, provider replacement, and ambiguous completion.",
    latestProof: "One repository task completed in both Codex→Hermes and Hermes→Codex orders while three injected faults were rejected or recovered.",
    flagshipSlug: "what-h1-h5-proved",
    summary: "A persistent agent control plane for goals, tasks, bounded cognition, candidate admission, harness assignment, effect proposals, verification, and outcomes. Model sessions and Runtime processes remain replaceable dependencies.",
    state: "Harness H1–H5 are closed: Host retained Task Attempt, Assignment generation, Run receipts, completion admission, and opaque Runtime correlation while rejecting a shared Provider lifecycle. The next bounded construction is Ordivon Harness v0 for bare model APIs.",
    evidence: [{ value: "H1–H5", label: "Harness boundary closed" }, { value: "2/2", label: "replacement orders accepted" }, { value: "3", label: "first faults survived" }],
    repository: "https://github.com/zycxfyh/ordivon-host", href: "/projects/host", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "project:runtime", kind: "project", slug: "runtime", title: "Ordivon Runtime", lifecycle: "active", group: "Agent system",
    label: "Committed local effects", architectureRoleId: "system:runtime", publicPage: true,
    problem: "Shell commands and transient processes do not preserve enough identity or evidence for a later agent to know what actually happened.",
    capability: "Turns admitted local operations into durable jobs, observable process state, bounded output, artifacts, cancellation, and restart recovery.",
    maturity: "Production-tested local runtime",
    audience: "Developers who need reliable local execution without turning the runtime into a workflow engine or semantic task owner.",
    latestProof: "Thirteen public tools supported Host correlation, replay, fresh-client recovery, and terminal evidence with no new Runtime semantic objects.",
    flagshipSlug: "runtime-after-core",
    summary: "The deterministic boundary between an agent decision and local machine execution. Runtime binds exact source and operation identity to durable jobs, process trees, bounded evidence, cancellation, reconciliation, and recovery.",
    state: "Production Runtime remains at thirteen public tools. Host H2/R2 proved cross-layer correlation, replay, recovery, and terminal evidence through existing request identity and opaque foreign references without adding Host Task semantics to Runtime.",
    evidence: [{ value: "13", label: "public tools" }, { value: "4", label: "opaque Host references" }, { value: "0", label: "new Runtime semantic objects" }],
    repository: "https://github.com/zycxfyh/ordivon-runtime", href: "/projects/runtime", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "project:world", kind: "project", slug: "world", title: "Ordivon World", lifecycle: "active", group: "World interaction",
    label: "Provider-native external capability", architectureRoleId: "system:world", publicPage: true,
    problem: "External effects and workstation network changes need exact owner-native identity and recovery without another synchronized authority.",
    capability: "Retains a Cloudflare Fetch/Browser adapter with receipts, artifacts, release and rollback, plus machine-specific VPN operator tools.",
    maturity: "Reduced operational carrier",
    audience: "Developers who need verifiable external adapters without a provider broker or World control plane.",
    latestProof: "W1 and WCP-0 through WXP-2 found no benefit from a shared World authority; the active tree deleted the experiments and retained only owner-local capabilities.",
    flagshipSlug: "link-edge-boundary",
    summary: "A repository carrier for two current capabilities whose authority remains in Cloudflare, network state, Host, and Runtime rather than in a new World database.",
    state: "The shared World layer is rejected. Historical experiments remain in Git; current code is limited to the Cloudflare adapter and private WSL/VPN tools.",
    evidence: [{ value: "0", label: "shared World authorities" }, { value: "2", label: "retained owner-local capabilities" }, { value: "W1+WCP", label: "negative architecture evidence" }],
    repository: "https://github.com/zycxfyh/ordivon-world", href: "/projects/world", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "project:web", kind: "project", slug: "web", title: "Ordivon Web", lifecycle: "active", group: "Public interface",
    label: "Research as an explorable system", publicPage: false,
    summary: "The public interface that connects stable projects, active research questions, and dated writing without duplicating repository truth.",
    state: "Web V2 is closed around static delivery, durable Question dossiers, an article-centered publication index, and a continuity-led visual thesis. Project and Question metadata now derive navigation without a second public fact registry.",
    evidence: [{ value: "15", label: "research dossiers" }, { value: "16", label: "published articles" }, { value: "3", label: "public content types" }],
    repository: "https://github.com/zycxfyh/ordivon-web", updatedAt: siteUpdatedAt,
  },
  {
    id: "project:game", kind: "project", slug: "game", title: "Ordivon Game", lifecycle: "active", group: "Agent-native application",
    label: "Persistent Agents inside a verified World", publicPage: false,
    summary: "Station Zero tests persistent single- and multi-Agent roles, partial knowledge, typed communication, player authority, deterministic World effects, replay, diagnosis, and exact comparison through shared Host semantics.",
    state: "Station Zero v0.1.0-alpha.1 is released as a source-playable developer Alpha with replay, evidence-linked diagnosis, exact run comparison, reload recovery, and clean archive verification.",
    evidence: [{ value: "v0.1.0-alpha.1", label: "released Alpha" }, { value: "406,855 B", label: "verified archive" }, { value: "2", label: "exact-comparison runs" }],
    repository: "https://github.com/zycxfyh/ordivon-game", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "project:security", kind: "project", slug: "security", title: "Ordivon Security", lifecycle: "active", group: "Adversarial agency",
    label: "Control under strategic opposition", publicPage: false,
    summary: "A research line for strategic adversarial agency, dynamic opponents, trajectory evidence, multidimensional outcomes, and evaluation when the acting subject adapts to observation and intervention.",
    state: "Round 1 completed 84 bounded Trials across a local dynamic-opponent World, CAGE Challenge 4, and model-backed diagnostics. The experimental method is retained; no Campaign engine, organization ontology, strategic state, custom cyber range, or general capability claim was promoted.",
    evidence: [{ value: "84", label: "bounded Trials" }, { value: "3", label: "experiment families" }, { value: "0", label: "strategic layers promoted" }],
    repository: "https://github.com/zycxfyh/ordivon-security", updatedAt: portfolioUpdatedAt,
  },
];

export const questions: QuestionDefinition[] = [
  {
    id: "question:computing-smallest-core", kind: "question", slug: "smallest-agent-native-core", projectSlug: "computing",
    title: "Which Agent-native responsibilities remain after strong classical baselines?",
    summary: "Use mature workflow, retrieval, idempotency, and provider systems to delete any shared abstraction that does not own a distinct failure.",
    importance: "A proposed core becomes permanent inheritance. It should contain only responsibilities that survive strong alternatives, multiple workloads, cost measurement, and a deletion test.",
    hypothesis: "Task meaning belongs in Host, physical execution truth in Runtime, and correlated external interaction may belong in World; durable workflow mechanics, generalized Context state, and provider-specific lifecycle can remain in mature systems or owning applications.",
    currentJudgment: "Answered within the Round 1 boundary. LangGraph and Temporal carried durable work state; current-revision retrieval matched the tested Context need; single-backend Effect machinery shrank to identity, UNKNOWN, correlation, reconciliation, and no blind redispatch; live provider replacement preserved Task state without proving model equivalence.",
    nextStep: "Use the result as an admission test in World W1 and Harness H4–H5. Reopen the shared-core boundary only when a materially different workload exposes an unowned non-bypassable responsibility.",
    falsifier: "A future workload repeatedly fails because a stable responsibility cannot remain in Host, Runtime, World, a mature workflow engine, or a provider-faithful adapter.", state: "answered", href: "/research/smallest-agent-native-core", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:computing-async-join", kind: "question", slug: "async-waiting-and-join", projectSlug: "computing",
    title: "Which Task Runtime objects are required by asynchronous waiting and Join semantics?",
    summary: "Determine the smallest durable objects required when work waits, fans out, and later joins.",
    importance: "Without explicit waiting and Join semantics, a Host or Runtime will hide continuity inside process state, polling loops, or a workflow engine it does not own.",
    hypothesis: "A thin set of durable dependency edges, wait conditions, Join policy, and Ready Frontier state is sufficient; scheduling and workflow authoring can remain outside the core contracts.",
    currentJudgment: "Open. Round 1 showed that mature workflow engines can carry durable work mechanics, but no interrupted fan-out and fan-in workload has yet proved which semantic Join facts must remain visible above those mechanics.",
    nextStep: "Run one real Task that fans out across replaceable workers, waits through interruption, and joins without reconstructing admitted state.",
    falsifier: "If existing Task, Job, Outcome, workflow state, and typed relation objects express waiting and Join behavior without ambiguity or hidden durable facts, add nothing.", state: "open", href: "/research/async-waiting-and-join", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:computing-second-workload", kind: "question", slug: "contracts-across-a-second-workload", projectSlug: "computing",
    title: "Which contracts survive a second independent workload without being tailored to one repository?",
    summary: "Use unrelated applications to distinguish general contracts from local accommodations.",
    importance: "A contract that only explains the workload that produced it is documentation, not a computing boundary.",
    hypothesis: "Task continuity, effect identity, evidence, and recovery contracts should survive materially different workloads through adapters rather than workload-specific core fields.",
    currentJudgment: "Strongly supported but not fully closed. Game implemented the immutable Host workload profile across a TypeScript deterministic World, single- and multi-Agent paths, response-loss recovery, and exact replay, then removed thirteen duplicate truth tables without changing World outcomes. A second non-Game external domain remains useful pressure.",
    nextStep: "Apply the surviving contracts to World W1 or another non-Game provider path and record every requested exception before promoting any further shared field.",
    falsifier: "If repeated workload-specific exceptions are necessary to preserve progress, split or narrow the claimed shared contract instead of generalizing it further.", state: "testing", href: "/research/contracts-across-a-second-workload", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:computing-calibrated-non-action", kind: "question", slug: "calibrated-non-action", projectSlug: "computing",
    title: "When should an Agent act, wait, observe, refuse, reconcile, or request a decision?",
    summary: "Treat non-action as a timed, evidence-bearing decision rather than the absence of Agent capability.",
    importance: "Acting too early can duplicate or commit the wrong Effect; waiting too long can lose a deadline, resource, or strategic option. Static approval-everywhere and model-only escalation both waste scarce attention or miss consequence boundaries.",
    hypothesis: "Host-local DecisionRequests, explicit UNKNOWN and wait states, deadlines, evidence requirements, and paired act/abstain evaluation can preserve authorized utility with fewer operator interruptions than uniform approval rules.",
    currentJudgment: "Testing. Round 1 reduced deterministic approval interruptions from 12 to 7 with no missed escalation in its designed cases, but those timings were estimated rather than measured with real operators. Security, Game, Runtime, and World now provide stronger act-versus-wait trajectories.",
    nextStep: "Run paired act/abstain trajectories with real timing, consequence, expiry, and recovery data across one authority request, one UNKNOWN Effect, and one adversarial policy switch.",
    falsifier: "A simpler static policy or always-act baseline achieves equal authorized utility, timing, recovery, and operator cost with fewer persistent states.", state: "testing", href: "/research/calibrated-non-action", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:host-general-goal", kind: "question", slug: "host-general-repository-goal", projectSlug: "host",
    title: "Can Host complete a general repository Goal without absorbing Runtime mechanics?",
    summary: "Test semantic continuity on real engineering work while preserving the Host–Runtime boundary.",
    importance: "Host only matters if semantic continuity survives real work; a demo loop that cannot cross restart, model replacement, and ambiguous effects does not establish a state owner.",
    hypothesis: "Host can own Goal, Task, candidate admission, Harness assignment, verification, and Outcome while Runtime exclusively owns Workspaces, Jobs, process trees, and physical evidence.",
    currentJudgment: "Strongly supported but still bounded. H2–H6 established continuation; Harness H1–H5 completed a frozen repository-repair workload in both Codex/Hermes replacement orders, rejected stale and missing-Artifact completion claims, recovered a dropped repair response without redispatch, and committed TaskOutcome only after independent Runtime acceptance. A broader unbounded repository Goal remains outstanding.",
    nextStep: "Run one broader multi-step repository Goal with open-ended decomposition across Host restart and later Harness replacement while preserving admitted decisions, unknown-effect handling, and acceptance evidence.",
    falsifier: "If Host must copy process, Workspace, or Artifact truth to continue correctly—or loses semantic commitments when those objects remain in Runtime—the boundary is wrong.", state: "testing", href: "/research/host-general-repository-goal", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:host-operational-surface", kind: "question", slug: "host-operational-surface", projectSlug: "host",
    title: "What operational surface is required before Host becomes installable rather than architectural proof?",
    summary: "Identify the minimum inspect, service, backup, and recovery surface earned by real use.",
    importance: "A correct state model that cannot be inspected, restarted, backed up, or recovered remains a laboratory artifact rather than a dependable Host.",
    hypothesis: "A small inspect surface, service lifecycle, append-only journal backup, and explicit recovery report will be sufficient; a general operations platform is unnecessary.",
    currentJudgment: "Open. The journal, recovery model, operator handoff, and Harness receipts exist, but long-lived installation and operator recovery have not yet established the minimum public surface.",
    nextStep: "Run Host as a persistent service through routine restart, backup, restore, and one deliberately interrupted Task.",
    falsifier: "If the current journal plus ordinary service tooling already makes every required state observable and recoverable, do not add a separate operations layer.", state: "open", href: "/research/host-operational-surface", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:host-harness-composition", kind: "question", slug: "harness-composition-and-completion", projectSlug: "host",
    title: "Which Harness objects survive live provider replacement without duplicating Host or Runtime state?",
    summary: "Prove or delete a Host-local Harness boundary across provider-faithful lifecycles, replacement, faults, and completion adjudication.",
    importance: "A shared Harness abstraction can erase useful provider capabilities or create a second Task and Session system. Direct drivers can also duplicate assignment, evidence, fencing, and completion logic unless the stable overlap is measured.",
    hypothesis: "Host-local Assignment, HarnessRunReceipt, CompletionProposal, capability manifest, generation fencing, and completion adjudication will survive Codex App Server and Hermes ACP, while provider Thread and Session identities remain local evidence.",
    currentJudgment: "Answered by H1–H5. Both replacement orders completed through one Task Attempt and fresh Assignment generation; stale completion, missing Artifact, and response loss were handled correctly. Provider final text was not portable evidence, and Codex/Hermes lifecycles remained materially different. The durable Host boundary survived; a shared internal Provider lifecycle did not.",
    nextStep: "Keep the shared mature-Provider lifecycle closed. Reopen only if a second independent consumer proves stable shared semantics and measurable net deletion without Provider capability loss. Use the separate Ordivon Harness v0 question for bare model APIs.",
    falsifier: "Direct provider drivers plus ordinary Host Task state remain simpler and equally correct, or a shared interface destroys material provider capability or adds more lifecycle code than it removes.", state: "answered", href: "/research/harness-composition-and-completion", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:ordivon-harness-v0", kind: "question", slug: "ordivon-harness-v0", projectSlug: "host",
    title: "What is the smallest Ordivon Harness that turns a bare model API into a verifiable Agent Run?",
    summary: "Build one thin first-party model/Tool Loop without copying Host Task truth, Runtime process truth, or mature Provider Harness lifecycles.",
    importance: "Without a first-party Loop, Ordivon can only use complete external Agent products or one-shot model judgment. Bare APIs, local models, controlled Loop research, and strategic fallback capability remain inaccessible.",
    hypothesis: "A Host-local v0 with one Model Adapter, sequential Tool Loop, Assignment-scoped catalog, Runtime bridge, bounded Run state, interruption, and existing Run receipts can solve one real multi-turn workload while remaining materially smaller than mature Provider drivers.",
    currentJudgment: "Ready for construction at M2. The complete model-to-work stack, H1–H5 ownership boundary, first falsifier, comparison baselines, acceptance, non-goals, and deletion condition are frozen. No implementation evidence exists yet.",
    nextStep: "Compare one frozen repository workload under one-shot ModelGateway, Ordivon Harness with a bare model API, and one mature Provider Harness; retain the prototype only if it solves a real failure or enables a real model path at acceptable permanent cost.",
    falsifier: "One-shot or mature Provider Harness paths match correctness, recovery, portability, and cost while no bare-model use case requires the first-party Loop.", state: "open", href: "/research/ordivon-harness-v0", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:runtime-structured-effect", kind: "question", slug: "runtime-structured-effect", projectSlug: "runtime",
    title: "Which real structured operation can complete the minimal Effect contract across a second backend?",
    summary: "Find one operation that proves stable identity, explicit uncertainty, correlation, reconciliation, and no blind redispatch beyond local process execution.",
    importance: "Round 1 weakened the larger Effect model on a single backend. A shared contract is not earned until a structurally different external path needs more than mature provider idempotency, durable Activities, and Runtime terminal evidence.",
    hypothesis: "The surviving cross-backend core is stable intended identity, explicit UNKNOWN, backend correlation, reconciliation, and a prohibition on blind redispatch; authority, path, and provider receipts remain World-owned when they condition the external effect.",
    currentJudgment: "Testing after contraction. Runtime dogfood supports commitment as the local abstraction, while Round 1 showed no advantage for a larger single-backend Effect graph. Host H2/R2 also completed real correlation and recovery through existing Runtime request identity and opaque references without expanding Runtime.",
    nextStep: "Use World W1 as the second backend and compare direct provider integration against the minimum Effect fields under response loss, path change, reconciliation, and continuation.",
    falsifier: "Stable provider request identity, native receipts, durable Activities, and direct Host integration preserve the same ambiguity and recovery with less permanent machinery.", state: "testing", href: "/research/runtime-structured-effect", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:runtime-boundary-friction", kind: "question", slug: "runtime-boundary-friction", projectSlug: "runtime",
    title: "Which remaining friction belongs above Runtime rather than becoming another primitive?",
    summary: "Prevent workflow and Harness convenience from expanding the trusted execution kernel.",
    importance: "Every convenience promoted into Runtime becomes a durable compatibility and recovery obligation inside the trusted effect boundary.",
    hypothesis: "A new Runtime primitive is justified only when a physical fact cannot be reconstructed after interruption; workflow, Task, Harness, and provider convenience belongs in Host, adapters, or World.",
    currentJudgment: "Strongly supported. Repeated dogfood earned request lookup, progress, repair, lifecycle retention, and receipts. Harness H2/R2 then proved Assignment and Harness Run correlation, exact replay, fresh-client recovery, and terminal evidence using four opaque foreign references with zero new Runtime semantic objects.",
    nextStep: "Apply the unreconstructable-physical-fact test to each new friction reported by Host, Game, World, and future workloads before adding any primitive.",
    falsifier: "A repeated failure cannot be recovered, correlated, or explained without a new durable Runtime-owned physical fact.", state: "open", href: "/research/runtime-boundary-friction", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:world-correlated-recovery", kind: "question", slug: "world-correlated-recovery", projectSlug: "world",
    title: "Can one Host Task combine path evidence and provider execution, reconcile a lost response, and continue without duplicate work?",
    summary: "Test whether path and external action evidence can support one recoverable Task trajectory.",
    importance: "A retry after response loss can duplicate an external effect unless delivery conditions, provider execution, authority, and receipts can be correlated before the next action.",
    hypothesis: "One World Interaction identity can bind target, path, identity, authority, provider request, receipt, and conditioned observation without replacing mature transports or provider APIs.",
    currentJudgment: "Testing. Link and Edge are now retired as separate projects and their useful planes are preserved inside World, but no end-to-end lost-response trajectory has yet reconciled a real provider action across a path change.",
    nextStep: "Run World W1: perform one provider mutation, lose the response deliberately, change the usable path, reconcile by evidence, and continue the original Task without duplicate work.",
    falsifier: "Provider idempotency and existing transport receipts compose directly in Host with equal recoverability and less state.", state: "testing", href: "/research/world-correlated-recovery", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:world-boundary-value", kind: "question", slug: "world-boundary-value", projectSlug: "world",
    title: "Does a thin World boundary prevent a real failure better than direct Host integration?",
    summary: "The project boundary must prove a concrete continuity gain before it expands.",
    importance: "World should not exist merely because networking and provider APIs are complicated; it must prevent a continuity failure that direct integration cannot handle cleanly.",
    hypothesis: "World earns its boundary only where path-conditioned delivery and external effect reconciliation must remain one recoverable interaction.",
    currentJudgment: "Supported as a corrected research boundary but still experimentally open. Link and Edge unification removed the wrong repository split; World W1 must now prove that correlated recovery creates more value than direct Host integration.",
    nextStep: "Implement the smallest correlated World Interaction and compare its failure recovery against a direct Host-to-provider path.",
    falsifier: "Direct Host integration remains simpler while preserving the same evidence, ambiguity, rebinding, and no-duplicate guarantees.", state: "open", href: "/research/world-boundary-value", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:web-research-interface", kind: "question", slug: "web-research-interface", projectSlug: "web",
    title: "Can the public site expose changing research judgment without becoming a second fact system?",
    summary: "Test whether an article-centered index of Projects and active Questions improves understanding without duplicating repository truth.",
    importance: "A static project directory hides why boundaries changed and what remains unresolved, but a complete public knowledge graph creates another mutable registry that can drift from articles and repositories.",
    hypothesis: "Stable Project ownership, durable Question dossiers, dated Articles, and a few curated architecture views can expose changing judgment while detailed evidence remains in publications and owning repositories.",
    currentJudgment: "Answered after contraction. The full Experiment/Finding/Decision/Event graph and explicit relation registry were removed. Project, Question, and Article metadata now drive Research, Writing, Current, article context, and curated System views with substantially less duplicate state.",
    nextStep: "Use the article-centered interface during real publication work and observe whether Question dossiers, topic browsing, and source links reduce explanation cost for first-time and returning readers.",
    falsifier: "If Project, Question, and Article metadata cannot support navigation without repeated manual exceptions, add only the narrow missing relation—not a general public graph.", state: "testing", href: "/research/web-research-interface", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:game-agent-native-mechanics", kind: "question", slug: "game-agent-native-mechanics", projectSlug: "game",
    title: "Which game structures become possible only when Agents persist and act through the same Host?",
    summary: "Separate genuinely Agent-native mechanics from classical systems with an LLM attached.",
    importance: "Without a falsifiable distinction, Agent-native game design collapses into ordinary scripted games with probabilistic dialogue attached.",
    hypothesis: "Persistent Agents sharing Task continuity can sustain actor-local knowledge, typed communication, authority, replaceable cognition, and recoverable commitments that fixed NPC state machines cannot express economically.",
    currentJudgment: "Testing with a released application. Station Zero now demonstrates persistent specialists, partial observations, communication whose reachability changes outcomes, player authority, provider replacement, replay, diagnosis, and exact run comparison. It still does not prove that these mechanics outperform a strong classical implementation or equal-budget single Agent.",
    nextStep: "Run the planned equal-budget single-Agent/multi-Agent ablation and implement one strong deterministic scripted baseline for the same mechanic and player information surface.",
    falsifier: "The same mechanic and player experience can be reproduced with a conventional state machine or single Agent without losing essential behavior or causing disproportionate authoring cost.", state: "testing", href: "/research/game-agent-native-mechanics", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:security-adversarial-trajectory", kind: "question", slug: "security-adversarial-trajectory", projectSlug: "security",
    title: "Can strategic adversarial trajectories be evaluated without collapsing them into one reward or success flag?",
    summary: "Model adaptive opposition through separate World truth, actor observation, decisions, effects, and multidimensional outcomes.",
    importance: "An adaptive subject can change policy, timing, explanation, and observable behavior. One action success or reward can hide deception, exposure, resource loss, mission damage, or strategic failure.",
    hypothesis: "A thin experiment layer with exact identities, observation/truth separation, digest-bound traces, dynamic opponents, and independent tactical, operational, strategic, information, organization, evaluator, and cost outcomes is sufficient to test candidate Agent-native distinctions before promoting shared architecture.",
    currentJudgment: "Testing with executable evidence. Round 1 completed 84 Trials and showed that tactical success can be strategically harmful, CAGE reward and foothold spread can conflict, richer model interpretation need not improve action, and organization can isolate compromised advice without creating new capability. The method survived; no Campaign engine or strategic ontology was promoted.",
    nextStep: "Run the next bounded experiment across multiple seeds, held-out opponent policies, compiled opponent state, and deliberate Host Session disruption while retaining multidimensional evidence.",
    falsifier: "Classical authorization, simulation, ordinary Goal/Task state, source-native metrics, and reactive policies explain the same failures and comparisons with fewer Security-specific objects.", state: "testing", href: "/research/security-adversarial-trajectory", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:security-opponent-state-transfer", kind: "question", slug: "opponent-state-transfer", projectSlug: "security",
    title: "Does compiled opponent state retain value across seeds, held-out policies, Context loss, and Harness replacement?",
    summary: "Distinguish durable strategic information from fixture-specific explanation and provider-specific reasoning style.",
    importance: "Round 1 improved local switch recognition and preserved richer hypotheses, but all retained model Trials failed the objective. Without transfer, opponent state is descriptive overhead rather than durable capability.",
    hypothesis: "Explicit opponent hypotheses and revisions will improve held-out switch recognition, resource timing, and objective completion when transcript Context is truncated or the Harness is replaced, provided the state is compiled from verified observations rather than model narrative alone.",
    currentJudgment: "Open after mixed Round 1 evidence. The local opponent-aware actor improved diagnosis and objective rate, one Codex strategic Trial recognized a switch, Hermes outcomes were unchanged, and no model Trial completed the genuine objective. No causal or transferable advantage is established.",
    nextStep: "Compare transcript-only and compiled-state conditions across multiple seeds, held-out opponent policies, bounded Context loss, and both Codex and Hermes Harness replacement.",
    falsifier: "A reactive policy or transcript-only Agent matches held-out objective, information, timing, and recovery outcomes with lower state and maintenance cost.", state: "testing", href: "/research/opponent-state-transfer", updatedAt: portfolioUpdatedAt,
  },
];

export function getArchitectureRoleById(id: string) { return architectureRoles.find((item) => item.id === id); }
export function getArchitectureRoleBySlug(slug: string) { return architectureRoles.find((item) => item.slug === slug); }
export function getBoundaryById(id: string) { return boundaries.find((item) => item.id === id); }
export function getResearchPlaneById(id: string) { return researchPlanes.find((item) => item.id === id); }
export function getProjectById(id: string) { return projects.find((item) => item.id === id); }
export function getProjectBySlug(slug: string) { return projects.find((item) => item.slug === slug); }
export function getQuestionById(id: string) { return questions.find((item) => item.id === id); }
export function getQuestionBySlug(slug: string) { return questions.find((item) => item.slug === slug); }
export function getProjectForQuestion(questionId: string) { const question = getQuestionById(questionId); return question ? getProjectBySlug(question.projectSlug) : undefined; }
