import type { BoundaryDefinition, ProjectDefinition, QuestionDefinition, ResearchPlaneDefinition } from "@/lib/model/types";
import { harnessBoundary, harnessProject } from "./projects/generated-harness.ts";
import { securityProject } from "./projects/generated-security.ts";
import { gameProject } from "./projects/generated-game.ts";

export const siteUpdatedAt = "2026-08-22";
const portfolioUpdatedAt = "2026-08-12";

export const researchPlanes: ResearchPlaneDefinition[] = [
  {
    id: "system:computing", kind: "research-plane", slug: "computing", index: "R", title: "Computing", status: "active",
    summary: "The research, specification, and conformance root that tests which shared contracts deserve to survive.",
    thesis: "Keep only responsibilities that remain unowned after comparison with mature systems and materially different workloads.",
    question: "Which facts and contracts must remain stable when models, Hosts, Harnesses, tools, and execution backends change?",
    owns: ["Shared theory", "Research portfolio", "Promoted protocol", "Conformance evidence"],
    boundary: ["No production Tasks", "No physical Jobs", "No product maturity claims"],
    href: "/projects/computing", updatedAt: portfolioUpdatedAt,
  },
];

export const boundaries: BoundaryDefinition[] = [
  {
    id: "system:host", kind: "boundary", slug: "host", index: "01", title: "Host", maturity: "tested",
    summary: "The durable semantic Task-continuity boundary: exact Task identity/revision, Host Journal/CAS admission, WorkingCheckpoint handoff, and bounded Host-local integrity across replaceable Agent sessions.",
    thesis: "Replace the cognition or process without replacing the admitted semantic work claim—and without copying foreign owner truth into Host.",
    question: "Which bounded semantic work claims must survive session replacement, and which Runtime, Git, Provider, or domain facts must instead be revalidated with their native owners?",
    owns: ["Task identity and revisioned projection", "Host Journal/CAS admission", "WorkingCheckpoint external continuity", "Opaque extension durability", "Host-local integrity, inspection, and deployment receipts"],
    boundary: ["No universal coordinator or scheduler", "No model–Tool/cognition execution", "No Runtime proxy or source mutation", "No foreign currentness or domain-world truth"],
    href: "/projects/host", updatedAt: "2026-08-18",
  },
  harnessBoundary,
  {
    id: "system:runtime", kind: "boundary", slug: "runtime", index: "03", title: "Runtime", maturity: "tested",
    summary: "The physical execution boundary that owns durable local operation identity, process state, retained evidence, cancellation, and reconciliation.",
    thesis: "Commit one admitted operation to local reality without losing what happened.",
    question: "Which physical execution facts cannot safely be reconstructed after interruption?",
    owns: ["Workspaces", "Jobs and Runtime Attempts", "Process trees", "Artifacts and physical recovery"],
    boundary: ["No Task semantics", "No Provider policy", "No semantic completion"],
    href: "/projects/runtime", updatedAt: "2026-08-20",
  },
];

export const architectureRoles = [...researchPlanes, ...boundaries];

export const projects: ProjectDefinition[] = [
  {
    id: "project:host", kind: "project", slug: "host", title: "Ordivon Host", lifecycle: "active", group: "Core work system",
    label: "Durable semantic Task continuity", category: "core-system", availability: "prototype", architectureRoleId: "system:host", publicPage: true,
    problem: "A long piece of work can outlive the model session, process, Workspace, or external state that originally carried it. A future Agent needs the exact semantic frontier and uncertainty without inheriting stale Runtime, Git, Provider, or domain facts as copied truth.",
    capability: "Provides schema-v5 Host Journal/CAS authority, revision-fenced TaskProjection state, external-continuity WorkingCheckpoints with exact response-loss replay, bounded handoff/inspection, opaque extension-state durability, Doctor/backup/restore/deployment receipts, and a deliberately small six-Tool MCP surface for adopt, checkpoint, resume, list, observe, and Host status.",
    maturity: "Operational owner-trusted local engineering component; pre-1.0 public interface", audience: "Builders and Agent workflows that need semantic work to survive conversation/session replacement without adopting a workflow platform, central coordinator, Runtime proxy, or generic cognition host.",
    latestProof: "The 0.3 contraction removed unconsumed Goal coordination, foreign execution, legacy execution workloads, generic capability policy, and Runtime-integration residue. Current 0.4.x then makes external semantic continuity first-class: one WorkingCheckpoint can survive client replacement with revision-coherent resume and exact response-loss replay, while every Runtime/Git/domain hint remains explicitly subject to owner-native revalidation.", flagshipSlug: "host-task-continuity",
    summary: "The durable semantic work-continuity component for Ordivon. Host preserves what work is being continued and what was last claimed, while cognition, physical execution, source currentness, external occurrence, and domain acceptance stay with their own owners.",
    state: "Operational with schema-v5 Journal/CAS and exactly six public MCP Tools. Host is intentionally narrower than its historical designs: it is not a universal coordination ontology, scheduler, executor, Runtime client, source engine, cognition host, or cross-owner truth service.",
    evidence: [{ value: "6", label: "public Host MCP Tools" }, { value: "v5", label: "current Journal schema" }, { value: "0", label: "Runtime proxy / generic coordinator roles" }],
    repository: "https://github.com/zycxfyh/ordivon-host", href: "/projects/host", updatedAt: "2026-08-18",
  },
  harnessProject,
  {
    id: "project:runtime", kind: "project", slug: "runtime", title: "Ordivon Runtime", lifecycle: "active", group: "Core work system",
    label: "Exact physical execution and recovery", category: "core-system", availability: "operational", architectureRoleId: "system:runtime", publicPage: true,
    problem: "A command can be admitted, partially execute, lose its response, time out, restart, cross execution targets, or outlive/release its Workspace while a later Agent still needs exact physical evidence about what happened and what remains current.",
    capability: "Owns exact Workspaces, durable Jobs and Attempts, immutable-input execution on local Linux and configured limited Windows targets, provider/source commitments, digest-bound image observation, request/target affordance discovery, Windows-native Job Object execution, cancellation, restart recovery, bounded Artifacts, exact replay, reclamation, and reconciliation of uncertain local commits.",
    maturity: "Operational owner-trusted local infrastructure; public interface remains pre-1.0 and Windows-native is experimental opt-in", audience: "Builders who need Agent actions, source commitments, physical effects, retained evidence, and lifecycle transitions to remain identifiable and recoverable without turning the executor into Task or domain authority.",
    latestProof: "The C1–C10 operational-realization programme saturated its current evidence horizon without reopening Runtime Foundations: currentness, consequential retry, evidence scope, identity/lineage, authority/binding, lifecycle retention, and reclamation remained separable. Current production also exposes workspace.content for digest-bound pixel observation, runtime.describe for capability/ceiling discovery, and workspace.execBound on Linux plus configured limited windows_native targets; the latest fixes preserve fresh remote source currentness, reclaim lifecycle contracts, and terminal observation time instead of guessing after the fact.",
    summary: "The physical authority for admitted local execution. Runtime proves what the machine executed, retained, observed, reclaimed, and can safely replay; it does not decide what that execution means for the Task, Provider, or external domain.",
    state: "Operational for owner-trusted Linux engineering work with an experimental configured Windows-native backend. Exact execution, immutable inputs, observation, cancellation, recovery, lifecycle/reclamation, and bounded evidence are current capabilities. Hostile multi-tenant isolation, arbitrary external-effect truth, and semantic Task completion remain outside Runtime.",
    evidence: [{ value: "C1–C10", label: "operational-realization programme saturated" }, { value: "2 targets", label: "verified immutable-input execution" }, { value: "pre-1.0", label: "explicit public compatibility boundary" }],
    repository: "https://github.com/zycxfyh/ordivon-runtime", href: "/projects/runtime", updatedAt: "2026-08-20",
  },
  gameProject,
  {
    id: "project:world", kind: "project", slug: "world", title: "Ordivon World", lifecycle: "active", group: "Applications and capability",
    label: "Cross-owner relationships to external reality", category: "application", availability: "operational", publicPage: true, index: "05",
    thesis: "Keep native truth with native owners; retain only the cross-owner relationship whose loss makes external observation, transfer, or consequence unsafe to reconstruct.",
    question: "Which facts about an Agent's relationship to external reality cannot be owned cleanly by the Provider, Host, Runtime, Workstation, or domain on either side?",
    owns: ["Provider request/consequence binding and UNKNOWN reconciliation", "Resource Transfer, Message Delivery, and Entity Migration trajectory identity", "Narrow provider/World temporal provenance", "Bounded read-only inspection of retained World commitments"],
    boundary: ["No global external-truth or Presence database", "No universal provider/capability router", "No duplicated Runtime, network, provider, or domain ownership", "Delivery, historical receipt, and structural provenance do not become cognition, currentness, or trust"],
    problem: "An Agent can interact with several external owners while responses are delayed, capabilities expire, execution targets change, trajectories cross domains, or consequences become uncertain; neither endpoint alone always preserves the exact relationship needed for safe reconciliation after interruption.",
    capability: "Provides an owner-preserving Bind→Observe/Act→Reconcile adapter shape plus production Resource Transfer, Message Delivery, and Entity Migration contracts, separate provider/World observation times, WorldTaskInspector for retained commitments, and owner-native doctor aggregation while providers, Host, Runtime, network operators, and domains keep their own truth.",
    maturity: "Operational 0.4 owner-preserving adapter/trajectory boundary after high-pressure contraction", audience: "Builders and researchers working on external Agent effects, cross-domain transfer, temporal evidence, and response-loss recovery where one side's native truth is not enough to reconstruct the relationship safely.",
    latestProof: "The 2026-08-18 WDF4 Causal Reality, WDF5 Property Evaluation, and TSAF0 Temporal Structure reconciliation admitted no new Causal, Measurement, or Temporal subsystem: current World already separates owner-native occurrence/admission from causal truth, bundle/observation integrity from measurement validity, and provider execution time from World availability and Host admission. Those results were consumed into the existing 0.4 production boundary rather than expanding it.", flagshipSlug: "world-got-smaller-and-got-clearer",
    summary: "The narrow relationship layer between independently authoritative systems. World preserves exact cross-owner consequence and trajectory identity, retained uncertainty, and evidence mapping without becoming the owner of external reality, current Presence, provider state, or domain meaning.",
    state: "World 0.4 currently supports provider effect binding/reconciliation plus Resource, Message, and Entity trajectories and bounded WorldTaskInspector projection. Historical research remains retrievable but deleted shared layers do not reactivate by recency; new abstractions require a named current workload that direct Host + owner/provider composition cannot represent cleanly.",
    evidence: [{ value: "0.4.0", label: "current package line" }, { value: "3", label: "production cross-World trajectory families" }, { value: "0", label: "new Causal / Measurement / Temporal subsystems from latest reconciliation" }],
    repository: "https://github.com/zycxfyh/ordivon-world", href: "/projects/world", updatedAt: "2026-08-18",
  },
  {
    id: "project:finance", kind: "project", slug: "finance", title: "Ordivon Finance", lifecycle: "active", group: "Applications and capability",
    label: "Agent-first capital system and finance research", category: "application", availability: "prototype", publicPage: true, index: "06",
    thesis: "Let the Primary Agent manage owner-delegated capital while Finance keeps observation, research, decision, execution, reconciliation, performance, and owner authority as distinct semantic boundaries.",
    question: "Can an Agent manage real capital end to end without confusing evidence, valuation basis, current portfolio state, a decision, execution authority, and an externally reconciled financial consequence?",
    owns: ["Finance-domain state and Finance Foundations", "Owner Constitution, objectives, and delegated capital scope", "Portfolio, capital-rationality, thesis, Decision, and Proposal semantics", "Financial effect identity, admission, reconciliation, attribution, and performance", "Quantitative and Agent research evidence"],
    boundary: ["External financial submission remains independently disabled until its physical deployment profile is admitted", "No universal quant DSL or generic confidence-to-authority shortcut", "Runtime owns physical execution and providers own venue-native occurrence truth", "A coherent historical Decision cannot mutate current capital after its portfolio-state baseline becomes stale"],
    problem: "A capital system crosses several authorities at once: market evidence can become stale, valuation bases can be incomparable, a model can prefer an action without authorizing it, and a dispatched order can remain economically unresolved. Finance must preserve those distinctions while still allowing the Primary Agent to make owner-native capital judgments.",
    capability: "Provides Finance Foundations v1, an Owner Constitution, point-in-time and aggregate multi-venue portfolio evidence, FinancialResource and exposure semantics, exact held-state/valuation-time separation, CapitalStateView and replayable exposure graphs, owner-capital research context, capital-rationality and Decision/Proposal machinery, a process-separated quantitative research lab, exact effect/reconciliation contracts, and Agent Context v21 / Primary Agent Surface v14 with seven semantic operations.",
    maturity: "Implemented Agent-first capital system with real-capital observation, decision, effect, reconciliation, and performance semantics; live external submission remains disabled", audience: "Researchers and builders working on Agent capital systems that need owner-native judgment, explicit evidence/currentness, causal accounting, quantitative falsification, and fail-closed external-effect boundaries.",
    latestProof: "The current capital-state path now aggregates portfolio observations fail-closed across component scopes, preserves balance FinancialResources even when risky positions are zero, separates held state from valuation time, records replayable carrier/exposure mappings, and bridges the exact managed-capital scope into owner contribution. Nonzero managed FinancialResources explicitly forbid the historical QB5 zero-return shortcut when aligned return evidence is missing. Context v21 additionally projects current execution/reconciliation work while keeping completed historical detail canonical and replayable; the state-changing Decision baseline fence remains enforced at Proposal creation.",
    summary: "The Finance-domain owner for Agent-first capital management. It combines mature financial semantics, owner objectives, quantitative research, current-state decision discipline, and exact external-effect/reconciliation boundaries without treating a research result or model preference as capital mutation.",
    state: "Primary Agent Surface v14 exposes seven semantic operations: observe, research, decide, execute, reconcile, performance, and owner. Agent Context v21 now distinguishes current consumer-bound obligations/current execution work from replayable historical detail. Current Finance can observe and compose real capital state, form/revalidate owner-bound decisions, preserve effect identity/reconciliation, and evaluate performance on explicit bases. External financial submission remains a separate fail-closed deployment boundary.",
    evidence: [{ value: "7", label: "Primary-Agent semantic operations" }, { value: "v21 / v14", label: "current Context / Surface" }, { value: "strict capital state", label: "replayable owner-scope contribution boundary" }],
    repository: "https://github.com/zycxfyh/ordivon-finance", href: "/projects/finance", updatedAt: "2026-08-22",
  },
  {
    id: "project:computing", kind: "project", slug: "computing", title: "Ordivon Computing", lifecycle: "active", group: "Research and specification",
    label: "Cross-project research, world-model revision, and reusable knowledge", category: "research", availability: "research", architectureRoleId: "system:computing", publicPage: true,
    problem: "A fast-changing project family can keep stale abstractions, confuse repeated vocabulary with a shared invariant, rediscover mature external knowledge, or preserve research results without routing them to the owner, Knowledge, Core, implementation, or history surface that can actually use them.",
    capability: "Runs owner-preserving cross-project falsification, historical and live dogfood, world-model revision, SCD and Computational Possibility research cores, reusable Knowledge synthesis, responsibility placement/deletion tests, and selected protocol conformance. Mature external results are imported into the informed baseline rather than re-proved for Ordivon ownership.",
    maturity: "Mature cross-project synthesis, Knowledge, method, and conformance root; new research remains admission-gated", audience: "Researchers and system designers asking which distinctions survive independent domains and mature baselines, which owner should hold them, and which results should become reusable Knowledge rather than new infrastructure.",
    latestProof: "The 1760–2026 historical dogfood closed without turning historical resemblance into proof of Ordivon theory, and the current Computer contraction reduced active shared machinery to a small responsibility map. On 2026-08-22 the canonical Research Method was strengthened to preserve imported mature knowledge through novelty subtraction, expose that method at first look, adjudicate closeout destinations, and materialize the Resource Ecology result as reusable Knowledge without creating a Resource owner or calculus.", flagshipSlug: "history-did-not-prove-us-right",
    summary: "The scientific synthesis and knowledge-transformation layer for Ordivon. Computing consumes owner-native and external evidence, tests cross-project claims, preserves reusable explanations, and keeps only compact shared responsibilities that survive deletion; it is not a global current-state authority.",
    state: "Current Computing separates Research, reusable Knowledge, compact Core, owner-native Projects, and Git history. SCD and Computational Possibility remain independent semantic owners inside the repository. The contracted Computer has no obligation to keep an active research line by inertia: new shared structure must survive owner placement, mature-baseline, deletion, and materially different consumer tests.",
    evidence: [{ value: "1760–2026", label: "closed historical dogfood horizon" }, { value: "10", label: "current contracted Computer responsibilities" }, { value: "import → Knowledge", label: "source-neutral research closeout path" }],
    repository: "https://github.com/zycxfyh/ordivon-computing", href: "/projects/computing", updatedAt: "2026-08-22",
  },
  {
    id: "project:human", kind: "project", slug: "human", title: "Ordivon Human", lifecycle: "active", group: "Research and specification",
    label: "Problem-first Human research, foundations, and Human–Agent capability", category: "research", availability: "research", publicPage: true, index: "07",
    thesis: "Start from concrete human problems, import the strongest relevant external evidence, and maintain reusable Human distinctions only where they prevent category errors across materially different questions—without turning a person into one ontology, score, profile, or automated adviser.",
    question: "Which human capabilities, values, relations, institutions, biological constraints, and Human–Agent boundaries materially change a concrete decision or trajectory, and which distinctions are merely descriptive overhead?",
    owns: ["Admitted Human research questions and applied-cycle status", "Human Foundations HF0–HF23 and Deep Foundations HD0–HD9", "Economic-autonomy and Human–Agent capability research", "Human research methods, evidence limits, privacy, and ethics"],
    boundary: ["No universal Human ontology, total score, or mandatory personal schema", "No permanent personal profile, digital twin, or behavioural-surveillance platform", "No individualized medical, psychological, financial, legal, employment, education, insurance, or credit authority", "Modeling a person never grants authority over that person"],
    problem: "Human questions are easy to collapse in opposite directions: a broad taxonomy can replace the actual problem, while an applied recommendation can overclaim evidence or authority. At the same time, recurring distinctions—capability versus performance, person versus context, current state versus developmental history, individual versus institution, assisted output versus retained Human skill—should not be reinvented for every new problem.",
    capability: "Maintains a problem-first research programme with one completed economic-autonomy cycle and one active Human–Agent capability cycle, plus a reusable Human Foundations library spanning identity, experience, attention, value, regulation, development, memory, knowledge, reasoning, action, social order, normativity, strategic implementation, production/economic organization, perception, affect, persistent relations, and symbolic systems. Deep Foundations add cultural inheritance, reproduction, genetics, evolution, and organismic health/pathophysiology without forcing new peer foundations.",
    maturity: "Active problem-first research with one completed applied cycle, one active applied cycle, HF0–HF23 reusable foundations, and HD0–HD9 completed depth audits", audience: "Readers, practitioners, researchers, and Agent builders who need evidence-bounded Human models, practical decision structure, and explicit limits on what joint Human–AI performance, population evidence, or system representations can prove.",
    latestProof: "The current programme demonstrates both expansion and refusal to expand. HUMAN-AI-001 now consumes mature external evidence first and targets only Ordivon-specific transport residuals; HF0–HF23 preserve reusable distinctions across materially different Human questions; and HD9 completed the organismic health/disease/pathophysiology route while explicitly rejecting HF24 and leaving HD10/NextDeepRoute UNKNOWN rather than manufacturing the next stage.",
    summary: "The Human-domain research owner for Ordivon. Human combines concrete applied questions with a reusable, source-grounded foundations library so economic autonomy, Human–Agent capability, cognition, social organization, biology, and normativity can be studied without collapsing the person into one model or converting research into personal authority.",
    state: "HUMAN-ECON-001 remains a completed conditional reference answer; HUMAN-AI-001 is active under an external-evidence-first contraction. Human Foundations currently end at HF23 with HF24 unadmitted, and Deep Foundations end at HD9 with no preselected HD10. New work is admitted by decision-changing problems or falsifiers, not by numbering or taxonomy completion.",
    evidence: [{ value: "2", label: "admitted applied Human cycles" }, { value: "HF0–HF23", label: "reusable Human Foundations" }, { value: "HD0–HD9", label: "completed deep-foundation routes" }],
    repository: "https://github.com/zycxfyh/ordivon-human", href: "/projects/human", updatedAt: "2026-08-18",
  },
  securityProject,
  {
    id: "project:media", kind: "project", slug: "studio", title: "Ordivon Media", lifecycle: "active", group: "Applications and capability",
    label: "Structured mediation with Studio as the production capability plane", category: "application", availability: "research", publicPage: true, index: "09",
    thesis: "Preserve source truth while making realities, descriptions, states, actions, and artifacts representable, transformable, exposable, and interactable for Human and Agent observers; keep authoring/production in Studio without turning Media into a second truth authority.",
    question: "How should source-owned reality be projected, transformed, composed, exposed, and interacted with without lifting standing, hiding omission, collapsing identity/time, or turning a useful representation into new domain truth?",
    owns: ["Structured mediation and observer-relative projection semantics", "OMPC-v0 shared reference/conformance discipline", "Media Foundations MF0–MF9 and derived Media research", "Studio authoring, production, editing, rendering, packaging, and expression capability"],
    boundary: ["No ownership or silent currentization of source-domain truth", "No universal Media Engine, Runtime, SDK, serializer, or asset database", "No absorption of Web, Game, Finance, Runtime, Host, Human, World, or other owners", "No universal taste or human-response claim from Agent-observer/mechanical evidence"],
    problem: "The same underlying reality can be summarized, visualized, edited, rendered, metricized, transformed, published, or made interactive. Those operations can add observer-relative utility while also hiding omissions, changing identity, compressing time, lifting a proxy into a fact, or accidentally becoming a competing authority for the source.",
    capability: "Media now owns a technology-neutral mediation contract with SourceBinding, ObserverScope, ProjectionEnvelope, RepresentationBody, Transformation/ProvenanceTrace, and ActionExposure/Disclosure roles plus eleven tested non-lifting invariants. Studio remains the active production plane for revision-bound Claims, editable cross-medium sources, exact selected assets, rendering/QC, review preparation, and human-response calibration when a decision genuinely depends on it.",
    maturity: "Phase 1 closed: stable Media owner, frozen MF0–MF9 research substrate, OMPC-v0 conformance baseline, active Studio production plane", audience: "Agent builders, designers, writers, product/research owners, and interface systems that need faithful mediation, provenance, transformation, expression, and interaction without duplicating the source owner.",
    latestProof: "Phase 1 completed the Studio→Media owner inversion and pressure-tested OMPC on four materially different real consumers: Host projection, Studio transformation lineage, Web interaction trajectory, and Finance metric/legibility. The result retained a six-role / eleven-invariant shared reference contract while explicitly rejecting a universal Media framework, engine, runtime, SDK, serializer, validator service, or owner absorption.", flagshipSlug: "a-better-looking-result-can-still-be-noise",
    summary: "The structured-mediation owner for Ordivon. Media governs how source-owned realities become observer-facing representations, transformations, exposures, and interactions; Studio remains its authoring and production capability plane for creating and reviewing concrete artifacts.",
    state: "Media Phase 1 (M0–M4) is closed in a stable-owner, consumer-pressure-driven posture. MF0–MF9 are frozen, MF10 is unadmitted, OMPC-v0 is the shared reference/conformance baseline, and Studio remains active. New shared implementation is admitted only if multiple real consumers demonstrate duplicated mediation machinery or a concrete falsifier.",
    evidence: [{ value: "MF0–MF9", label: "frozen Media Foundations" }, { value: "4", label: "materially different OMPC consumers" }, { value: "0", label: "shared Media engine / runtime / SDK admitted" }],
    repository: "https://github.com/zycxfyh/ordivon-media", href: "/projects/studio", updatedAt: "2026-08-19",
  },
  {
    id: "project:web", kind: "project", slug: "web", title: "Ordivon Web", lifecycle: "active", group: "Publication",
    label: "Public orientation and dated interpretation", category: "publication", availability: "internal", publicPage: false,
    summary: "The public interface that explains the project family, organizes research and writing, and points back to owning repositories without copying their technical truth.",
    state: "Static publication and navigation layer; no CMS, live product database, or request-time application server.",
    evidence: [{ value: "static", label: "deployment model" }, { value: "MDX", label: "publication source" }, { value: "0", label: "live fact databases" }],
    repository: "https://github.com/zycxfyh/ordivon-web", updatedAt: siteUpdatedAt,
  },
];

export const questions: QuestionDefinition[] = [
  {
    id: "question:computing-open-interface-relative-closure", kind: "question", slug: "open-interface-relative-closure", projectSlug: "computing",
    title: "When should a finite intelligence expand its interface to Reality instead of only reasoning harder?",
    summary: "Distinguish failures of a callable action interface, representation/hypothesis language, physical affordance, installed executor capability, and artifact/grounding so repair happens at the level that is actually closed.",
    importance: "A finite Agent can fail because its current action set, representation language, physical affordances, or installed tools are insufficient—not only because its reasoning is weak. Collapsing those cases creates the wrong repair and encourages vague claims of ‘basis escape.’",
    hypothesis: "Open-interface change is best represented as a level-relative closure transition under prospectively frozen feasibility/resource bounds. Mature external witnesses already cover several distinct cases: B* expansion for finite-agent callable reachability, predicate invention for representation-space expansion, and compound-tool construction for bounded physical affordance expansion.",
    currentJudgment: "Testing under a contracted theory. External prior art falsifies the claim that action/interface expansion is absent, but it also weakens any absolute transcendence claim: callable, representational, affordance, and executor expansions can be new relative to one closure while remaining compositional inside a deeper supplied substrate. No universal basis hierarchy or generic basis-escape object is admitted.",
    nextStep: "Wait for a natural owner-level failure that satisfies an already-frozen strict burden: a real certificate/language or grounded-meta-closure case where the current closure is prospectively explicit and the repair cannot be reconstructed as ordinary composition inside the admitted substrate. Do not manufacture E1b/E2 merely because apparatus exists.",
    falsifier: "If every apparent expansion is explained by an already-available deeper composition/meta-action, or mature interface/representation methods plus owner-local repair classify the failure without a new shared relation, keep the theory contracted; conversely, a source-fenced strict missing-primitive case that survives the frozen closure burden would reopen it.",
    state: "testing", href: "/research/open-interface-relative-closure", updatedAt: "2026-08-22",
  },
  {
    id: "question:computing-smallest-core", kind: "question", slug: "smallest-agent-native-core", projectSlug: "computing",
    title: "Which Agent-native responsibilities remain after strong classical baselines?",
    summary: "Use mature workflow, retrieval, idempotency, and Provider systems to delete shared abstractions that do not own a distinct failure.",
    importance: "A proposed core becomes permanent inheritance and must survive stronger alternatives and multiple workloads.",
    hypothesis: "Task continuity belongs in Host, Agent Run semantics in Harness, physical execution truth in Runtime, and most other mechanics can remain in mature or domain-owning systems.",
    currentJudgment: "Answered within Round 1. Strong baselines reduced the proposed core; later Host and Harness extraction clarified the surviving ownership split without adding a universal Agent platform.",
    nextStep: "Use the result as an admission test for every new shared contract; reopen only when a materially different workload exposes an unowned non-bypassable responsibility.",
    falsifier: "A real workload repeatedly fails because a stable responsibility cannot remain in Host, Harness, Runtime, a mature system, or the owning domain.", state: "answered", href: "/research/smallest-agent-native-core", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:computing-async-join", kind: "question", slug: "async-waiting-and-join", projectSlug: "computing",
    title: "Which Task Runtime objects are required by asynchronous waiting and Join semantics?",
    summary: "Determine the smallest durable objects required when work waits, fans out, and later joins.",
    importance: "Without explicit waiting and Join semantics, a Host or Runtime will hide continuity inside process state, polling loops, or a workflow engine it does not own.",
    hypothesis: "A thin set of durable dependency edges, wait conditions, Join policy, and Ready Frontier state is sufficient; scheduling and workflow authoring can remain outside the core contracts.",
    currentJudgment: "Open. Round 1 showed that mature workflow engines can carry durable work mechanics, but no interrupted fan-out and fan-in workload has yet proved which semantic Join facts must remain visible above those mechanics.",
    nextStep: "Run one real Task that fans out across replaceable workers, waits through interruption, and joins without reconstructing admitted state.",
    falsifier: "If existing Task, Job, Outcome, workflow state, and typed relation objects express waiting and Join behavior without ambiguity or hidden durable facts, add nothing.", state: "open", href: "/research/async-waiting-and-join", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:computing-second-workload", kind: "question", slug: "contracts-across-a-second-workload", projectSlug: "computing",
    title: "Which responsibilities survive materially different workloads without becoming one mandatory stack?",
    summary: "Use unrelated owners and applications to distinguish genuinely recurring responsibility boundaries from repository-local packaging or a frozen Host→Harness→Runtime architecture.",
    importance: "A shared contract or subsystem that only explains the workload that produced it is documentation or local packaging, not a durable computing boundary; equally, forcing every later workload through the same package stack can manufacture false generality.",
    hypothesis: "Recurring invariants such as work continuity, consequence identity, explicit uncertainty, owner-native evidence, and replacement can transfer across domains while their lowest correct owner and implementation packaging differ.",
    currentJudgment: "Reframed and answered at the responsibility level. Game, Finance, Security, World, Web, Host, Harness, and Runtime now provide materially different consumers and deletion tests. The recurring result is not a universal Host→Harness→Runtime stack: Computing's canonical Core explicitly treats subsystem names as non-invariants and retains only responsibilities that remain unowned after mature mechanisms and owner-native composition. Cross-domain pressure has repeatedly localized, deleted, or kept different packages while preserving a smaller set of ownership/identity/currentness/recovery distinctions.",
    nextStep: "Use ‘which second materially different workload needs this invariant?’ as an admission/deletion test for each future shared proposal. Do not reopen a generic stack-transfer programme unless a named recurring responsibility cannot be placed cleanly in existing owners or mature substrate.",
    falsifier: "A future shared candidate repeatedly requires the same invariant across materially different owners and simpler owner-local/mature baselines cannot preserve it without duplicated ambiguity or unrecoverable state; that should pressure the specific responsibility, not automatically the old package stack.", state: "reframed", href: "/research/contracts-across-a-second-workload", updatedAt: "2026-08-22",
  },
  {
    id: "question:computing-calibrated-non-action", kind: "question", slug: "calibrated-non-action", projectSlug: "computing",
    title: "When should an Agent act, wait, observe, refuse, reconcile, or request a decision?",
    summary: "Treat non-action as a timed, evidence-bearing decision rather than the absence of Agent capability.",
    importance: "Acting too early can duplicate or commit the wrong Effect; waiting too long can lose a deadline, resource, or strategic option. Static approval-everywhere and model-only escalation both waste scarce attention or miss consequence boundaries.",
    hypothesis: "Host-local DecisionRequests, explicit UNKNOWN and wait states, deadlines, evidence requirements, and paired act/abstain evaluation can preserve authorized utility with fewer operator interruptions than uniform approval rules.",
    currentJudgment: "Testing with a stronger real-domain non-action case. Finance QB6 let one Agent request exact read-only evidence rather than infer missing execution facts, then update from more_research to no_op when the current minimum contract exceeded both the frozen 10% target and existing 25% canary bound; the branch ended before simulation, Decision, Proposal, or financial write.",
    nextStep: "Repeat evidence-conditioned act/abstain trajectories in materially different domains and with state changes that make a previously impossible action become expressible; retain new non-action state only if simpler owner-native evidence cannot reconstruct the same decision.",
    falsifier: "A simpler static policy or always-act baseline achieves equal authorized utility, timing, recovery, and operator cost with fewer persistent states.", state: "testing", href: "/research/calibrated-non-action", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:host-general-goal", kind: "question", slug: "host-general-repository-goal", projectSlug: "host",
    title: "What semantic work should Host preserve when broader work continues across sessions?",
    summary: "Retain durable Task identity and the bounded semantic frontier without turning Host into a Goal coordinator, executor, Runtime proxy, or domain-completion authority.",
    importance: "A continuity component can preserve useful work while still becoming harmful if it silently absorbs planning, execution, currentness, or domain truth merely because those facts are convenient to resume from.",
    hypothesis: "Host only needs Task identity/revision, Journal/CAS admission, WorkingCheckpoint continuity, bounded handoff/inspection, and opaque owner references; broader Goal coordination and external execution can remain consumer-local.",
    currentJudgment: "Reframed by the 0.3 contraction. The original ‘broader Goal completion’ target was too broad: Host deliberately removed shared Goal coordination, caller-neutral foreign execution, Runtime integration residue, generic capability policy, and legacy execution workloads. Current 0.4.x preserves the semantic work claim and revalidation hints while cognition, execution, source currentness, external occurrence, and domain completion remain owner-native.",
    nextStep: "Treat the narrowed 0.4.x continuity journey as the standing answer. Reopen shared coordination only if a named cross-session workload repeatedly loses a Host-owned semantic fact that WorkingCheckpoint plus direct owner revalidation cannot preserve.",
    falsifier: "A real workload repeatedly requires Host itself to own a stable coordination or completion fact—not merely reference it—and direct consumer/owner composition cannot recover correctly with less shared machinery.", state: "reframed", href: "/research/host-general-repository-goal", updatedAt: "2026-08-18",
  },
  {
    id: "question:host-operational-surface", kind: "question", slug: "host-operational-surface", projectSlug: "host",
    title: "What operational surface is required for durable semantic Host continuity?",
    summary: "Determine the smallest inspection, recovery, backup/restore, deployment, and MCP surface needed to operate Host without expanding it into an operations platform.",
    importance: "A correct continuity model still needs observable and recoverable product behavior, but operational convenience should not recreate deleted coordination, execution, or cross-owner truth roles.",
    hypothesis: "A small Host-local surface is sufficient when every foreign fact remains an opaque reference that its native owner revalidates.",
    currentJudgment: "Answered for the current 0.4.x product scope. Host now has schema-v5 Journal/CAS, full-history validation, Doctor, backup/restore, receipt-bound deployment/rollback, WorkingCheckpoint recovery, and exactly six public MCP Tools. Runtime health, source currentness, Provider state, and domain verification are intentionally not folded into Host operations.",
    nextStep: "Continue ordinary operation and product hardening. Reopen the research question only if a repeated Host-local failure cannot be diagnosed, recovered, or rolled back with the current bounded surface without importing foreign-owner truth.",
    falsifier: "A current Host-owned operational failure repeatedly requires one additional durable Host fact or operation that cannot be reconstructed from Journal/CAS plus the existing inspection/recovery surface.", state: "answered", href: "/research/host-operational-surface", updatedAt: "2026-08-18",
  },
  {
    id: "question:host-harness-composition", kind: "question", slug: "harness-composition-and-completion", projectSlug: "harness",
    title: "Which Harness objects survive live Provider replacement without duplicating Host or Runtime state?",
    summary: "Preserve Provider-faithful execution while retaining only shared Run facts required for recovery and completion.",
    importance: "A shared Harness can erase Provider capabilities or create another Task database; direct adapters can duplicate Run evidence and recovery.",
    hypothesis: "Assignment, Run receipt, Tool-step evidence, recovery, and completion proposal survive while Provider Sessions remain local.",
    currentJudgment: "Answered by H1–H5 and later extraction. The durable Run boundary survived Codex and Hermes replacement; a universal Provider lifecycle did not.",
    nextStep: "Keep Provider lifecycles native and pressure only the current Harness public boundary through new adapters and workloads.",
    falsifier: "Direct Provider integrations remain equally correct with less repeated code, or the shared boundary destroys material Provider capability.", state: "answered", href: "/research/harness-composition-and-completion", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:ordivon-harness-v0", kind: "question", slug: "ordivon-harness-v0", projectSlug: "harness",
    title: "Does the caller-neutral Harness boundary remain valuable across different workloads and execution strategies?",
    summary: "Pressure immutable Run contracts, delegated execution mandates, Provider and Tool recovery, and completion proposals without reintroducing caller-specific persistence or a universal planner.",
    importance: "H3 removed the Host-backed product line, so Harness retention now depends on recurring caller-neutral execution and recovery value rather than compatibility with one upstream owner.",
    hypothesis: "Mandate-to-strategy-to-Run-contract compilation plus durable Provider and Tool continuity will transfer to another materially different caller or workload with small permanent cost.",
    currentJudgment: "Testing with stronger Agent-owned discovery evidence. P4 proved the Agent could select repository observations without caller-preselected source slices but required 203 admitted observations. P5 replaced count minimization with decision value per observation: one negative control used only the repository map and abstained ignorantly, while the accepted branch consumed exact external failure evidence plus six Agent-selected source/reference investigations, reduced admitted observations to 8 (25.375× fewer), and still lawfully abstained because no causal baseline-red source defect was established. Durable exact history remained separate from the compact current Working View; no RAG, Context scheduler, generic evaluator, or mutation authority was added.",
    nextStep: "Continue testing whether Agent-owned observation selection transfers to materially different discovery workloads while preserving exact provenance, compact Working Views, and bounded abstention. Treat model-call/token efficiency as a separate pressure: P5 still used 12 Provider calls and 239,953 tokens despite the 25.375× observation reduction.",
    falsifier: "Direct Provider and Runtime integration matches the same interruption recovery, evidence, bounded authority, and completion handoff with less permanent Harness machinery.", state: "testing", href: "/research/ordivon-harness-v0", updatedAt: "2026-08-08",
  },
  {
    id: "question:runtime-structured-effect", kind: "question", slug: "runtime-structured-effect", projectSlug: "runtime",
    title: "Which repeated physical operation deserves a dedicated structured Runtime contract?",
    summary: "Require stable identity, enforceable preconditions, receipts, replay/reconciliation, and ambiguity behavior before promoting another physical Tool contract.",
    importance: "Every Runtime primitive becomes a durable compatibility and recovery obligation inside the physical boundary.",
    hypothesis: "Only repeated operations with unreconstructable Runtime-owned physical facts should become structured contracts; generic execution stays effect-opaque and external consequence stays owner-native.",
    currentJudgment: "Open, but trigger-gated rather than under active expansion. Structured Patch and a small set of Runtime-owned lifecycle operations earned dedicated contracts; the later C1–C10 operational-realization programme did not produce a generic Effect layer, external-consequence authority, cleanup service, or semantic-completion primitive.",
    nextStep: "Wait for repeated real use to expose one physical fact that generic execution plus owner-local evidence cannot preserve. Only then preregister the smallest structured contract against that simpler baseline.",
    falsifier: "Generic execution plus owner-local receipts/reconciliation continues to preserve the required result with less permanent Runtime machinery.", state: "open", href: "/research/runtime-structured-effect", updatedAt: "2026-08-20",
  },
  {
    id: "question:runtime-boundary-friction", kind: "question", slug: "runtime-boundary-friction", projectSlug: "runtime",
    title: "Which remaining friction belongs above Runtime rather than becoming another primitive?",
    summary: "Prevent semantic convenience, environment closure, external-effect policy, or cleanup pressure from expanding physical execution authority without a reproduced unreconstructable fact.",
    importance: "Every Runtime primitive becomes permanent compatibility, recovery, and release debt inside the physical authority boundary.",
    hypothesis: "Most remaining friction belongs with Harness, Host, Workstation, providers, package managers, or domain owners; Runtime should retain only irreducible physical execution, evidence, and lifecycle facts.",
    currentJudgment: "Answered for the current P0–P5, HP0, and C1–C10 evidence horizon. Storage pressure produced an owner/retention correction rather than a generic cleanup service, and later operational-realization pressure kept currentness, retry, evidence scope, identity, authority, retention, and reclamation separable without reopening Runtime Foundations.",
    nextStep: "Keep the graduated boundary closed. Reopen only on a new physical falsifier: a repeated current operation that cannot be recovered, replayed, observed, or explained without one additional Runtime-owned fact under a materially different workload or execution target.",
    falsifier: "A repeated current failure survives owner-local repair and cannot be represented with existing Workspace/Job/Attempt/process/Artifact/source/lifecycle evidence without adding a new durable Runtime fact.", state: "answered", href: "/research/runtime-boundary-friction", updatedAt: "2026-08-20",
  },
  {
    id: "question:world-correlated-recovery", kind: "question", slug: "world-correlated-recovery", projectSlug: "world",
    title: "Did a shared World Interaction improve correlated external recovery?",
    summary: "Record the negative result that direct owner-local integration carried the tested external recovery responsibilities.",
    importance: "A shared layer should exist only if it prevents a reproduced failure more cleanly than Provider-native receipts, Host state, and Runtime correlation.",
    hypothesis: "A shared World identity would be necessary to bind path and Provider execution across response loss.",
    currentJudgment: "Answered negatively. W1 and subsequent experiments did not justify a shared World authority; the active repository retains Provider-native and machine-local capabilities only.",
    nextStep: "Keep the question closed unless a new external workload reproduces an unowned failure that direct integration cannot reconcile.",
    falsifier: "A new workload repeatedly loses necessary continuity despite Provider-native receipts, Host correlation, Runtime evidence, and machine-local observation.", state: "answered", href: "/research/world-correlated-recovery", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:world-boundary-value", kind: "question", slug: "world-boundary-value", projectSlug: "world",
    title: "What remains valuable after the shared World layer is removed?",
    summary: "Separate retained operational capability from the rejected semantic project thesis.",
    importance: "Useful adapters and network tools should not reactivate a service, database, broker, or universal schema that failed its admission test.",
    hypothesis: "Cloudflare Provider operations and private network tooling can remain owner-local while shared World semantics stay deleted.",
    currentJudgment: "Answered for the current repository. Two capability families remain; the shared semantic authority is rejected and archived.",
    nextStep: "Maintain the retained capabilities against their own operational contracts; reopen shared architecture only after a reproduced cross-owner failure.",
    falsifier: "The retained capabilities require one recurring semantic fact that no Provider, Host, Runtime, network state, or caller can own directly.", state: "answered", href: "/research/world-boundary-value", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:computing-causal-explanation", kind: "question", slug: "causal-responsibility-explanation", projectSlug: "computing",
    title: "What is the smallest explanation that preserves the causal boundaries an Agent needs?",
    summary: "Compare compact owner-native causal prose with richer cards, relation vocabularies, and explicit diagnostic grammars before promoting another mandatory representation.",
    importance: "A research system can become harder to use when every useful distinction is serialized into default context, even when the richer representation adds no decision value.",
    hypothesis: "Compact causal prose is sufficient for ordinary Agent decisions when it states the relevant proof owner, semantic owner, consequence/currentness boundary, and material non-implications.",
    currentJudgment: "Answered on the EX3–EX7 Agent-facing surfaces. All treatments reached the same exact-action ceiling across 1,326 accepted decisions; richer representations added token burden, so the preregistered smallest-non-inferior rule selected compact prose.",
    nextStep: "Reopen only after a consequential failure under strong compact prose, or begin a separate human-comprehension program with human evidence rather than Agent proxies.",
    falsifier: "A harder open-ended or materially different decision surface repeatedly fails under compact causal prose while a frozen richer representation succeeds without introducing a new authority ambiguity.", state: "answered", href: "/research/causal-responsibility-explanation", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:world-minimal-boundary", kind: "question", slug: "world-minimal-boundary", projectSlug: "world",
    title: "Which World responsibilities still earn permanent ownership after deletion pressure?",
    summary: "Archive stale active-history material, delete research-only APIs, replay the same mixed failures, and retain only cross-owner reality relations whose absence recreates a current failure.",
    importance: "A broad World layer can duplicate Provider, Host, Runtime, Workstation, and domain truth while also making old research easier for an Agent to mistake for current authority.",
    hypothesis: "A narrow cross-owner relation and reconciliation boundary survives while routing, network mechanics, provider truth, and physical execution remain owner-native.",
    currentJudgment: "Answered for the current HP0–HP8 boundary. Current retrieval improved 7/9→9/9 after historical contraction, research-only ForeignEgress/EffectPath machinery was deleted, and the same 96 mixed-failure invocations passed after deletion.",
    nextStep: "Keep the boundary demand-triggered. Reopen only when a named current workload reproduces a cross-owner failure the remaining direct owners cannot preserve cleanly.",
    falsifier: "A real remote or multi-owner workload repeatedly loses necessary observation, transfer, currentness, or consequence continuity despite Provider-native evidence plus Host, Runtime, Workstation, and domain ownership.", state: "answered", href: "/research/world-minimal-boundary", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:finance-real-capital-agent", kind: "question", slug: "finance-real-capital-agent", projectSlug: "finance",
    title: "Can Agent capital judgment remain separate from financial effect authority?",
    summary: "Pressure quantitative research, proposal/decision semantics, signer and credential authority, one-shot dispatch, and venue reconciliation without turning a backtest or model conclusion into permission to trade.",
    importance: "Real-capital systems fail dangerously when predictive evidence, semantic judgment, API permission, dispatch identity, and final venue consequence are treated as the same state.",
    hypothesis: "Agent judgment can remain flexible while deterministic Finance/Executor machinery owns exact effect identity, admission, dispatch evidence, and reconciliation under explicit deployment assurance.",
    currentJudgment: "Testing at a later boundary than the original QB experiments. Finance now preserves real FinancialResources independently of current risky positions, aggregates component portfolio state with explicit FX/temporal evidence, binds owner-managed capital through replayable CapitalState/Exposure context, and blocks both stale state-changing Decisions and unsupported owner-contribution shortcuts. Context v21 routes only work pulled by current Finance consumers into authoritative obligations while external financial submission remains independently fail-closed.",
    nextStep: "Use the current owner-capital and consumer-bound context to evaluate real opportunities without relabeling missing return/history evidence as zero risk or positive contribution. Keep external submission separate until its selected deployment profile, current credentials/signer, one-shot dispatch, and reconciliation prerequisites are explicitly admitted.",
    falsifier: "A simpler owner-native venue integration preserves the same effect identity, one-shot dispatch, evidence, and reconciliation with less permanent Finance machinery, or the Agent/effect boundary fails under a bounded canary.", state: "testing", href: "/research/finance-real-capital-agent", updatedAt: "2026-08-22",
  },
  {
    id: "question:studio-creative-validity", kind: "question", slug: "creative-empirical-validity", projectSlug: "studio",
    title: "How do we know a creative improvement is not just a searched winner or model preference?",
    summary: "Separate richer perception, evidence-grounded meaning, real encounter, typed consequence, search history, and independent holdout before promoting a creative prior.",
    importance: "Agent-scale generation makes false winners cheap: a system can search until one variant looks exceptional and then mistake selection noise or one observer class for creative truth.",
    hypothesis: "Exact artifact identity, search-aware evidence, realized encounter, grounded consequence, and independent OOS support can support bounded creative learning without a universal reward model.",
    currentJudgment: "Testing after R4–R6. Rich perception earned medium-local equipment, grounding proved more stable than fine labels, and R6 showed a 5,000-candidate zero-effect search could manufacture an impressive winner that failed stronger evidence. One reveal-order effect replicated directionally on pristine content for one Agent-observer class.",
    nextStep: "Change observer class/provider and repeat frozen interventions across new artifact worlds. Introduce human evidence only when making a human comprehension, preference, trust, memory, or behavior claim.",
    falsifier: "A simpler production/evaluation loop reaches the same grounded and OOS conclusions without preserving search history or encounter identity, or the retained creative effect disappears consistently under independent observers and content.", state: "testing", href: "/research/creative-empirical-validity", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:computing-evidence-current-applicability", kind: "question", slug: "evidence-current-applicability", projectSlug: "computing",
    title: "When does valid evidence stop being current enough to govern a decision?",
    summary: "Separate historical validity, current applicability, and downstream commitment; revalidate the exact load-bearing dependency with its owner before a new consequence rather than using age or one global freshness service.",
    importance: "Authentic evidence can remain historically valid after the world it described changes, and an admitted judgment can itself become stale before action. Timestamp freshness, generation counters, or successful rendering can invalidate too much or prove too little.",
    hypothesis: "Currentness can usually remain claim- and owner-native: preserve exact evidence/commitment identity, name the dependency that makes the consequence admissible, and revalidate that dependency at the relevant consumer boundary while preserving UNKNOWN when current authority is unavailable.",
    currentJudgment: "Answered for the current evidence horizon. Security EC1 separated byte identity from semantic applicability; World independently separates historical occurrence from current relation/Presence; Web source-bound publication distinguishes exact owner revision from current editorial judgment and exposed stale static/test consumers; Finance further showed that an already coherent state-changing Decision loses Proposal authority when its PortfolioSnapshot baseline is no longer current. Computing Knowledge now records both HistoricalValidity != Currentness and AdmissionCurrentness != CommitmentCurrentness. These cases support owner-native revalidation and have not forced a generic Freshness, impact-graph, or automatic rebase service.",
    nextStep: "Treat owner-native dependency revalidation as the standing default. Reopen only when several independent consumers require one genuinely cross-owner currentness fact that cannot remain claim-local or be reconstructed cheaply from exact owner dependencies at the consequence boundary.",
    falsifier: "A repeated current failure spans independent owners such that local dependency fences disagree or cannot determine consequence admissibility without duplicating a stable shared currentness fact; that would justify testing the smallest cross-owner representation rather than a global freshness platform by default.", state: "answered", href: "/research/evidence-current-applicability", updatedAt: "2026-08-22",
  },
  {
    id: "question:finance-context-treatment-replication", kind: "question", slug: "context-treatment-replication", projectSlug: "finance",
    title: "When does a useful research constitution earn default Agent context?",
    summary: "Freeze context treatments before holdout reveal and require replicated marginal benefit before turning persuasive domain knowledge into mandatory prompt state.",
    importance: "A constitution can change Agent behavior, candidate selection, reasoning style, and apparent caution while still failing to improve the objective consistently across worlds.",
    hypothesis: "Domain knowledge should remain equipment, priors, baselines, and falsifiers unless an unchanged context treatment shows stable sealed benefit across materially different carriers after token and search cost are counted.",
    currentJudgment: "Answered for the current Quant Bedrock default-context claim. Constitution-only looked less bad than control on QB3b but remained negative; the unchanged treatment became materially worse than control on the second sealed QB3c carrier and used about 27.5% more Provider tokens. Mandatory injection has not earned default status.",
    nextStep: "Keep Quant Bedrock available as equipment rather than mandatory context. Reopen only with a frozen treatment that replicates benefit across additional carriers/providers without holdout-guided tuning and beats a simpler on-demand equipment path.",
    falsifier: "A frozen constitution treatment repeatedly improves sealed outcomes across independent carriers/providers at acceptable marginal cost, while equivalent on-demand retrieval or equipment does not recover the benefit.", state: "answered", href: "/research/context-treatment-replication", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:harness-provider-protocol-continuation", kind: "question", slug: "provider-protocol-continuation", projectSlug: "harness",
    title: "Which Provider-required state must survive a Tool turn without becoming Agent cognition?",
    summary: "Separate model-visible semantic history from opaque Provider continuation bytes whose authority comes from an exact prior Provider Tool result and lineage.",
    importance: "A semantic transcript can look complete while a native Provider still rejects the next request if protocol continuation is missing; copying opaque bytes into messages would blur cognition, privacy, and Provider authority.",
    hypothesis: "A small Adapter-bound continuation object can preserve Provider protocol continuity across crash/reopen while remaining hidden from Agent messages and without replaying the physical Tool effect.",
    currentJudgment: "Answered within Harness X2. A live Gemini falsifier returned 200 with the exact continuation and 400 INVALID_ARGUMENT when only the signature was stripped. A 940-byte continuation then survived crash/reopen, remained hidden from Agent messages, completed LIVE_CONTINUATION_OK, and caused zero Runtime redispatch. ProviderToolContinuation was the only new primitive earned across five pressured frontiers.",
    nextStep: "Keep the primitive Provider-neutral and small. Reopen abstraction only when another native Provider exposes a materially different continuation fact that cannot fit the same Adapter/turn/model-call authority and privacy boundary.",
    falsifier: "Official Provider stateful APIs or direct adapters preserve the same crash/reopen Tool continuation with less shared Harness machinery, or another Provider requires continuation semantics that invalidate the current authority shape.", state: "answered", href: "/research/provider-protocol-continuation", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:computing-semantic-order", kind: "question", slug: "semantic-order-and-canonicalization", projectSlug: "computing",
    title: "Does canonical evidence order make an Agent understand the evidence better?",
    summary: "Separate deterministic byte identity from semantic tractability, and falsify wire/evaluator ambiguity before attributing Agent errors to presentation order.",
    importance: "Stable sorting and maps are mechanically attractive enough to become permanent Context infrastructure even when the observed model variance actually comes from a broken Tool wire or ambiguous oracle.",
    hypothesis: "Canonicalization should be retained for owner-declared identity/replay needs but promoted as a model-facing representation only after an unambiguous prospective experiment beats raw presentation.",
    currentJudgment: "Answered for P11. Six unordered datasets collapsed 720 raw permutation digests to one stable identity, but after invalidating a truncated Tool-wire campaign and clarifying an ambiguous evaluator target, raw presentation scored 44/48 strict versus 42/48 stable list and 43/48 identity map. No semantic normalization advantage survived.",
    nextStep: "Use deterministic canonicalization only where owner semantics require stable identity. Reopen model-facing order machinery after a new unambiguous workload reproduces material order sensitivity that simpler evaluator/prompt clarification cannot remove.",
    falsifier: "Across independent clear-oracle workloads, one canonical representation repeatedly improves semantic accuracy over raw presentation and the gain survives Provider changes without erasing meaningful event order.", state: "answered", href: "/research/semantic-order-and-canonicalization", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:computing-historical-world-model", kind: "question", slug: "historical-world-model-dogfood", projectSlug: "computing",
    title: "Which Agent-era world-model laws survive historical out-of-distribution pressure?",
    summary: "Freeze the modern theory, reconstruct history before coding it, preserve failures and anti-cases, and let independent epochs narrow or contradict the candidate laws before any cross-era promotion.",
    importance: "A modern systems theory can appear universal if it chooses famous examples and retrospective labels after seeing the outcomes. Historical OOD pressure is useful only when the theory cannot move to fit the evidence.",
    hypothesis: "Materially different scientific and industrial worlds may expose recurring structural pressures, but recurrence must be separated from universal law, taxonomy quality, measurement currentness, and replay validity.",
    currentJudgment: "Answered for the HD0–HD9 programme. The frozen 1760–2026 campaign closed with 320 trajectories and 96 Deep Anchors across eight chronological waves. Cross-era recurrence survived only as a typed seven-family structural map plus explicit demotions, merges, replay negatives, and measurement/currentness results; the evidence did not justify ten universal success invariants or eight universal innovation laws.",
    nextStep: "Keep HD0–HD9 closed and use the bounded structural map as a prior, not a law factory. Reopen only when a new decision requires historical pressure that the retained map cannot answer, or when an independent anti-case materially changes the bounded standing; HD10 is not admitted by numbering inertia.",
    falsifier: "A future independent corpus or coding audit can still show that a retained family is mainly taxonomy artifact, selection bias, or historical-replay leakage; such evidence should narrow or delete that family rather than restart the programme automatically.", state: "answered", href: "/research/historical-world-model-dogfood", updatedAt: "2026-08-22",
  },
  {
    id: "question:web-research-interface", kind: "question", slug: "web-research-interface", projectSlug: "web",
    title: "Can the public site explain changing research judgment without becoming a second fact system?",
    summary: "Use a stable project map, dated publications, Feynman-style causal explanation, and exact owner links while keeping rendered encounter evidence separate from technical truth.",
    importance: "A project directory without synthesis is opaque; a copied fact graph drifts; and technically correct source can still produce a misleading reader encounter.",
    hypothesis: "Public orientation can remain authored and progressively disclosed while repositories and research records retain technical truth and Web owns only explanation, navigation, rendering, and encounter evidence.",
    currentJudgment: "Testing with a direct 2026-08-22 public-currentness audit. Source-bound Game, Harness, and Security projections exposed exact owner review obligations and were refreshed without copying their implementation databases; their current review set is now empty. Manual project judgments for Host, Runtime, World, Finance, Computing, Human, and Media required editorial re-adjudication, and fast-moving Finance drifted again within the same audit because it lacks the public-authority contract used by the source-bound owners. The audit also caught two different downstream currentness failures: a stale static `out/` artifact and smoke tests that still asserted superseded public wording. Home, Now, System, Research, and Writing were then refreshed while dirty/uncommitted owner state was deliberately excluded.",
    nextStep: "Finish bounded question-state adjudication, then run the full publication/build/budget/browser suite and compare the deployed source commit with current main. After that, test whether fresh readers can recover purpose, owner boundaries, current maturity, evidence limits, and the next useful destination. For high-change manual owners, prefer an owner-supplied public-authority envelope if and when that owner admits one; Web must not manufacture it on their behalf.",
    falsifier: "Current owner changes repeatedly become misleading public claims despite source/revision review; source-bound capture requires Web to duplicate owner semantics; fresh readers still need copied implementation detail to understand responsibility; or rendered encounter evidence repeatedly contradicts the authored orientation in ways the current review/build/browser discipline cannot catch.", state: "testing", href: "/research/web-research-interface", updatedAt: "2026-08-22",
  },
  {
    id: "question:game-direction-player-value", kind: "question", slug: "game-direction-player-value", projectSlug: "game",
    title: "Which game form deserves the next Ordivon Game product—and where do Agents add Player Value?",
    summary: "Search game form before Agent role: use cheap falsifiers and bounded playable proofs to find a form worth playing, then test whether Agent participation creates value a simpler design cannot.",
    importance: "A sophisticated Agent mechanic can be technically real and still fail to produce a game worth playing. Product direction should therefore be selected by player-facing pressure rather than by the desire to showcase an Agent architecture.",
    hypothesis: "Separating GameForm from AgentRole, rejecting weak forms cheaply, and requiring bounded playable proof plus human Player Value evidence will produce better product choices than starting from an Agent-native mechanic and designing outward from it.",
    currentJudgment: "Testing in the Pre-G0 direction-search phase. Station Zero v2 remains the only registered current product; v3, Casefile, and other treatments are references/research surfaces rather than selected product stages. R1–R29 foundation expansion is provisionally frozen. The current A/D/I playable-proof wave has mechanical/browser evidence, but C0/C1 human Player Value remains explicitly unobserved and no next product has been selected.",
    nextStep: "Put the bounded playable proofs in front of human players, compare them against simpler/non-Agent baselines where possible, and record which form produces comprehension, tension, agency, replay desire, or other preregistered Player Value before admitting a G0 product direction.",
    falsifier: "No candidate survives direct player pressure, or a simpler non-Agent/classical form reproduces the same player-facing value with lower complexity; in either case do not promote the Agent treatment into a product thesis.", state: "testing", href: "/research/game-direction-player-value", updatedAt: "2026-08-20",
  },
  {
    id: "question:game-agent-native-mechanics", kind: "question", slug: "game-agent-native-mechanics", projectSlug: "game",
    title: "Which game structures become possible only when Agents persist and act through one World history?",
    summary: "Historical Agent-first research that separated strategy existence, policy accessibility, model realization, and simpler classical substitutes before the Game programme moved to GameForm-first direction search.",
    importance: "Without a falsifiable distinction, Agent-native game design becomes a marketing label; but even a genuine distinction is insufficient if it does not create Player Value.",
    hypothesis: "Persistent roles, actor-local knowledge, typed communication, player doctrine, and recoverable commitments can create distinct mechanics, but their product value must be tested separately from their technical existence.",
    currentJudgment: "Reframed after GX1 and the later Game direction work. GX1 showed materially different reachable futures and separated strategy existence from model realization; the model still failed the frozen Core-carrier continuation while a deterministic continuous-carrier policy could succeed, and a generic structured primaryObjective prototype was deleted after presentation-order sensitivity. Those results remain valid research pressure, but the programme no longer assumes that proving an Agent-native mechanic selects the next game.",
    nextStep: "Use GX1 as a historical constraint on future Agent roles. Continue through the new GameForm/Player-Value question and reopen this narrower mechanism question only when a candidate game form survives player pressure and Agent participation becomes the decision-changing variable.",
    falsifier: "The same player experience and mechanics can be reproduced by a simpler deterministic or non-Agent system, or Agent-native differences remain technically observable but irrelevant to player-facing value.", state: "reframed", href: "/research/game-agent-native-mechanics", updatedAt: "2026-08-20",
  },
  {
    id: "question:human-economic-autonomy", kind: "question", slug: "human-economic-autonomy", projectSlug: "human",
    title: "What practical path can increase personal economic autonomy without materially reducing life quality?",
    summary: "Translate first-principles economic reasoning into a conditional, practical path with explicit trade-offs and no individualized advice claim.",
    importance: "People need usable decision structure, but universal prescriptions and personal scoring can obscure constraints, privacy, and high-consequence uncertainty.",
    hypothesis: "A staged E0–E9 path with simple cases, conditions, stopping rules, and structural review can improve practical reasoning without becoming an adviser product.",
    currentJudgment: "Answered for the first admitted cycle. HUMAN-ECON-001 produced the E0–E9 practical path and six-case review; conclusions remain conditional and do not automatically create E10.",
    nextStep: "Use and critique the completed path. Admit a new Human research cycle only when another concrete problem and boundary are explicit.",
    falsifier: "The path cannot guide decisions without individualized data, hides major quality-of-life costs, or adds complexity beyond ordinary planning tools.", state: "answered", href: "/research/human-economic-autonomy", updatedAt: portfolioUpdatedAt,
  },
  {
    id: "question:security-adversarial-trajectory", kind: "question", slug: "security-adversarial-trajectory", projectSlug: "security",
    title: "Which Agent-level adversarial distinctions survive after mature security capability is imported?",
    summary: "Separate the Security-owned semantics that remain decision-relevant after ordinary scanners, fuzzers, execution carriers, defensive mechanisms, providers, Host, Harness, and Runtime are consumed directly.",
    importance: "Agent security research can easily rebrand classical capability, or overpromote persistent Campaign/Opponent/Organization machinery merely because adaptive opposition sounds complex. The residual should survive comparison with thin deterministic policies and mature mechanisms.",
    hypothesis: "Exact Range/Scenario authority, asymmetric observation, independent truth/evidence, effect/recovery identity, and bounded evaluation remain Security-owned; the first Agent-level behavioral residual is conditional capability selection and replanning against current evidence/counterplay rather than a new tactical-state or Campaign subsystem.",
    currentJudgment: "Answered for the CA0–CA7 capability programme. CA6 showed a fixed script fail three of four held-out worlds while both a generic observation-driven deterministic adaptive policy and the canonical Harness/model Actor succeeded all four with the same oracle-regret vector; P1 reproduced the core adaptive-selection result under real provider/authority friction. The model did not establish a stronger residual than the thin adaptive policy. CA7 therefore closed by contraction: Campaign, Organization, persistent OpponentModel, coevolution, provider gateway, and cross-fidelity strategic law are not admitted by current evidence.",
    nextStep: "Use current-observation selection/replanning as a bounded standing, not a universal law. Reopen a stronger strategic abstraction only when an independent authorized consumer produces one of CA7's exact failures—cross-mission obligation, team benefit, opponent-history gain, held-out coevolution transfer, or higher-fidelity failure that ordinary trajectory/current evidence cannot explain.",
    falsifier: "Mature range/simulation authority plus ordinary Host, Harness, Runtime, provider-native evidence, and thin current-observation decision logic express the same retained distinctions with fewer Security-specific contracts, or a future higher-order consumer forces a different residual than current conditional selection/replanning.", state: "answered", href: "/research/security-adversarial-trajectory", updatedAt: "2026-08-15",
  },
  {
    id: "question:security-opponent-state-transfer", kind: "question", slug: "opponent-state-transfer", projectSlug: "security",
    title: "When does persistent opponent history earn a Security-owned OpponentModel?",
    summary: "Treat opponent state as a trigger-gated hypothesis: require held-out repeated encounters where history changes decisions beyond current observations and ordinary trajectory before adding durable strategic state.",
    importance: "A stored opponent model can preserve real strategic information, but it can also become descriptive overhead, memorization, or a second state system when current evidence already supports the same decision.",
    hypothesis: "Persistent opponent history should be admitted only if exact prior encounters causally improve held-out decisions or recovery after controlling for current observations, ordinary trajectory, context capacity, and provider/model effects.",
    currentJudgment: "Open under the CA7 negative admission gate; no positive transfer standing exists. Earlier Round 1 evidence was mixed and did not establish causal held-out advantage, while CA6 handled deliberate Blue policy change using current consequences and replanning without a stored opponent hypothesis. CA7 therefore leaves persistent OpponentModel NOT ADMITTED and records opponent-history gain as one explicit reopen condition.",
    nextStep: "Do not run a transfer programme by roadmap inertia. Reopen only when repeated authorized encounters make opponent history a natural decision input; then compare transcript/current-observation baselines against exact compiled history on held-out opponents/worlds with memorization, evaluator, and Context-loss controls.",
    falsifier: "A reactive/current-observation policy or ordinary trajectory matches held-out decision quality, timing, information use, and recovery with lower durable state and maintenance cost.", state: "open", href: "/research/opponent-state-transfer", updatedAt: "2026-08-15",
  },
];

export function getArchitectureRoleById(id: string) { return architectureRoles.find((item) => item.id === id); }
export function getArchitectureRoleBySlug(slug: string) { return architectureRoles.find((item) => item.slug === slug); }
export function getBoundaryById(id: string) { return boundaries.find((item) => item.id === id); }
export function getResearchPlaneById(id: string) { return researchPlanes.find((item) => item.id === id); }
export function getProjectById(id: string) { return projects.find((item) => item.id === id); }
export function getProjectBySlug(slug: string) { return projects.find((item) => item.slug === slug); }
export function getQuestionById(id: string) { return questions.find((item) => item.id === id); }
export function getQuestionBySlug(slug: string) { return questions.find((item) => item.slug === slug); }
export function getProjectForQuestion(questionId: string) { const question = getQuestionById(questionId); return question ? getProjectBySlug(question.projectSlug) : undefined; }
