import type { GraphEvent } from "@/lib/graph/types";

export const graphEvents = [
  {
    id: "event:security-round1-published",
    date: "2026-07-31",
    type: "publication",
    title: "Strategic failure became visible across 84 adversarial Trials",
    summary: "A canonical report now connects sixty local dynamic-opponent Trials, twenty pinned CAGE Challenge 4 Trials, four bounded model diagnostics, three metric contradictions, explicit negative results, and the next opponent-state transfer falsifier.",
    nodeIds: ["project:security", "question:security-adversarial-trajectory", "question:security-opponent-state-transfer", "experiment:security-round1", "finding:tactical-not-strategic", "finding:interpretation-not-action", "finding:organization-isolation-not-intelligence", "decision:no-custom-cyber-range", "decision:no-campaign-promotion", "article:winning-move-loses-contest"],
  },
  {
    id: "event:smaller-core-published",
    date: "2026-07-31",
    type: "publication",
    title: "Strong-baseline evidence became a canonical public argument",
    summary: "The first post-V2 flagship report now connects the frozen Round 1 workload, sixteen deterministic variants, six live Provider replacements, five architectural dispositions, explicit validity limits, and the World W1 falsifier through one graph-derived article.",
    nodeIds: ["project:computing", "question:computing-smallest-core", "experiment:core-work-system-round1", "finding:mature-workflows-carry-state", "finding:more-context-not-safer", "finding:unknown-operational-state", "finding:provider-portability-not-equivalence", "decision:no-task-runtime", "decision:no-context-kernel", "decision:shrink-effect", "article:smaller-core-strong-baselines"],
  },
  {
    id: "event:harness-h1-h3-complete",
    date: "2026-07-31",
    type: "experiment",
    title: "Harness H1–H3 established the current Host boundary",
    summary: "Host now owns Assignment fencing and completion adjudication, Runtime correlation works through opaque references without semantic expansion, and a live Codex App Server run retained provider and execution evidence while correctly leaving the Task waiting.",
    nodeIds: ["project:host", "project:runtime", "question:host-harness-composition", "experiment:harness-h1-contracts", "experiment:harness-h2-runtime-correlation", "experiment:harness-h3-codex-app", "finding:process-success-not-task-completion", "decision:no-runtime-harness-expansion"],
  },
  {
    id: "event:web-continuity-visual-thesis",
    date: "2026-07-31",
    type: "project",
    title: "Web V2 closed around one research graph and continuity thesis",
    summary: "Static delivery, fifteen Question dossiers, System and Writing projections, a continuity-led homepage, and a single dark visual system are now closed; current effort moves from interface reconstruction to research publication.",
    nodeIds: ["project:web", "question:web-research-interface", "experiment:web-governance-audit", "finding:web-governance-displaced-interface", "decision:thin-web-release"],
  },
  {
    id: "event:core-work-system-round1",
    date: "2026-07-30",
    type: "experiment",
    title: "Strong baselines reduced the proposed Agent-native core",
    summary: "Sixteen deterministic variants and six live provider-replacement Trials retained Host work meaning, Runtime execution truth, explicit UNKNOWN, and a possible World boundary while rejecting a separate Task Runtime, generalized Context Kernel, and larger single-backend Effect graph.",
    nodeIds: ["project:computing", "question:computing-smallest-core", "experiment:core-work-system-round1", "finding:mature-workflows-carry-state", "finding:unknown-operational-state", "decision:no-task-runtime", "decision:no-context-kernel", "decision:shrink-effect"],
  },
  {
    id: "event:security-round1",
    date: "2026-07-30",
    type: "experiment",
    title: "Security completed 84 bounded adversarial Trials",
    summary: "Local dynamic opponents, CAGE Challenge 4, and model-backed diagnostics separated tactical, operational, strategic, information, organization, evaluator, and cost outcomes without promoting a Campaign engine, custom range, or strategic ontology.",
    nodeIds: ["project:security", "question:security-adversarial-trajectory", "question:security-opponent-state-transfer", "experiment:security-round1", "finding:tactical-not-strategic", "finding:interpretation-not-action", "decision:no-custom-cyber-range", "decision:no-campaign-promotion"],
  },
  {
    id: "event:station-zero-alpha",
    date: "2026-07-30",
    type: "project",
    title: "Station Zero v0.1.0-alpha.1 became source-playable",
    summary: "The verified release supports a bounded mission, point-in-time replay, evidence-linked diagnosis, exact same-Case comparison, redeployment, reload recovery, and clean archive reverification without making live model providers release blockers.",
    nodeIds: ["project:game", "question:game-agent-native-mechanics", "experiment:station-zero-alpha", "finding:replay-pure-projection"],
  },
  {
    id: "event:game-authority-cutover",
    date: "2026-07-29",
    type: "decision",
    title: "Game converged on one Host authority",
    summary: "A functionally correct Python sidecar lost the measured decision gate; the embedded authority preserved exact World outcomes while deleting thirteen duplicate truth tables, two reconstruction adapters, and the duplicate execution store.",
    nodeIds: ["project:game", "question:computing-second-workload", "experiment:game-authority-cutover", "finding:one-authority-over-shared-process", "decision:embedded-game-host"],
  },
  {
    id: "event:web-writing-network",
    date: "2026-07-30",
    type: "project",
    title: "Writing became an explorable argument network",
    summary: "Article relevance, research anchors, nearest arguments, and homepage features now derive from typed document relations instead of hand-maintained related links.",
    nodeIds: ["project:web", "question:web-research-interface", "article:runtime-after-core", "article:host-task-continuity"],
  },
  {
    id: "event:web-research-dossiers",
    date: "2026-07-30",
    type: "project",
    title: "Research questions became durable public dossiers",
    summary: "Fifteen Questions now publish their hypothesis, current judgment, next admitted test, deletion condition, evidence trajectory, and connected public record.",
    nodeIds: ["project:web", "question:web-research-interface"],
  },
  {
    id: "event:web-system-explorer",
    date: "2026-07-30",
    type: "project",
    title: "System became an explorable research space",
    summary: "A typed SVG interface now exposes state ownership, execution paths, and research trajectories with node inspection and relation highlighting.",
    nodeIds: ["project:web", "question:web-research-interface"],
  },
  {
    id: "event:web-graph-kernel",
    date: "2026-07-30",
    type: "project",
    title: "Web gained a typed research graph",
    summary: "System responsibilities, repositories, questions, experiments, findings, decisions, and articles now share one validated relation source.",
    nodeIds: ["project:web", "question:web-research-interface", "decision:mdx-writing"],
  },
  {
    id: "event:web-mdx",
    date: "2026-07-30",
    type: "decision",
    title: "Writing became composable MDX",
    summary: "Six articles left JSON-embedded HTML; the first interactive architecture comparison now lives inside the article itself.",
    nodeIds: ["project:web", "decision:mdx-writing", "article:link-edge-boundary"],
  },
  {
    id: "event:web-governance",
    date: "2026-07-30",
    type: "decision",
    title: "Release governance was removed",
    summary: "Duplicate V1 trees, evidence archives, browser matrices, Lighthouse batches, and release runbooks left the active repository.",
    nodeIds: ["project:web", "finding:web-governance-displaced-interface", "decision:thin-web-release"],
  },
  {
    id: "event:world-unified",
    date: "2026-07-30",
    type: "decision",
    title: "Link and Edge became Ordivon World",
    summary: "Connectivity and provider action remain distinct planes inside one external-interaction continuity boundary.",
    nodeIds: ["project:world", "finding:link-edge-boundary-wrong", "decision:unify-world"],
  },
  {
    id: "event:runtime-dogfood",
    date: "2026-07-28",
    type: "experiment",
    title: "Runtime production use changed the kernel",
    summary: "Exact request lookup, structured progress, repair, lifecycle retention, and receipted deployment were earned through repeated work.",
    nodeIds: ["project:runtime", "experiment:runtime-production-dogfood", "finding:runtime-commitment-boundary"],
  },
  {
    id: "event:host-extracted",
    date: "2026-07-27",
    type: "decision",
    title: "Host became independent",
    summary: "Deterministic continuation and restart recovery proved that Task truth deserves an owner above sessions and processes.",
    nodeIds: ["project:host", "experiment:host-h2-h6", "decision:extract-host"],
  },
] as const satisfies readonly GraphEvent[];
