import { articleMetadata } from "@/content/articles/registry";
import type { ArticleNode, DecisionNode, ExperimentNode, FindingNode, GraphNode, ProjectNode, QuestionNode, SystemNode } from "@/lib/graph/types";

export const graphUpdatedAt = "2026-07-30";

export const systemNodes: SystemNode[] = [
  {
    id: "system:computing", kind: "system", slug: "computing", index: "01", title: "Computing", status: "active",
    summary: "The contract and conformance layer for persistent work performed with replaceable probabilistic cognition.",
    thesis: "Keep cognition, Task continuity, semantic execution, and machine execution separable.",
    question: "Which facts and contracts must remain stable when models, Hosts, tools, and execution backends change?",
    owns: ["Stack model", "Semantic contracts", "Reference systems", "Conformance"],
    boundary: ["No production Tasks", "No physical Jobs", "No implementation monorepo"],
    href: "/projects/computing", updatedAt: graphUpdatedAt,
  },
  {
    id: "system:host", kind: "system", slug: "host", index: "02", title: "Host", status: "active",
    summary: "The semantic control plane that keeps Goals and Tasks continuous above replaceable sessions and processes.",
    thesis: "Replace the model session without replacing the Task.",
    question: "Which semantic state must survive when cognition, transport, and execution processes are replaced?",
    owns: ["Goals and Tasks", "Host journal", "Cognition contexts", "Outcomes"],
    boundary: ["No process ownership", "No model monopoly", "No Runtime mechanics"],
    href: "/projects/host", updatedAt: graphUpdatedAt,
  },
  {
    id: "system:runtime", kind: "system", slug: "runtime", index: "03", title: "Runtime", status: "active",
    summary: "The physical effect boundary that owns durable local execution identity, process state, and retained evidence.",
    thesis: "Commit one Agent action to reality without losing what happened.",
    question: "Which execution facts cannot safely be reconstructed after interruption?",
    owns: ["Workspaces", "Jobs and Attempts", "Process trees", "Artifacts"],
    boundary: ["Trusted-local, not a sandbox", "No Goal ownership", "No invented exactly-once claims"],
    href: "/projects/runtime", updatedAt: graphUpdatedAt,
  },
  {
    id: "system:world", kind: "system", slug: "world", index: "04", title: "World", status: "experimental",
    summary: "The continuity boundary for paths, identities, authority, provider actions, receipts, and external uncertainty.",
    thesis: "Let a Task reach and act through a changing external world without rebuilding the world beneath it.",
    question: "What must remain continuous when connection and external action fail together?",
    owns: ["World Interaction bindings", "Conditioned observations", "External evidence", "Reconciliation and rebinding"],
    boundary: ["No universal proxy or transport", "No provider reimplementation", "No Goal, Task, or local process ownership"],
    href: "/projects/world", updatedAt: graphUpdatedAt,
  },
];

export const projectNodes: ProjectNode[] = [
  {
    id: "project:computing", kind: "project", slug: "computing", title: "Ordivon Computing", status: "active", group: "Foundations",
    label: "Contracts that survive replacement", systemNodeId: "system:computing", publicPage: true,
    summary: "The research and conformance root for persistent work performed with probabilistic models. Computing defines the contracts that other projects test rather than becoming another production runtime.",
    state: "Core semantic slices established; Host extracted as an independent state owner.",
    evidence: [{ value: "14", label: "layer map" }, { value: "H2–H6", label: "continuation gates" }, { value: "2", label: "provider paths" }],
    repository: "https://github.com/zycxfyh/ordivon-computing", href: "/projects/computing", updatedAt: graphUpdatedAt,
  },
  {
    id: "project:host", kind: "project", slug: "host", title: "Ordivon Host", status: "active", group: "Agent system",
    label: "Task continuity above sessions", systemNodeId: "system:host", publicPage: true,
    summary: "A persistent Agent control plane for Goals, Tasks, bounded cognition, candidate admission, Effect proposals, verification, and outcomes. Model sessions and Runtime processes remain replaceable dependencies.",
    state: "Independent engineering prototype after deterministic continuation and recovery proof.",
    evidence: [{ value: "1", label: "append-only journal" }, { value: "H6", label: "recovery proof" }, { value: "UNKNOWN", label: "explicit delivery state" }],
    repository: "https://github.com/zycxfyh/ordivon-host", href: "/projects/host", updatedAt: graphUpdatedAt,
  },
  {
    id: "project:runtime", kind: "project", slug: "runtime", title: "Ordivon Runtime", status: "active", group: "Agent system",
    label: "Committed local effects", systemNodeId: "system:runtime", publicPage: true,
    summary: "The deterministic boundary between an Agent decision and local machine execution. Runtime binds exact source and operation identity to durable Jobs, process trees, bounded evidence, cancellation, reconciliation, and recovery.",
    state: "Production Runtime with effect commitment, lifecycle operations, recovery, and receipted deployment.",
    evidence: [{ value: "13", label: "public tools" }, { value: "42", label: "Workspaces reclaimed" }, { value: "3.4 GB", label: "post-cleanup store" }],
    repository: "https://github.com/zycxfyh/ordivon-runtime", href: "/projects/runtime", updatedAt: graphUpdatedAt,
  },
  {
    id: "project:world", kind: "project", slug: "world", title: "Ordivon World", status: "experimental", group: "World interaction",
    label: "Conditioned external interaction", systemNodeId: "system:world", publicPage: true,
    summary: "The Task-to-external-world interaction boundary. World correlates target, path, identity, transport, provider execution, authority, Receipt, Artifact, conditioned evidence, uncertainty, reconciliation, and rebinding while mature systems retain their native mechanisms.",
    state: "Former Link and Edge histories unified; Cloudflare provider and network-observation slices preserved while the shared World Interaction boundary remains under experiment.",
    evidence: [{ value: "2", label: "migrated prototype slices" }, { value: "1", label: "correlated interaction" }, { value: "0", label: "universal IDs" }],
    repository: "https://github.com/zycxfyh/ordivon-world", href: "/projects/world", updatedAt: graphUpdatedAt,
  },
  {
    id: "project:web", kind: "project", slug: "web", title: "Ordivon Web", status: "active", group: "Public interface",
    label: "Research as an explorable system", publicPage: false,
    summary: "The public interface that connects projects, research questions, experiments, findings, decisions, and writing without duplicating repository truth.",
    state: "Static delivery is live; /system exposes three graph perspectives and active Questions now have durable public dossiers.",
    evidence: [{ value: "11", label: "research dossiers" }, { value: "6", label: "composable articles" }, { value: "3", label: "graph perspectives" }],
    repository: "https://github.com/zycxfyh/ordivon-web", updatedAt: graphUpdatedAt,
  },
  {
    id: "project:game", kind: "project", slug: "game", title: "Ordivon Game", status: "experimental", group: "Agent-native application",
    label: "Games where Agents change the playable structure", publicPage: false,
    summary: "An experimental application line for mechanics that become possible when Agents can perceive, decide, persist, and act through a shared Host.",
    state: "Playable prototype work is active; public presentation remains intentionally deferred.", evidence: [],
    repository: "https://github.com/zycxfyh/ordivon-game", updatedAt: graphUpdatedAt,
  },
  {
    id: "project:security", kind: "project", slug: "security", title: "Ordivon Security", status: "experimental", group: "Adversarial agency",
    label: "Control under strategic opposition", publicPage: false,
    summary: "A research line for high-intensity adversarial agency, dynamic intent, trajectory control, and evaluation when the acting subject actively resists observation or intervention.",
    state: "Research object and repository route are being redefined before further implementation.", evidence: [],
    repository: "https://github.com/zycxfyh/ordivon-security", updatedAt: graphUpdatedAt,
  },
];

export const questionNodes: QuestionNode[] = [
  {
    id: "question:computing-async-join", kind: "question", slug: "async-waiting-and-join",
    title: "Which Task Runtime objects are required by asynchronous waiting and Join semantics?",
    summary: "Determine the smallest durable objects required when work waits, fans out, and later joins.",
    importance: "Without explicit waiting and Join semantics, a Host or Runtime will hide continuity inside process state, polling loops, or a workflow engine it does not own.",
    hypothesis: "A thin set of durable dependency edges, wait conditions, Join policy, and Ready Frontier state is sufficient; scheduling and workflow authoring can remain outside the core contracts.",
    currentJudgment: "Open. The graph model identifies the missing continuity facts, but no interrupted fan-out and fan-in workload has yet proved the minimum object set.",
    nextStep: "Run one real Task that fans out across replaceable workers, waits through interruption, and joins without reconstructing admitted state.",
    falsifier: "If existing Task, Job, Outcome, and relation objects express waiting and Join behavior without ambiguity or hidden durable facts, add nothing.",
    status: "active", state: "open", href: "/research/async-waiting-and-join", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:computing-second-workload", kind: "question", slug: "contracts-across-a-second-workload",
    title: "Which contracts survive a second independent workload without being tailored to one repository?",
    summary: "Use an unrelated workload to distinguish general contracts from local accommodations.",
    importance: "A contract that only explains the workload that produced it is documentation, not a computing boundary.",
    hypothesis: "Task continuity, effect identity, evidence, and recovery contracts should survive a second workload through adapters rather than workload-specific core fields.",
    currentJudgment: "Testing. Host and Runtime have crossed multiple engineering paths, but a deliberately unrelated workload has not yet completed the same conformance route.",
    nextStep: "Use Game or another independent application as a second workload and record every exception requested from the shared contracts.",
    falsifier: "If repeated workload-specific exceptions are necessary to preserve progress, split or narrow the claimed shared contract instead of generalizing it further.",
    status: "active", state: "testing", href: "/research/contracts-across-a-second-workload", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:host-general-goal", kind: "question", slug: "host-general-repository-goal",
    title: "Can Host complete a general repository Goal without absorbing Runtime mechanics?",
    summary: "Test semantic continuity on real engineering work while preserving the Host–Runtime boundary.",
    importance: "Host only matters if semantic continuity survives real work; a demo loop that cannot cross restart, model replacement, and ambiguous effects does not establish a state owner.",
    hypothesis: "Host can own Goal, Task, candidate admission, verification, and Outcome while Runtime exclusively owns Workspaces, Jobs, process trees, and physical evidence.",
    currentJudgment: "Supported but incomplete. H2–H6 proved deterministic continuation and recovery on bounded paths without moving process ownership into Host; a broader repository Goal remains the next proof.",
    nextStep: "Complete a multi-step repository Goal across Host restart and model replacement while preserving admitted decisions and unknown-dispatch handling.",
    falsifier: "If Host must copy process, Workspace, or artifact truth to continue correctly—or loses semantic commitments when those objects remain in Runtime—the boundary is wrong.",
    status: "active", state: "testing", href: "/research/host-general-repository-goal", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:host-operational-surface", kind: "question", slug: "host-operational-surface",
    title: "What operational surface is required before Host becomes installable rather than architectural proof?",
    summary: "Identify the minimum inspect, service, backup, and recovery surface earned by real use.",
    importance: "A correct state model that cannot be inspected, restarted, backed up, or recovered remains a laboratory artifact rather than a dependable Host.",
    hypothesis: "A small inspect surface, service lifecycle, append-only journal backup, and explicit recovery report will be sufficient; a general operations platform is unnecessary.",
    currentJudgment: "Open. The journal and recovery model exist, but long-lived installation and operator recovery have not yet established the minimum public surface.",
    nextStep: "Run Host as a persistent service through routine restart, backup, restore, and one deliberately interrupted Task.",
    falsifier: "If the current journal plus ordinary service tooling already makes every required state observable and recoverable, do not add a separate operations layer.",
    status: "active", state: "open", href: "/research/host-operational-surface", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:runtime-structured-effect", kind: "question", slug: "runtime-structured-effect",
    title: "Which real structured operation can complete the full Effect contract?",
    summary: "Find one operation that owns canonical identity, authority, evidence, reconciliation, and ambiguity behavior.",
    importance: "The Effect contract remains partly abstract until one operation proves identity, source commitment, authority, evidence, reconciliation, and response-loss behavior together.",
    hypothesis: "One narrowly scoped deployment or mutation operation can complete the contract without turning Runtime into a provider framework.",
    currentJudgment: "Testing. Production dogfood strongly supports commitment as the Runtime abstraction, but the final structured operation and its ambiguity semantics remain unproven.",
    nextStep: "Select one real operation with observable side effects and implement canonical identity, preconditions, retained evidence, lookup, reconciliation, and unknown outcome handling.",
    falsifier: "If the operation's decisive facts are provider-side path, authority, or receipt conditions rather than local execution truth, it belongs in World instead of Runtime.",
    status: "active", state: "testing", href: "/research/runtime-structured-effect", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:runtime-boundary-friction", kind: "question", slug: "runtime-boundary-friction",
    title: "Which remaining friction belongs above Runtime rather than becoming another primitive?",
    summary: "Prevent workflow convenience from expanding the trusted execution kernel.",
    importance: "Every convenience promoted into Runtime becomes a durable compatibility and recovery obligation inside the trusted effect boundary.",
    hypothesis: "A new Runtime primitive is justified only when a physical fact cannot be reconstructed after interruption; workflow convenience belongs in Host, harnesses, or adapters.",
    currentJudgment: "Strongly supported. Repeated dogfood earned request lookup, progress, repair, lifecycle retention, and receipts, while many workflow conveniences remained safely outside the kernel.",
    nextStep: "Apply the unreconstructable-fact test to each new friction reported by Host, Game, and future workloads before adding any primitive.",
    falsifier: "If a repeated failure cannot be recovered or explained without a new durable Runtime fact, the thin boundary must expand by exactly that fact.",
    status: "active", state: "open", href: "/research/runtime-boundary-friction", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:world-correlated-recovery", kind: "question", slug: "world-correlated-recovery",
    title: "Can one Host Task combine path evidence and provider execution, reconcile a lost response, and continue without duplicate work?",
    summary: "Test whether path and external action evidence can support one recoverable Task trajectory.",
    importance: "A retry after response loss can duplicate an external effect unless delivery conditions, provider execution, authority, and receipts can be correlated before the next action.",
    hypothesis: "One World Interaction identity can bind target, path, identity, authority, provider request, receipt, and conditioned observation without replacing mature transports or provider APIs.",
    currentJudgment: "Testing. The internal planes and repository histories are now unified, but no end-to-end lost-response trajectory has yet reconciled a real provider action across a path change.",
    nextStep: "Run one provider mutation, lose the response deliberately, change the usable path, reconcile by evidence, and continue the original Task without duplicate work.",
    falsifier: "If provider idempotency and existing transport receipts compose directly in Host with equal recoverability and less state, a separate World Interaction object is unnecessary.",
    status: "experimental", state: "testing", href: "/research/world-correlated-recovery", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:world-boundary-value", kind: "question", slug: "world-boundary-value",
    title: "Does a thin World boundary prevent a real failure better than direct Host integration?",
    summary: "The project boundary must prove a concrete continuity gain before it expands.",
    importance: "World should not exist merely because networking and provider APIs are complicated; it must prevent a continuity failure that direct integration cannot handle cleanly.",
    hypothesis: "World earns its boundary only where path-conditioned delivery and external effect reconciliation must remain one recoverable interaction.",
    currentJudgment: "Supported but still experimental. Link and Edge unification corrected the project boundary and preserved two useful internal planes; the correlated recovery proof remains outstanding.",
    nextStep: "Implement the smallest correlated World Interaction and compare its failure recovery against a direct Host-to-provider path.",
    falsifier: "If direct Host integration remains simpler while preserving the same evidence, ambiguity, rebinding, and no-duplicate guarantees, close or narrow World.",
    status: "experimental", state: "open", href: "/research/world-boundary-value", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:web-research-interface", kind: "question", slug: "web-research-interface",
    title: "Can the public site expose Ordivon as a changing research graph rather than a directory of pages?",
    summary: "Test whether graph-based navigation improves understanding and makes the system worth revisiting.",
    importance: "A static project directory records conclusions but hides why boundaries changed, which experiments mattered, and what remains unresolved.",
    hypothesis: "Typed relations, explorable system perspectives, and durable Question dossiers can expose changing judgment without duplicating repository truth.",
    currentJudgment: "Structurally supported. Governance was removed, MDX became composable, and /system now exposes three graph perspectives; repeated public use of Question dossiers is the next evidence.",
    nextStep: "Publish every active Question as a dated dossier, use the site as the working orientation layer, and observe which views actually reduce explanation cost.",
    falsifier: "If the graph and dossiers are harder to maintain or understand than concise project pages and articles, collapse them back into simpler editorial views.",
    status: "active", state: "testing", href: "/research/web-research-interface", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:game-agent-native-mechanics", kind: "question", slug: "game-agent-native-mechanics",
    title: "Which game structures become possible only when Agents persist and act through the same Host?",
    summary: "Separate genuinely Agent-native mechanics from classical systems with an LLM attached.",
    importance: "Without a falsifiable distinction, Agent-native game design collapses into ordinary scripted games with probabilistic dialogue attached.",
    hypothesis: "Persistent agents sharing Task continuity can sustain roles, commitments, world changes, and cross-session strategies that fixed NPC state machines cannot express economically.",
    currentJudgment: "Testing. Prototype work indicates new interaction space, but the claimed mechanics have not yet been compared against a strong classical baseline.",
    nextStep: "Choose one mechanic, build both an Agent-persistent and deterministic scripted version, and compare expressive power, authoring cost, recovery, and player legibility.",
    falsifier: "If the same mechanic can be reproduced with a conventional state machine without losing its essential behavior or exploding authoring cost, it is not Agent-native.",
    status: "experimental", state: "testing", href: "/research/game-agent-native-mechanics", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:security-adversarial-trajectory", kind: "question", slug: "security-adversarial-trajectory",
    title: "Can trajectory control remain meaningful when an Agent strategically changes behavior under observation?",
    summary: "Model adversarial agency beyond static permissions, policy checks, and ordinary software security.",
    importance: "An adaptive subject can change intent, timing, explanation, and observable behavior in response to the evaluator, defeating controls that assume a fixed program or passive failure.",
    hypothesis: "High-intensity Agent security requires evidence and intervention over trajectories, commitments, and changing strategy in addition to classical isolation and authorization.",
    currentJudgment: "Open. The failure class is distinct from ordinary software security, but the smallest evaluable adversarial trajectory has not yet been formalized.",
    nextStep: "Define one bounded adversarial scenario with observable strategy changes, authorized objectives, intervention points, and a measurable control failure.",
    falsifier: "If classical authorization, isolation, monitoring, and incident response fully explain and control the scenario, do not introduce a new Agent-security abstraction.",
    status: "experimental", state: "open", href: "/research/security-adversarial-trajectory", updatedAt: graphUpdatedAt,
  },
];

export const experimentNodes: ExperimentNode[] = [
  { id: "experiment:host-h2-h6", kind: "experiment", title: "Host deterministic continuation and restart recovery", summary: "Read, cognition, mutation, response-loss recovery, and model replacement crossed H2–H6 without moving physical process ownership into Host.", status: "historical", state: "completed", date: "2026-07-27", updatedAt: "2026-07-27" },
  { id: "experiment:runtime-production-dogfood", kind: "experiment", title: "Runtime production dogfood and lifecycle cleanup", summary: "Repeated real work exposed observation, exact request lookup, Workspace repair, lifecycle retention, and receipted deployment requirements.", status: "active", state: "completed", date: "2026-07-28", updatedAt: "2026-07-28" },
  { id: "experiment:world-unification", kind: "experiment", title: "Link and Edge boundary unification", summary: "Repository histories and proven slices were combined to test World Interaction as the continuity object rather than networking and provider action as separate projects.", status: "experimental", state: "running", date: "2026-07-30", updatedAt: graphUpdatedAt },
  { id: "experiment:web-governance-audit", kind: "experiment", title: "Web governance displacement audit", summary: "The repository was measured against its actual interface code to test whether release evidence had displaced visual and research-system work.", status: "active", state: "completed", date: "2026-07-30", updatedAt: graphUpdatedAt },
];

export const findingNodes: FindingNode[] = [
  { id: "finding:host-state-above-session", kind: "finding", title: "Task truth belongs above model sessions and execution processes", summary: "A replaceable provider can reconstruct reasoning, but it cannot safely reconstruct admitted decisions, unknown dispatches, verification, or Task outcomes.", status: "active", confidence: "strong", date: "2026-07-27", updatedAt: "2026-07-27" },
  { id: "finding:runtime-commitment-boundary", kind: "finding", title: "Commitment—not command execution—is Runtime's decisive abstraction", summary: "Request identity, source commitment, process ownership, evidence, and explicit ambiguity matter more than wrapping additional host commands.", status: "active", confidence: "strong", date: "2026-07-28", updatedAt: "2026-07-28" },
  { id: "finding:link-edge-boundary-wrong", kind: "finding", title: "Link and Edge were useful analytical planes but the wrong repository boundary", summary: "Recovery must correlate path-conditioned delivery and external execution before retry, so one World Interaction boundary better matches the continuous object.", status: "active", confidence: "supported", date: "2026-07-30", updatedAt: graphUpdatedAt },
  { id: "finding:web-governance-displaced-interface", kind: "finding", title: "Release governance had become larger than the Web interface it protected", summary: "Most tracked implementation effort lived in evidence, archives, cross-browser matrices, and release scripts while the system map remained four links and a CSS line.", status: "active", confidence: "strong", date: "2026-07-30", updatedAt: graphUpdatedAt },
];

export const decisionNodes: DecisionNode[] = [
  { id: "decision:extract-host", kind: "decision", title: "Extract Host as an independent state owner", summary: "Host now versions Task continuity independently while Computing retains shared contracts and Runtime retains physical execution truth.", status: "active", rationale: "Continuation and recovery proved a durable state boundary that would be blurred by continued incubation inside Computing.", date: "2026-07-27", updatedAt: "2026-07-27" },
  { id: "decision:unify-world", kind: "decision", title: "Unify Link and Edge under Ordivon World", summary: "Preserve their proven internal planes while removing the project boundary that split one recoverable external interaction.", status: "active", rationale: "The intended Effect conditions path choice, and response loss cannot be reconciled without delivery and execution evidence together.", date: "2026-07-30", updatedAt: graphUpdatedAt },
  { id: "decision:thin-web-release", kind: "decision", title: "Return Web release checks to build, smoke, preview, and deploy", summary: "Delete in-tree release evidence, duplicate V1 archives, browser matrices, and repeated performance proof.", status: "active", rationale: "Git-based recovery is cheaper than the governance system, and no retained gate demonstrated loss proportionate to its maintenance cost.", date: "2026-07-30", updatedAt: graphUpdatedAt },
  { id: "decision:mdx-writing", kind: "decision", title: "Replace JSON-embedded HTML with composable MDX", summary: "Articles are now real content modules that can embed research interfaces without retaining a migration pipeline.", status: "active", rationale: "The previous system paid for MDX and JSON HTML simultaneously while receiving the capabilities of neither.", date: "2026-07-30", updatedAt: graphUpdatedAt },
];

export const articleNodes: ArticleNode[] = articleMetadata.map((article) => ({
  id: `article:${article.slug}`,
  kind: "article" as const,
  slug: article.slug,
  title: article.title,
  summary: article.description,
  status: "active" as const,
  href: `/writing/${article.slug}`,
  articleType: article.type,
  project: article.project,
  date: article.date,
  updatedAt: article.modifiedDate,
}));

export const graphNodes: GraphNode[] = [
  ...systemNodes,
  ...projectNodes,
  ...questionNodes,
  ...experimentNodes,
  ...findingNodes,
  ...decisionNodes,
  ...articleNodes,
];
