import { articleMetadata } from "@/content/articles/registry";
import type { ArticleNode, DecisionNode, ExperimentNode, FindingNode, GraphNode, ProjectNode, QuestionNode, SystemNode } from "@/lib/graph/types";

export const graphUpdatedAt = "2026-07-31";

export const systemNodes: SystemNode[] = [
  {
    id: "system:computing", kind: "system", slug: "computing", index: "01", title: "Computing", status: "active",
    summary: "The contract and conformance layer for persistent work performed with replaceable probabilistic cognition.",
    thesis: "Keep cognition, Task continuity, semantic execution, and machine execution separable.",
    question: "Which facts and contracts must remain stable when models, Hosts, tools, and execution backends change?",
    owns: ["Stack model", "Semantic contracts", "Reference systems", "Conformance"],
    boundary: ["No production Tasks", "No physical Jobs", "No implementation monorepo"],
    href: "/projects/computing", updatedAt: graphUpdatedAt,
  },
  {
    id: "system:host", kind: "system", slug: "host", index: "02", title: "Host", status: "active",
    summary: "The semantic control plane that keeps Goals and Tasks continuous above replaceable sessions and processes.",
    thesis: "Replace the model session without replacing the Task.",
    question: "Which semantic state must survive when cognition, transport, and execution processes are replaced?",
    owns: ["Goals and Tasks", "Host journal", "Cognition contexts", "Outcomes"],
    boundary: ["No process ownership", "No model monopoly", "No Runtime mechanics"],
    href: "/projects/host", updatedAt: graphUpdatedAt,
  },
  {
    id: "system:runtime", kind: "system", slug: "runtime", index: "03", title: "Runtime", status: "active",
    summary: "The physical effect boundary that owns durable local execution identity, process state, and retained evidence.",
    thesis: "Commit one Agent action to reality without losing what happened.",
    question: "Which execution facts cannot safely be reconstructed after interruption?",
    owns: ["Workspaces", "Jobs and Attempts", "Process trees", "Artifacts"],
    boundary: ["Trusted-local, not a sandbox", "No Goal ownership", "No invented exactly-once claims"],
    href: "/projects/runtime", updatedAt: graphUpdatedAt,
  },
  {
    id: "system:world", kind: "system", slug: "world", index: "04", title: "World", status: "experimental",
    summary: "The continuity boundary for paths, identities, authority, provider actions, receipts, and external uncertainty.",
    thesis: "Let a Task reach and act through a changing external world without rebuilding the world beneath it.",
    question: "What must remain continuous when connection and external action fail together?",
    owns: ["World Interaction bindings", "Conditioned observations", "External evidence", "Reconciliation and rebinding"],
    boundary: ["No universal proxy or transport", "No provider reimplementation", "No Goal, Task, or local process ownership"],
    href: "/projects/world", updatedAt: graphUpdatedAt,
  },
];

export const projectNodes: ProjectNode[] = [
  {
    id: "project:computing", kind: "project", slug: "computing", title: "Ordivon Computing", status: "active", group: "Foundations",
    label: "Contracts that survive replacement", systemNodeId: "system:computing", publicPage: true,
    summary: "The research and conformance root for persistent work performed with probabilistic models. Computing defines the contracts that other projects test rather than becoming another production runtime.",
    state: "Core Work System Round 1 reduced the proposed shared core against LangGraph, Temporal, direct retrieval, durable Activities, and live Codex/Hermes replacement; Harness H1–H3 are now implemented in Host.",
    evidence: [{ value: "16", label: "deterministic variants" }, { value: "6/6", label: "live replacement trials" }, { value: "2", label: "active research lines" }],
    repository: "https://github.com/zycxfyh/ordivon-computing", href: "/projects/computing", updatedAt: graphUpdatedAt,
  },
  {
    id: "project:host", kind: "project", slug: "host", title: "Ordivon Host", status: "active", group: "Agent system",
    label: "Task continuity above sessions", systemNodeId: "system:host", publicPage: true,
    summary: "A persistent Agent control plane for Goals, Tasks, bounded cognition, candidate admission, Harness assignment, Effect proposals, verification, and outcomes. Model sessions and Runtime processes remain replaceable dependencies.",
    state: "Harness H1–H3 are implemented: Host owns Assignment fencing and completion adjudication, correlates real Runtime Jobs through opaque references, and retains provider-faithful Codex App Server Thread, Turn, Tool, usage, and raw-event evidence without treating process success as Task completion.",
    evidence: [{ value: "H1–H3", label: "Harness stages complete" }, { value: "1", label: "live Codex App Server run" }, { value: "H4–H5", label: "next falsifier" }],
    repository: "https://github.com/zycxfyh/ordivon-host", href: "/projects/host", updatedAt: graphUpdatedAt,
  },
  {
    id: "project:runtime", kind: "project", slug: "runtime", title: "Ordivon Runtime", status: "active", group: "Agent system",
    label: "Committed local effects", systemNodeId: "system:runtime", publicPage: true,
    summary: "The deterministic boundary between an Agent decision and local machine execution. Runtime binds exact source and operation identity to durable Jobs, process trees, bounded evidence, cancellation, reconciliation, and recovery.",
    state: "Production Runtime remains at thirteen public tools. Host H2/R2 proved cross-layer correlation, replay, recovery, and terminal evidence through existing request identity and opaque foreign references without adding Host Task semantics to Runtime.",
    evidence: [{ value: "13", label: "public tools" }, { value: "4", label: "opaque Host references" }, { value: "0", label: "new Runtime semantic objects" }],
    repository: "https://github.com/zycxfyh/ordivon-runtime", href: "/projects/runtime", updatedAt: graphUpdatedAt,
  },
  {
    id: "project:world", kind: "project", slug: "world", title: "Ordivon World", status: "experimental", group: "World interaction",
    label: "Conditioned external interaction", systemNodeId: "system:world", publicPage: true,
    summary: "The Task-to-external-world interaction boundary. World correlates target, path, identity, transport, provider execution, authority, Receipt, Artifact, conditioned evidence, uncertainty, reconciliation, and rebinding while mature systems retain their native mechanisms.",
    state: "Former Link and Edge histories are unified and retired as separate projects. The next decision is empirical: compare one correlated lost-response recovery path against direct Host-to-provider integration.",
    evidence: [{ value: "2", label: "retired prototype boundaries" }, { value: "1", label: "World Interaction question" }, { value: "W1", label: "next decisive experiment" }],
    repository: "https://github.com/zycxfyh/ordivon-world", href: "/projects/world", updatedAt: graphUpdatedAt,
  },
  {
    id: "project:web", kind: "project", slug: "web", title: "Ordivon Web", status: "active", group: "Public interface",
    label: "Research as an explorable system", publicPage: false,
    summary: "The public interface that connects projects, research questions, experiments, findings, decisions, and writing without duplicating repository truth.",
    state: "Web V2 is closed around static delivery, one typed graph, durable Question dossiers, an argument network, and a continuity-led visual thesis. Current work moves from interface reconstruction to research publication.",
    evidence: [{ value: "15", label: "research dossiers" }, { value: "8", label: "argument nodes" }, { value: "1", label: "typed public graph" }],
    repository: "https://github.com/zycxfyh/ordivon-web", updatedAt: graphUpdatedAt,
  },
  {
    id: "project:game", kind: "project", slug: "game", title: "Ordivon Game", status: "experimental", group: "Agent-native application",
    label: "Persistent Agents inside a verified World", publicPage: false,
    summary: "Station Zero tests persistent single- and multi-Agent roles, partial knowledge, typed communication, player authority, deterministic World effects, replay, diagnosis, and exact comparison through shared Host semantics.",
    state: "Station Zero v0.1.0-alpha.1 is released as a source-playable developer Alpha with replay, evidence-linked diagnosis, exact run comparison, reload recovery, and clean archive verification.",
    evidence: [{ value: "v0.1.0-alpha.1", label: "released Alpha" }, { value: "406,855 B", label: "verified archive" }, { value: "2", label: "exact-comparison runs" }],
    repository: "https://github.com/zycxfyh/ordivon-game", updatedAt: graphUpdatedAt,
  },
  {
    id: "project:security", kind: "project", slug: "security", title: "Ordivon Security", status: "experimental", group: "Adversarial agency",
    label: "Control under strategic opposition", publicPage: false,
    summary: "A research line for strategic adversarial agency, dynamic opponents, trajectory evidence, multidimensional outcomes, and evaluation when the acting subject adapts to observation and intervention.",
    state: "Round 1 completed 84 bounded Trials across a local dynamic-opponent World, CAGE Challenge 4, and model-backed diagnostics. The experimental method is retained; no Campaign engine, organization ontology, strategic state, custom cyber range, or general capability claim was promoted.",
    evidence: [{ value: "84", label: "bounded Trials" }, { value: "3", label: "experiment families" }, { value: "0", label: "strategic layers promoted" }],
    repository: "https://github.com/zycxfyh/ordivon-security", updatedAt: graphUpdatedAt,
  },
];

export const questionNodes: QuestionNode[] = [
  {
    id: "question:computing-smallest-core", kind: "question", slug: "smallest-agent-native-core",
    title: "Which Agent-native responsibilities remain after strong classical baselines?",
    summary: "Use mature workflow, retrieval, idempotency, and provider systems to delete any shared abstraction that does not own a distinct failure.",
    importance: "A proposed core becomes permanent inheritance. It should contain only responsibilities that survive strong alternatives, multiple workloads, cost measurement, and a deletion test.",
    hypothesis: "Task meaning belongs in Host, physical execution truth in Runtime, and correlated external interaction may belong in World; durable workflow mechanics, generalized Context state, and provider-specific lifecycle can remain in mature systems or owning applications.",
    currentJudgment: "Answered within the Round 1 boundary. LangGraph and Temporal carried durable work state; current-revision retrieval matched the tested Context need; single-backend Effect machinery shrank to identity, UNKNOWN, correlation, reconciliation, and no blind redispatch; live provider replacement preserved Task state without proving model equivalence.",
    nextStep: "Use the result as an admission test in World W1 and Harness H4–H5. Reopen the shared-core boundary only when a materially different workload exposes an unowned non-bypassable responsibility.",
    falsifier: "A future workload repeatedly fails because a stable responsibility cannot remain in Host, Runtime, World, a mature workflow engine, or a provider-faithful adapter.",
    status: "active", state: "answered", href: "/research/smallest-agent-native-core", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:computing-async-join", kind: "question", slug: "async-waiting-and-join",
    title: "Which Task Runtime objects are required by asynchronous waiting and Join semantics?",
    summary: "Determine the smallest durable objects required when work waits, fans out, and later joins.",
    importance: "Without explicit waiting and Join semantics, a Host or Runtime will hide continuity inside process state, polling loops, or a workflow engine it does not own.",
    hypothesis: "A thin set of durable dependency edges, wait conditions, Join policy, and Ready Frontier state is sufficient; scheduling and workflow authoring can remain outside the core contracts.",
    currentJudgment: "Open. Round 1 showed that mature workflow engines can carry durable work mechanics, but no interrupted fan-out and fan-in workload has yet proved which semantic Join facts must remain visible above those mechanics.",
    nextStep: "Run one real Task that fans out across replaceable workers, waits through interruption, and joins without reconstructing admitted state.",
    falsifier: "If existing Task, Job, Outcome, workflow state, and typed relation objects express waiting and Join behavior without ambiguity or hidden durable facts, add nothing.",
    status: "active", state: "open", href: "/research/async-waiting-and-join", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:computing-second-workload", kind: "question", slug: "contracts-across-a-second-workload",
    title: "Which contracts survive a second independent workload without being tailored to one repository?",
    summary: "Use unrelated applications to distinguish general contracts from local accommodations.",
    importance: "A contract that only explains the workload that produced it is documentation, not a computing boundary.",
    hypothesis: "Task continuity, effect identity, evidence, and recovery contracts should survive materially different workloads through adapters rather than workload-specific core fields.",
    currentJudgment: "Strongly supported but not fully closed. Game implemented the immutable Host workload profile across a TypeScript deterministic World, single- and multi-Agent paths, response-loss recovery, and exact replay, then removed thirteen duplicate truth tables without changing World outcomes. A second non-Game external domain remains useful pressure.",
    nextStep: "Apply the surviving contracts to World W1 or another non-Game provider path and record every requested exception before promoting any further shared field.",
    falsifier: "If repeated workload-specific exceptions are necessary to preserve progress, split or narrow the claimed shared contract instead of generalizing it further.",
    status: "active", state: "testing", href: "/research/contracts-across-a-second-workload", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:computing-calibrated-non-action", kind: "question", slug: "calibrated-non-action",
    title: "When should an Agent act, wait, observe, refuse, reconcile, or request a decision?",
    summary: "Treat non-action as a timed, evidence-bearing decision rather than the absence of Agent capability.",
    importance: "Acting too early can duplicate or commit the wrong Effect; waiting too long can lose a deadline, resource, or strategic option. Static approval-everywhere and model-only escalation both waste scarce attention or miss consequence boundaries.",
    hypothesis: "Host-local DecisionRequests, explicit UNKNOWN and wait states, deadlines, evidence requirements, and paired act/abstain evaluation can preserve authorized utility with fewer operator interruptions than uniform approval rules.",
    currentJudgment: "Testing. Round 1 reduced deterministic approval interruptions from 12 to 7 with no missed escalation in its designed cases, but those timings were estimated rather than measured with real operators. Security, Game, Runtime, and World now provide stronger act-versus-wait trajectories.",
    nextStep: "Run paired act/abstain trajectories with real timing, consequence, expiry, and recovery data across one authority request, one UNKNOWN Effect, and one adversarial policy switch.",
    falsifier: "A simpler static policy or always-act baseline achieves equal authorized utility, timing, recovery, and operator cost with fewer persistent states.",
    status: "active", state: "testing", href: "/research/calibrated-non-action", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:host-general-goal", kind: "question", slug: "host-general-repository-goal",
    title: "Can Host complete a general repository Goal without absorbing Runtime mechanics?",
    summary: "Test semantic continuity on real engineering work while preserving the Host–Runtime boundary.",
    importance: "Host only matters if semantic continuity survives real work; a demo loop that cannot cross restart, model replacement, and ambiguous effects does not establish a state owner.",
    hypothesis: "Host can own Goal, Task, candidate admission, Harness assignment, verification, and Outcome while Runtime exclusively owns Workspaces, Jobs, process trees, and physical evidence.",
    currentJudgment: "Supported but incomplete. H2–H6 established bounded continuation; Harness H1–H3 added assignment fencing, completion adjudication, Runtime correlation, and a real Codex App Server run while Runtime retained the process tree and Host correctly left the Task waiting after process success. Cross-Harness replacement and a broader repository Goal remain outstanding.",
    nextStep: "Complete Harness H4–H5, then run one multi-step repository Goal across Host restart and Codex/Hermes replacement while preserving admitted decisions, unknown-effect handling, and acceptance evidence.",
    falsifier: "If Host must copy process, Workspace, or Artifact truth to continue correctly—or loses semantic commitments when those objects remain in Runtime—the boundary is wrong.",
    status: "active", state: "testing", href: "/research/host-general-repository-goal", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:host-operational-surface", kind: "question", slug: "host-operational-surface",
    title: "What operational surface is required before Host becomes installable rather than architectural proof?",
    summary: "Identify the minimum inspect, service, backup, and recovery surface earned by real use.",
    importance: "A correct state model that cannot be inspected, restarted, backed up, or recovered remains a laboratory artifact rather than a dependable Host.",
    hypothesis: "A small inspect surface, service lifecycle, append-only journal backup, and explicit recovery report will be sufficient; a general operations platform is unnecessary.",
    currentJudgment: "Open. The journal, recovery model, operator handoff, and Harness receipts exist, but long-lived installation and operator recovery have not yet established the minimum public surface.",
    nextStep: "Run Host as a persistent service through routine restart, backup, restore, and one deliberately interrupted Task.",
    falsifier: "If the current journal plus ordinary service tooling already makes every required state observable and recoverable, do not add a separate operations layer.",
    status: "active", state: "open", href: "/research/host-operational-surface", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:host-harness-composition", kind: "question", slug: "harness-composition-and-completion",
    title: "Which Harness objects survive live provider replacement without duplicating Host or Runtime state?",
    summary: "Prove or delete a Host-local Harness boundary across provider-faithful lifecycles, replacement, faults, and completion adjudication.",
    importance: "A shared Harness abstraction can erase useful provider capabilities or create a second Task and Session system. Direct drivers can also duplicate assignment, evidence, fencing, and completion logic unless the stable overlap is measured.",
    hypothesis: "Host-local Assignment, HarnessRunReceipt, CompletionProposal, capability manifest, generation fencing, and completion adjudication will survive Codex App Server and Hermes ACP, while provider Thread and Session identities remain local evidence.",
    currentJudgment: "Testing. H1–H3 are implemented. Host owns immutable assignment and completion objects; Runtime correlation required no new Runtime semantics; Codex App Server retained Thread, Turn, Tool, usage, interrupt, and raw-event evidence. No shared cross-provider adapter has yet earned promotion.",
    nextStep: "Implement the provider-faithful Hermes ACP H4 path, then execute both H5 replacement orders and the stale proposal, missing Artifact, and unresolved UNKNOWN faults under equal budgets.",
    falsifier: "Direct provider drivers plus ordinary Host Task state remain simpler and equally correct, or a shared interface destroys material provider capability or adds more lifecycle code than it removes.",
    status: "active", state: "testing", href: "/research/harness-composition-and-completion", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:runtime-structured-effect", kind: "question", slug: "runtime-structured-effect",
    title: "Which real structured operation can complete the minimal Effect contract across a second backend?",
    summary: "Find one operation that proves stable identity, explicit uncertainty, correlation, reconciliation, and no blind redispatch beyond local process execution.",
    importance: "Round 1 weakened the larger Effect model on a single backend. A shared contract is not earned until a structurally different external path needs more than mature provider idempotency, durable Activities, and Runtime terminal evidence.",
    hypothesis: "The surviving cross-backend core is stable intended identity, explicit UNKNOWN, backend correlation, reconciliation, and a prohibition on blind redispatch; authority, path, and provider receipts remain World-owned when they condition the external effect.",
    currentJudgment: "Testing after contraction. Runtime dogfood supports commitment as the local abstraction, while Round 1 showed no advantage for a larger single-backend Effect graph. Host H2/R2 also completed real correlation and recovery through existing Runtime request identity and opaque references without expanding Runtime.",
    nextStep: "Use World W1 as the second backend and compare direct provider integration against the minimum Effect fields under response loss, path change, reconciliation, and continuation.",
    falsifier: "Stable provider request identity, native receipts, durable Activities, and direct Host integration preserve the same ambiguity and recovery with less permanent machinery.",
    status: "active", state: "testing", href: "/research/runtime-structured-effect", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:runtime-boundary-friction", kind: "question", slug: "runtime-boundary-friction",
    title: "Which remaining friction belongs above Runtime rather than becoming another primitive?",
    summary: "Prevent workflow and Harness convenience from expanding the trusted execution kernel.",
    importance: "Every convenience promoted into Runtime becomes a durable compatibility and recovery obligation inside the trusted effect boundary.",
    hypothesis: "A new Runtime primitive is justified only when a physical fact cannot be reconstructed after interruption; workflow, Task, Harness, and provider convenience belongs in Host, adapters, or World.",
    currentJudgment: "Strongly supported. Repeated dogfood earned request lookup, progress, repair, lifecycle retention, and receipts. Harness H2/R2 then proved Assignment and Harness Run correlation, exact replay, fresh-client recovery, and terminal evidence using four opaque foreign references with zero new Runtime semantic objects.",
    nextStep: "Apply the unreconstructable-physical-fact test to each new friction reported by Host, Game, World, and future workloads before adding any primitive.",
    falsifier: "A repeated failure cannot be recovered, correlated, or explained without a new durable Runtime-owned physical fact.",
    status: "active", state: "open", href: "/research/runtime-boundary-friction", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:world-correlated-recovery", kind: "question", slug: "world-correlated-recovery",
    title: "Can one Host Task combine path evidence and provider execution, reconcile a lost response, and continue without duplicate work?",
    summary: "Test whether path and external action evidence can support one recoverable Task trajectory.",
    importance: "A retry after response loss can duplicate an external effect unless delivery conditions, provider execution, authority, and receipts can be correlated before the next action.",
    hypothesis: "One World Interaction identity can bind target, path, identity, authority, provider request, receipt, and conditioned observation without replacing mature transports or provider APIs.",
    currentJudgment: "Testing. Link and Edge are now retired as separate projects and their useful planes are preserved inside World, but no end-to-end lost-response trajectory has yet reconciled a real provider action across a path change.",
    nextStep: "Run World W1: perform one provider mutation, lose the response deliberately, change the usable path, reconcile by evidence, and continue the original Task without duplicate work.",
    falsifier: "Provider idempotency and existing transport receipts compose directly in Host with equal recoverability and less state.",
    status: "experimental", state: "testing", href: "/research/world-correlated-recovery", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:world-boundary-value", kind: "question", slug: "world-boundary-value",
    title: "Does a thin World boundary prevent a real failure better than direct Host integration?",
    summary: "The project boundary must prove a concrete continuity gain before it expands.",
    importance: "World should not exist merely because networking and provider APIs are complicated; it must prevent a continuity failure that direct integration cannot handle cleanly.",
    hypothesis: "World earns its boundary only where path-conditioned delivery and external effect reconciliation must remain one recoverable interaction.",
    currentJudgment: "Supported as a corrected research boundary but still experimentally open. Link and Edge unification removed the wrong repository split; World W1 must now prove that correlated recovery creates more value than direct Host integration.",
    nextStep: "Implement the smallest correlated World Interaction and compare its failure recovery against a direct Host-to-provider path.",
    falsifier: "Direct Host integration remains simpler while preserving the same evidence, ambiguity, rebinding, and no-duplicate guarantees.",
    status: "experimental", state: "open", href: "/research/world-boundary-value", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:web-research-interface", kind: "question", slug: "web-research-interface",
    title: "Can the public site expose Ordivon as a changing research graph rather than a directory of pages?",
    summary: "Test whether graph-based navigation improves understanding and makes the system worth revisiting.",
    importance: "A static project directory records conclusions but hides why boundaries changed, which experiments mattered, and what remains unresolved.",
    hypothesis: "Typed relations, explorable system perspectives, durable Question dossiers, and graph-derived writing can expose changing judgment without duplicating repository truth.",
    currentJudgment: "Structurally and visually supported. Web V2 is closed around one typed graph that drives System, Research, Writing, article context, Current, and a continuity-led homepage without restoring release governance or duplicate state.",
    nextStep: "Use the public interface during real publication work and observe whether Question dossiers, evidence trajectories, and argument links reduce explanation cost for first-time and returning readers.",
    falsifier: "The graph and dossiers are harder to maintain or understand than concise project pages and articles, or publication repeatedly requires a second mutable fact registry.",
    status: "active", state: "testing", href: "/research/web-research-interface", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:game-agent-native-mechanics", kind: "question", slug: "game-agent-native-mechanics",
    title: "Which game structures become possible only when Agents persist and act through the same Host?",
    summary: "Separate genuinely Agent-native mechanics from classical systems with an LLM attached.",
    importance: "Without a falsifiable distinction, Agent-native game design collapses into ordinary scripted games with probabilistic dialogue attached.",
    hypothesis: "Persistent Agents sharing Task continuity can sustain actor-local knowledge, typed communication, authority, replaceable cognition, and recoverable commitments that fixed NPC state machines cannot express economically.",
    currentJudgment: "Testing with a released application. Station Zero now demonstrates persistent specialists, partial observations, communication whose reachability changes outcomes, player authority, provider replacement, replay, diagnosis, and exact run comparison. It still does not prove that these mechanics outperform a strong classical implementation or equal-budget single Agent.",
    nextStep: "Run the planned equal-budget single-Agent/multi-Agent ablation and implement one strong deterministic scripted baseline for the same mechanic and player information surface.",
    falsifier: "The same mechanic and player experience can be reproduced with a conventional state machine or single Agent without losing essential behavior or causing disproportionate authoring cost.",
    status: "experimental", state: "testing", href: "/research/game-agent-native-mechanics", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:security-adversarial-trajectory", kind: "question", slug: "security-adversarial-trajectory",
    title: "Can strategic adversarial trajectories be evaluated without collapsing them into one reward or success flag?",
    summary: "Model adaptive opposition through separate World truth, actor observation, decisions, effects, and multidimensional outcomes.",
    importance: "An adaptive subject can change policy, timing, explanation, and observable behavior. One action success or reward can hide deception, exposure, resource loss, mission damage, or strategic failure.",
    hypothesis: "A thin experiment layer with exact identities, observation/truth separation, digest-bound traces, dynamic opponents, and independent tactical, operational, strategic, information, organization, evaluator, and cost outcomes is sufficient to test candidate Agent-native distinctions before promoting shared architecture.",
    currentJudgment: "Testing with executable evidence. Round 1 completed 84 Trials and showed that tactical success can be strategically harmful, CAGE reward and foothold spread can conflict, richer model interpretation need not improve action, and organization can isolate compromised advice without creating new capability. The method survived; no Campaign engine or strategic ontology was promoted.",
    nextStep: "Run the next bounded experiment across multiple seeds, held-out opponent policies, compiled opponent state, and deliberate Host Session disruption while retaining multidimensional evidence.",
    falsifier: "Classical authorization, simulation, ordinary Goal/Task state, source-native metrics, and reactive policies explain the same failures and comparisons with fewer Security-specific objects.",
    status: "experimental", state: "testing", href: "/research/security-adversarial-trajectory", updatedAt: graphUpdatedAt,
  },
  {
    id: "question:security-opponent-state-transfer", kind: "question", slug: "opponent-state-transfer",
    title: "Does compiled opponent state retain value across seeds, held-out policies, Context loss, and Harness replacement?",
    summary: "Distinguish durable strategic information from fixture-specific explanation and provider-specific reasoning style.",
    importance: "Round 1 improved local switch recognition and preserved richer hypotheses, but all retained model Trials failed the objective. Without transfer, opponent state is descriptive overhead rather than durable capability.",
    hypothesis: "Explicit opponent hypotheses and revisions will improve held-out switch recognition, resource timing, and objective completion when transcript Context is truncated or the Harness is replaced, provided the state is compiled from verified observations rather than model narrative alone.",
    currentJudgment: "Open after mixed Round 1 evidence. The local opponent-aware actor improved diagnosis and objective rate, one Codex strategic Trial recognized a switch, Hermes outcomes were unchanged, and no model Trial completed the genuine objective. No causal or transferable advantage is established.",
    nextStep: "Compare transcript-only and compiled-state conditions across multiple seeds, held-out opponent policies, bounded Context loss, and both Codex and Hermes Harness replacement.",
    falsifier: "A reactive policy or transcript-only Agent matches held-out objective, information, timing, and recovery outcomes with lower state and maintenance cost.",
    status: "experimental", state: "testing", href: "/research/opponent-state-transfer", updatedAt: graphUpdatedAt,
  },
];

export const experimentNodes: ExperimentNode[] = [
  { id: "experiment:host-h2-h6", kind: "experiment", title: "Host deterministic continuation and restart recovery", summary: "Read, cognition, mutation, response-loss recovery, and model replacement crossed H2–H6 without moving physical process ownership into Host.", status: "historical", state: "completed", date: "2026-07-27", updatedAt: "2026-07-27" },
  { id: "experiment:runtime-production-dogfood", kind: "experiment", title: "Runtime production dogfood and lifecycle cleanup", summary: "Repeated real work exposed observation, exact request lookup, Workspace repair, lifecycle retention, and receipted deployment requirements.", status: "active", state: "completed", date: "2026-07-28", updatedAt: "2026-07-28" },
  { id: "experiment:game-multi-agent-m3", kind: "experiment", title: "Station Zero persistent multi-Agent team", summary: "Three specialists with actor-local Context, typed communication, explicit authority, atomic World time, replaceable Providers, interruption recovery, and exact replay completed deterministic and live trajectories without a manager model.", status: "active", state: "completed", date: "2026-07-29", updatedAt: "2026-07-29" },
  { id: "experiment:game-authority-cutover", kind: "experiment", title: "Game Host authority cutover", summary: "A working Python sidecar competed with an embedded Host authority; measured latency, code size, process cost, and duplicate ownership caused the sidecar and thirteen duplicate truth tables to be deleted.", status: "active", state: "completed", date: "2026-07-29", updatedAt: "2026-07-29" },
  { id: "experiment:core-work-system-round1", kind: "experiment", title: "Core Work System Round 1", summary: "Sixteen deterministic variants and six live Codex/Hermes replacement Trials compared Ordivon claims against LangGraph, Temporal, direct retrieval, idempotency and audit, durable Activities, and alternative attention policies.", status: "active", state: "completed", date: "2026-07-30", updatedAt: "2026-07-30" },
  { id: "experiment:security-round1", kind: "experiment", title: "Security dynamic-opponent Round 1", summary: "Sixty local, twenty CAGE Challenge 4, and four model-backed Trials tested deception, policy switching, multidimensional outcomes, organization under compromise, and explicit strategic state.", status: "experimental", state: "completed", date: "2026-07-30", updatedAt: "2026-07-30" },
  { id: "experiment:station-zero-alpha", kind: "experiment", title: "Station Zero first playable Alpha", summary: "The exact source release completed a Chromium journey through play, terminal outcome, point-in-time replay, evidence-linked diagnosis, redeployment, exact comparison, reload recovery, and clean archive reverification.", status: "experimental", state: "completed", date: "2026-07-30", updatedAt: "2026-07-30" },
  { id: "experiment:harness-h1-contracts", kind: "experiment", title: "Harness H1 contracts and fencing", summary: "Host added immutable Task Attempt, Assignment, Harness Run, CompletionProposal, capability, generation-fencing, and completion-decision objects without new scheduler, Session store, or assignment tables.", status: "active", state: "completed", date: "2026-07-30", updatedAt: "2026-07-30" },
  { id: "experiment:world-unification", kind: "experiment", title: "Link and Edge boundary unification", summary: "Repository histories and proven slices were combined to test World Interaction as the continuity object rather than networking and provider action as separate projects.", status: "experimental", state: "running", date: "2026-07-30", updatedAt: graphUpdatedAt },
  { id: "experiment:web-governance-audit", kind: "experiment", title: "Web governance displacement audit", summary: "The repository was measured against its actual interface code to test whether release evidence had displaced visual and research-system work.", status: "active", state: "completed", date: "2026-07-30", updatedAt: graphUpdatedAt },
  { id: "experiment:harness-h3-codex-app", kind: "experiment", title: "Codex App Server H3 live Harness run", summary: "A Runtime-managed read-only Codex App Server run retained Thread, Turn, Tool lifecycle, usage, interrupt capability, raw provider digest, Runtime artifacts, and Host handoff while the Task correctly remained waiting.", status: "active", state: "completed", date: "2026-07-31", updatedAt: graphUpdatedAt },
  { id: "experiment:harness-h2-runtime-correlation", kind: "experiment", title: "Harness H2 and Runtime R2 correlation", summary: "One real Host request used four opaque foreign references, exact request replay, changed-generation conflict, terminal evidence, fresh-client recovery, and Host receipt admission without Runtime claiming semantic Task completion.", status: "active", state: "completed", date: "2026-07-31", updatedAt: graphUpdatedAt },
];

export const findingNodes: FindingNode[] = [
  { id: "finding:host-state-above-session", kind: "finding", title: "Task truth belongs above model sessions and execution processes", summary: "A replaceable provider can reconstruct reasoning, but it cannot safely reconstruct admitted decisions, unknown dispatches, verification, or Task outcomes.", status: "active", confidence: "strong", date: "2026-07-27", updatedAt: "2026-07-27" },
  { id: "finding:runtime-commitment-boundary", kind: "finding", title: "Commitment—not command execution—is Runtime's decisive abstraction", summary: "Request identity, source commitment, process ownership, evidence, and explicit ambiguity matter more than wrapping additional host commands.", status: "active", confidence: "strong", date: "2026-07-28", updatedAt: "2026-07-28" },
  { id: "finding:communication-is-world-state", kind: "finding", title: "Communication reachability is gameplay state", summary: "The same typed task offer produced victory through a reachable local channel and power exhaustion when radio delivery arrived after the coordination window.", status: "active", confidence: "strong", date: "2026-07-29", updatedAt: "2026-07-29" },
  { id: "finding:one-authority-over-shared-process", kind: "finding", title: "One authority matters more than one shared implementation", summary: "The correct Host semantics survived an embedded implementation while a functionally correct Python sidecar added startup, transport, deployment, code-size, and split-recovery cost.", status: "active", confidence: "strong", date: "2026-07-29", updatedAt: "2026-07-29" },
  { id: "finding:mature-workflows-carry-state", kind: "finding", title: "Mature workflow systems can carry durable Agent work state", summary: "LangGraph SQLite checkpoints and Temporal Workflow state preserved the tested semantic fields and recovered pending work without duplicate Effects; Ordivon did not earn a separate Task Runtime.", status: "active", confidence: "strong", date: "2026-07-30", updatedAt: "2026-07-30" },
  { id: "finding:transcript-not-task-database", kind: "finding", title: "A transcript is not an authoritative Task database", summary: "Transcript summaries and full transcript Context can preserve useful cognition while omitting pending operation identity or mixing stale and untrusted claims that make retries unsafe.", status: "active", confidence: "strong", date: "2026-07-30", updatedAt: "2026-07-30" },
  { id: "finding:more-context-not-safer", kind: "finding", title: "More Context is not automatically safer", summary: "Current-revision source retrieval matched the tested Context requirement, while full transcript input combined stale and untrusted information; no generalized Context Kernel was earned.", status: "active", confidence: "supported", date: "2026-07-30", updatedAt: "2026-07-30" },
  { id: "finding:unknown-operational-state", kind: "finding", title: "UNKNOWN is an operational state, not model sentiment", summary: "No response does not imply no commit. Safe continuation requires stable operation identity, backend correlation, reconciliation, and a prohibition on blind redispatch.", status: "active", confidence: "strong", date: "2026-07-30", updatedAt: "2026-07-30" },
  { id: "finding:provider-portability-not-equivalence", kind: "finding", title: "Provider replacement proves state portability, not interchangeability", summary: "Codex and Hermes could continue the same durable Task without prior Session transfer, while outcome quality, cost, and strategy remained provider-dependent.", status: "active", confidence: "strong", date: "2026-07-30", updatedAt: "2026-07-30" },
  { id: "finding:attention-is-admission-resource", kind: "finding", title: "Human attention is an admission resource", summary: "Evidence-rich deterministic escalation reduced designed interruptions from twelve to seven without missed escalation, but the timing model remains an estimate until real operator traces exist.", status: "active", confidence: "tentative", date: "2026-07-30", updatedAt: "2026-07-30" },
  { id: "finding:tactical-not-strategic", kind: "finding", title: "Tactical success can be strategically harmful", summary: "The greedy local actor received tactical credit while entering the decoy in all fifteen Trials, and CAGE foothold spread did not monotonically track mission reward.", status: "experimental", confidence: "strong", date: "2026-07-30", updatedAt: "2026-07-30" },
  { id: "finding:interpretation-not-action", kind: "finding", title: "Better interpretation does not guarantee better action", summary: "Explicit hypotheses improved local diagnosis and one model switch-recognition trace, but all four retained model Trials failed the genuine objective.", status: "experimental", confidence: "supported", date: "2026-07-30", updatedAt: "2026-07-30" },
  { id: "finding:organization-isolation-not-intelligence", kind: "finding", title: "Organization can isolate bad advice without creating new capability", summary: "Compartmentalized command suppressed a compromised proposal but exactly matched the selected cautious specialist rather than producing emergent collective capability.", status: "experimental", confidence: "supported", date: "2026-07-30", updatedAt: "2026-07-30" },
  { id: "finding:replay-pure-projection", kind: "finding", title: "Replay and diagnosis can remain pure projections", summary: "Station Zero derived point-in-time state, Evidence Graphs, bounded frames, evidence classes, and exact comparison from retained authority without a second truth store or model-generated causality.", status: "experimental", confidence: "strong", date: "2026-07-30", updatedAt: "2026-07-30" },
  { id: "finding:link-edge-boundary-wrong", kind: "finding", title: "Link and Edge were useful analytical planes but the wrong repository boundary", summary: "Recovery must correlate path-conditioned delivery and external execution before retry, so one World Interaction boundary better matches the continuous object.", status: "active", confidence: "supported", date: "2026-07-30", updatedAt: graphUpdatedAt },
  { id: "finding:web-governance-displaced-interface", kind: "finding", title: "Release governance had become larger than the Web interface it protected", summary: "Most tracked implementation effort lived in evidence, archives, cross-browser matrices, and release scripts while the system map remained four links and a CSS line.", status: "active", confidence: "strong", date: "2026-07-30", updatedAt: graphUpdatedAt },
  { id: "finding:process-success-not-task-completion", kind: "finding", title: "A successful Harness process does not complete a Task", summary: "Codex App Server and Runtime completed successfully, but Host correctly retained the Task in waiting because completion still required a current proposal, evidence, Artifacts, resolved uncertainty, and acceptance adjudication.", status: "active", confidence: "strong", date: "2026-07-31", updatedAt: graphUpdatedAt },
  { id: "finding:runtime-opaque-correlation-sufficient", kind: "finding", title: "Opaque foreign references were sufficient for Host–Runtime correlation", summary: "Task, Attempt, Assignment, and Harness Run identities survived exact replay, conflict detection, terminal evidence, and fresh-client recovery without Runtime interpreting Host semantics.", status: "active", confidence: "strong", date: "2026-07-31", updatedAt: graphUpdatedAt },
];

export const decisionNodes: DecisionNode[] = [
  { id: "decision:extract-host", kind: "decision", title: "Extract Host as an independent state owner", summary: "Host now versions Task continuity independently while Computing retains shared contracts and Runtime retains physical execution truth.", status: "active", rationale: "Continuation and recovery proved a durable state boundary that would be blurred by continued incubation inside Computing.", date: "2026-07-27", updatedAt: "2026-07-27" },
  { id: "decision:embedded-game-host", kind: "decision", title: "Use one embedded Host authority in Game", summary: "Reuse the shared workload semantics without forcing Game through a Python sidecar or retaining duplicate Host truth tables.", status: "active", rationale: "The sidecar was functionally correct but slower, larger, operationally split, and unable to justify its extra process; the embedded authority preserved exact Game outcomes and enabled net deletion.", date: "2026-07-29", updatedAt: "2026-07-29" },
  { id: "decision:no-task-runtime", kind: "decision", title: "Do not create a separate Ordivon Task Runtime", summary: "Keep work meaning in Host and reuse mature workflow mechanics when a workload needs them.", status: "active", rationale: "LangGraph and Temporal preserved the tested application semantics and continuation behavior; no independent shared Task Runtime responsibility was demonstrated.", date: "2026-07-30", updatedAt: "2026-07-30" },
  { id: "decision:no-context-kernel", kind: "decision", title: "Do not create a generalized Context Kernel", summary: "Keep current source binding and selection metadata in the owning Host or application until a second workload proves a shared responsibility.", status: "active", rationale: "Current-revision retrieval matched the tested Context requirement while full transcript input performed worse; generalized state added no demonstrated leverage.", date: "2026-07-30", updatedAt: "2026-07-30" },
  { id: "decision:shrink-effect", kind: "decision", title: "Shrink Effect pending a second backend", summary: "Retain stable identity, explicit UNKNOWN, backend correlation, reconciliation, and no blind redispatch while deferring the larger shared Effect graph.", status: "active", rationale: "Idempotency plus audit and durable Activity baselines matched the single-backend outcome; World W1 must prove any additional cross-backend fields.", date: "2026-07-30", updatedAt: "2026-07-30" },
  { id: "decision:decision-request-host-local", kind: "decision", title: "Keep DecisionRequest and attention admission Host-local", summary: "Represent consequence, options, deadline, evidence, and escalation where Task meaning and participant authority are already owned.", status: "active", rationale: "The deterministic attention experiment showed promise but not enough cross-workload or operator evidence to promote a separate control platform.", date: "2026-07-30", updatedAt: "2026-07-30" },
  { id: "decision:no-custom-cyber-range", kind: "decision", title: "Do not build a custom Ordivon cyber range", summary: "Reuse pinned CAGE Challenge 4 and other mature Worlds while Security owns only the experimental strategic relations it proves necessary.", status: "active", rationale: "CAGE supplied authoritative state, partial observations, actor populations, actions, mission phases, rewards, and seeded Trials; no missing classical fact justified a replacement range.", date: "2026-07-30", updatedAt: "2026-07-30" },
  { id: "decision:no-campaign-promotion", kind: "decision", title: "Do not promote Campaign or strategic state after Security Round 1", summary: "Retain opponent hypotheses and multidimensional outcomes as research variables rather than shared architecture.", status: "active", rationale: "All retained model Trials failed the objective, transfer was untested, and one synthetic organization scenario did not establish a general ontology.", date: "2026-07-30", updatedAt: "2026-07-30" },
  { id: "decision:unify-world", kind: "decision", title: "Unify Link and Edge under Ordivon World", summary: "Preserve their proven internal planes while removing the project boundary that split one recoverable external interaction.", status: "active", rationale: "The intended Effect conditions path choice, and response loss cannot be reconciled without delivery and execution evidence together.", date: "2026-07-30", updatedAt: graphUpdatedAt },
  { id: "decision:thin-web-release", kind: "decision", title: "Return Web release checks to build, smoke, preview, and deploy", summary: "Delete in-tree release evidence, duplicate V1 archives, browser matrices, and repeated performance proof.", status: "active", rationale: "Git-based recovery is cheaper than the governance system, and no retained gate demonstrated loss proportionate to its maintenance cost.", date: "2026-07-30", updatedAt: graphUpdatedAt },
  { id: "decision:mdx-writing", kind: "decision", title: "Replace JSON-embedded HTML with composable MDX", summary: "Articles are now real content modules that can embed research interfaces without retaining a migration pipeline.", status: "active", rationale: "The previous system paid for MDX and JSON HTML simultaneously while receiving the capabilities of neither.", date: "2026-07-30", updatedAt: graphUpdatedAt },
  { id: "decision:no-runtime-harness-expansion", kind: "decision", title: "Do not expand Runtime for Harness correlation", summary: "Keep Host identities opaque and bind them to existing Runtime request and terminal-evidence surfaces.", status: "active", rationale: "H2/R2 proved real correlation, replay, conflict, recovery, and evidence using foreign references without new Runtime database tables, Task state, or completion semantics.", date: "2026-07-31", updatedAt: graphUpdatedAt },
];

export const articleNodes: ArticleNode[] = articleMetadata.map((article) => ({
  id: `article:${article.slug}`,
  kind: "article" as const,
  slug: article.slug,
  title: article.title,
  summary: article.description,
  status: "active" as const,
  href: `/writing/${article.slug}`,
  articleType: article.type,
  project: article.project,
  date: article.date,
  updatedAt: article.modifiedDate,
}));

export const graphNodes: GraphNode[] = [
  ...systemNodes,
  ...projectNodes,
  ...questionNodes,
  ...experimentNodes,
  ...findingNodes,
  ...decisionNodes,
  ...articleNodes,
];
