import type { GraphRelation } from "@/lib/graph/types";

const projectSystemRelations = [
  ["project:computing", "system:computing"],
  ["project:host", "system:host"],
  ["project:runtime", "system:runtime"],
  ["project:world", "system:world"],
].map(([source, target], index) => ({ id: `relation:project-system-${index + 1}`, type: "implements" as const, source, target }));

const projectQuestionRelations = [
  ["project:computing", "question:computing-smallest-core"],
  ["project:computing", "question:computing-async-join"],
  ["project:computing", "question:computing-second-workload"],
  ["project:computing", "question:computing-calibrated-non-action"],
  ["project:host", "question:host-general-goal"],
  ["project:host", "question:host-operational-surface"],
  ["project:host", "question:host-harness-composition"],
  ["project:runtime", "question:runtime-structured-effect"],
  ["project:runtime", "question:runtime-boundary-friction"],
  ["project:world", "question:world-correlated-recovery"],
  ["project:world", "question:world-boundary-value"],
  ["project:web", "question:web-research-interface"],
  ["project:game", "question:game-agent-native-mechanics"],
  ["project:security", "question:security-adversarial-trajectory"],
  ["project:security", "question:security-opponent-state-transfer"],
].map(([source, target]) => ({ id: `relation:project-question-${target.replace("question:", "")}`, type: "raises" as const, source, target }));

const researchRelations: GraphRelation[] = [
  { id: "relation:host-experiment-tests", type: "tests", source: "experiment:host-h2-h6", target: "question:host-general-goal" },
  { id: "relation:host-experiment-supports-finding", type: "supports", source: "experiment:host-h2-h6", target: "finding:host-state-above-session" },
  { id: "relation:host-finding-supports", type: "supports", source: "finding:host-state-above-session", target: "question:host-general-goal" },
  { id: "relation:host-finding-decision", type: "supports", source: "finding:host-state-above-session", target: "decision:extract-host" },

  { id: "relation:core-round1-tests-smallest-core", type: "tests", source: "experiment:core-work-system-round1", target: "question:computing-smallest-core" },
  { id: "relation:core-round1-supports-workflow-finding", type: "supports", source: "experiment:core-work-system-round1", target: "finding:mature-workflows-carry-state" },
  { id: "relation:core-round1-supports-transcript-finding", type: "supports", source: "experiment:core-work-system-round1", target: "finding:transcript-not-task-database" },
  { id: "relation:core-round1-supports-context-finding", type: "supports", source: "experiment:core-work-system-round1", target: "finding:more-context-not-safer" },
  { id: "relation:core-round1-supports-unknown-finding", type: "supports", source: "experiment:core-work-system-round1", target: "finding:unknown-operational-state" },
  { id: "relation:core-round1-supports-portability-finding", type: "supports", source: "experiment:core-work-system-round1", target: "finding:provider-portability-not-equivalence" },
  { id: "relation:core-round1-supports-attention-finding", type: "supports", source: "experiment:core-work-system-round1", target: "finding:attention-is-admission-resource" },
  { id: "relation:workflow-finding-supports-smallest-core", type: "supports", source: "finding:mature-workflows-carry-state", target: "question:computing-smallest-core" },
  { id: "relation:transcript-finding-supports-smallest-core", type: "supports", source: "finding:transcript-not-task-database", target: "question:computing-smallest-core" },
  { id: "relation:context-finding-supports-smallest-core", type: "supports", source: "finding:more-context-not-safer", target: "question:computing-smallest-core" },
  { id: "relation:unknown-finding-supports-smallest-core", type: "supports", source: "finding:unknown-operational-state", target: "question:computing-smallest-core" },
  { id: "relation:portability-finding-supports-smallest-core", type: "supports", source: "finding:provider-portability-not-equivalence", target: "question:computing-smallest-core" },
  { id: "relation:attention-finding-supports-non-action", type: "supports", source: "finding:attention-is-admission-resource", target: "question:computing-calibrated-non-action" },
  { id: "relation:workflow-finding-supports-no-task-runtime", type: "supports", source: "finding:mature-workflows-carry-state", target: "decision:no-task-runtime" },
  { id: "relation:context-finding-supports-no-context-kernel", type: "supports", source: "finding:more-context-not-safer", target: "decision:no-context-kernel" },
  { id: "relation:unknown-finding-supports-shrink-effect", type: "supports", source: "finding:unknown-operational-state", target: "decision:shrink-effect" },
  { id: "relation:attention-finding-supports-host-local-decision", type: "supports", source: "finding:attention-is-admission-resource", target: "decision:decision-request-host-local" },
  { id: "relation:no-task-runtime-implements-smallest-core", type: "implements", source: "decision:no-task-runtime", target: "question:computing-smallest-core" },
  { id: "relation:no-context-kernel-implements-smallest-core", type: "implements", source: "decision:no-context-kernel", target: "question:computing-smallest-core" },
  { id: "relation:shrink-effect-implements-smallest-core", type: "implements", source: "decision:shrink-effect", target: "question:computing-smallest-core" },
  { id: "relation:shrink-effect-implements-runtime-question", type: "implements", source: "decision:shrink-effect", target: "question:runtime-structured-effect" },
  { id: "relation:host-local-decision-implements-non-action", type: "implements", source: "decision:decision-request-host-local", target: "question:computing-calibrated-non-action" },

  { id: "relation:harness-h1-tests-composition", type: "tests", source: "experiment:harness-h1-contracts", target: "question:host-harness-composition" },
  { id: "relation:harness-h2-tests-composition", type: "tests", source: "experiment:harness-h2-runtime-correlation", target: "question:host-harness-composition" },
  { id: "relation:harness-h2-tests-runtime-boundary", type: "tests", source: "experiment:harness-h2-runtime-correlation", target: "question:runtime-boundary-friction" },
  { id: "relation:harness-h3-tests-composition", type: "tests", source: "experiment:harness-h3-codex-app", target: "question:host-harness-composition" },
  { id: "relation:harness-h3-tests-general-goal", type: "tests", source: "experiment:harness-h3-codex-app", target: "question:host-general-goal" },
  { id: "relation:harness-h1-supports-process-finding", type: "supports", source: "experiment:harness-h1-contracts", target: "finding:process-success-not-task-completion" },
  { id: "relation:harness-h2-supports-correlation-finding", type: "supports", source: "experiment:harness-h2-runtime-correlation", target: "finding:runtime-opaque-correlation-sufficient" },
  { id: "relation:harness-h3-supports-process-finding", type: "supports", source: "experiment:harness-h3-codex-app", target: "finding:process-success-not-task-completion" },
  { id: "relation:correlation-finding-supports-composition", type: "supports", source: "finding:runtime-opaque-correlation-sufficient", target: "question:host-harness-composition" },
  { id: "relation:correlation-finding-supports-runtime-boundary", type: "supports", source: "finding:runtime-opaque-correlation-sufficient", target: "question:runtime-boundary-friction" },
  { id: "relation:process-finding-supports-composition", type: "supports", source: "finding:process-success-not-task-completion", target: "question:host-harness-composition" },
  { id: "relation:process-finding-supports-general-goal", type: "supports", source: "finding:process-success-not-task-completion", target: "question:host-general-goal" },
  { id: "relation:correlation-finding-supports-no-runtime-expansion", type: "supports", source: "finding:runtime-opaque-correlation-sufficient", target: "decision:no-runtime-harness-expansion" },
  { id: "relation:no-runtime-expansion-implements-runtime-boundary", type: "implements", source: "decision:no-runtime-harness-expansion", target: "question:runtime-boundary-friction" },
  { id: "relation:no-runtime-expansion-implements-composition", type: "implements", source: "decision:no-runtime-harness-expansion", target: "question:host-harness-composition" },

  { id: "relation:runtime-experiment-tests", type: "tests", source: "experiment:runtime-production-dogfood", target: "question:runtime-boundary-friction" },
  { id: "relation:runtime-experiment-supports-finding", type: "supports", source: "experiment:runtime-production-dogfood", target: "finding:runtime-commitment-boundary" },
  { id: "relation:runtime-finding-supports", type: "supports", source: "finding:runtime-commitment-boundary", target: "question:runtime-structured-effect" },
  { id: "relation:runtime-finding-supports-boundary", type: "supports", source: "finding:runtime-commitment-boundary", target: "question:runtime-boundary-friction" },
  { id: "relation:unknown-finding-supports-runtime-effect", type: "supports", source: "finding:unknown-operational-state", target: "question:runtime-structured-effect" },

  { id: "relation:game-m3-tests-mechanics", type: "tests", source: "experiment:game-multi-agent-m3", target: "question:game-agent-native-mechanics" },
  { id: "relation:game-m3-supports-communication", type: "supports", source: "experiment:game-multi-agent-m3", target: "finding:communication-is-world-state" },
  { id: "relation:game-m3-supports-provider-portability", type: "supports", source: "experiment:game-multi-agent-m3", target: "finding:provider-portability-not-equivalence" },
  { id: "relation:communication-finding-supports-game", type: "supports", source: "finding:communication-is-world-state", target: "question:game-agent-native-mechanics" },
  { id: "relation:portability-finding-supports-game", type: "supports", source: "finding:provider-portability-not-equivalence", target: "question:game-agent-native-mechanics" },
  { id: "relation:game-authority-tests-second-workload", type: "tests", source: "experiment:game-authority-cutover", target: "question:computing-second-workload" },
  { id: "relation:game-authority-supports-finding", type: "supports", source: "experiment:game-authority-cutover", target: "finding:one-authority-over-shared-process" },
  { id: "relation:one-authority-finding-supports-second-workload", type: "supports", source: "finding:one-authority-over-shared-process", target: "question:computing-second-workload" },
  { id: "relation:one-authority-finding-supports-decision", type: "supports", source: "finding:one-authority-over-shared-process", target: "decision:embedded-game-host" },
  { id: "relation:embedded-game-host-implements-second-workload", type: "implements", source: "decision:embedded-game-host", target: "question:computing-second-workload" },
  { id: "relation:station-zero-tests-game", type: "tests", source: "experiment:station-zero-alpha", target: "question:game-agent-native-mechanics" },
  { id: "relation:station-zero-supports-replay-finding", type: "supports", source: "experiment:station-zero-alpha", target: "finding:replay-pure-projection" },
  { id: "relation:replay-finding-supports-game", type: "supports", source: "finding:replay-pure-projection", target: "question:game-agent-native-mechanics" },

  { id: "relation:security-round1-tests-trajectory", type: "tests", source: "experiment:security-round1", target: "question:security-adversarial-trajectory" },
  { id: "relation:security-round1-tests-opponent-transfer", type: "tests", source: "experiment:security-round1", target: "question:security-opponent-state-transfer" },
  { id: "relation:security-round1-supports-tactical-finding", type: "supports", source: "experiment:security-round1", target: "finding:tactical-not-strategic" },
  { id: "relation:security-round1-supports-interpretation-finding", type: "supports", source: "experiment:security-round1", target: "finding:interpretation-not-action" },
  { id: "relation:security-round1-supports-organization-finding", type: "supports", source: "experiment:security-round1", target: "finding:organization-isolation-not-intelligence" },
  { id: "relation:tactical-finding-supports-security", type: "supports", source: "finding:tactical-not-strategic", target: "question:security-adversarial-trajectory" },
  { id: "relation:interpretation-finding-supports-security", type: "supports", source: "finding:interpretation-not-action", target: "question:security-adversarial-trajectory" },
  { id: "relation:organization-finding-supports-security", type: "supports", source: "finding:organization-isolation-not-intelligence", target: "question:security-adversarial-trajectory" },
  { id: "relation:interpretation-finding-supports-opponent-transfer", type: "supports", source: "finding:interpretation-not-action", target: "question:security-opponent-state-transfer" },
  { id: "relation:no-custom-range-implements-security", type: "implements", source: "decision:no-custom-cyber-range", target: "question:security-adversarial-trajectory" },
  { id: "relation:no-campaign-implements-security", type: "implements", source: "decision:no-campaign-promotion", target: "question:security-adversarial-trajectory" },
  { id: "relation:no-campaign-implements-opponent-transfer", type: "implements", source: "decision:no-campaign-promotion", target: "question:security-opponent-state-transfer" },

  { id: "relation:world-experiment-tests", type: "tests", source: "experiment:world-unification", target: "question:world-boundary-value" },
  { id: "relation:world-experiment-supports-finding", type: "supports", source: "experiment:world-unification", target: "finding:link-edge-boundary-wrong" },
  { id: "relation:world-finding-supports-question", type: "supports", source: "finding:link-edge-boundary-wrong", target: "question:world-boundary-value" },
  { id: "relation:world-finding-supports", type: "supports", source: "finding:link-edge-boundary-wrong", target: "decision:unify-world" },

  { id: "relation:web-experiment-tests", type: "tests", source: "experiment:web-governance-audit", target: "question:web-research-interface" },
  { id: "relation:web-experiment-supports-finding", type: "supports", source: "experiment:web-governance-audit", target: "finding:web-governance-displaced-interface" },
  { id: "relation:web-finding-supports", type: "supports", source: "finding:web-governance-displaced-interface", target: "decision:thin-web-release" },
  { id: "relation:web-thin-release-implements", type: "implements", source: "decision:thin-web-release", target: "question:web-research-interface" },
  { id: "relation:web-mdx-implements", type: "implements", source: "decision:mdx-writing", target: "question:web-research-interface" },

  { id: "relation:host-runtime-dependency", type: "depends_on", source: "system:host", target: "system:runtime", label: "dispatches physical effects" },
  { id: "relation:host-computing-dependency", type: "depends_on", source: "system:host", target: "system:computing", label: "implements shared contracts" },
  { id: "relation:world-computing-dependency", type: "depends_on", source: "system:world", target: "system:computing", label: "tests continuity contracts" },
  { id: "relation:project-computing-defines-host", type: "defines", source: "project:computing", target: "project:host", label: "defines shared contracts" },
  { id: "relation:project-computing-defines-runtime", type: "defines", source: "project:computing", target: "project:runtime", label: "defines effect contracts" },
  { id: "relation:project-computing-defines-world", type: "defines", source: "project:computing", target: "project:world", label: "defines continuity contracts" },
  { id: "relation:project-host-runtime-dependency", type: "depends_on", source: "project:host", target: "project:runtime", label: "commits local effects" },
  { id: "relation:project-host-world-dependency", type: "depends_on", source: "project:host", target: "project:world", label: "acts through external bindings" },
];

const articleRelations: GraphRelation[] = [
  { id: "relation:article-winning-move-security", type: "documents", source: "article:winning-move-loses-contest", target: "project:security" },
  { id: "relation:article-winning-move-trajectory-question", type: "documents", source: "article:winning-move-loses-contest", target: "question:security-adversarial-trajectory" },
  { id: "relation:article-winning-move-transfer-question", type: "documents", source: "article:winning-move-loses-contest", target: "question:security-opponent-state-transfer" },
  { id: "relation:article-winning-move-experiment", type: "documents", source: "article:winning-move-loses-contest", target: "experiment:security-round1" },
  { id: "relation:article-winning-move-tactical-finding", type: "documents", source: "article:winning-move-loses-contest", target: "finding:tactical-not-strategic" },
  { id: "relation:article-winning-move-interpretation-finding", type: "documents", source: "article:winning-move-loses-contest", target: "finding:interpretation-not-action" },
  { id: "relation:article-winning-move-organization-finding", type: "documents", source: "article:winning-move-loses-contest", target: "finding:organization-isolation-not-intelligence" },
  { id: "relation:article-winning-move-range-decision", type: "documents", source: "article:winning-move-loses-contest", target: "decision:no-custom-cyber-range" },
  { id: "relation:article-winning-move-campaign-decision", type: "documents", source: "article:winning-move-loses-contest", target: "decision:no-campaign-promotion" },
  { id: "relation:article-smaller-core-computing", type: "documents", source: "article:smaller-core-strong-baselines", target: "project:computing" },
  { id: "relation:article-smaller-core-question", type: "documents", source: "article:smaller-core-strong-baselines", target: "question:computing-smallest-core" },
  { id: "relation:article-smaller-core-effect-question", type: "documents", source: "article:smaller-core-strong-baselines", target: "question:runtime-structured-effect" },
  { id: "relation:article-smaller-core-attention-question", type: "documents", source: "article:smaller-core-strong-baselines", target: "question:computing-calibrated-non-action" },
  { id: "relation:article-smaller-core-experiment", type: "documents", source: "article:smaller-core-strong-baselines", target: "experiment:core-work-system-round1" },
  { id: "relation:article-smaller-core-workflow-finding", type: "documents", source: "article:smaller-core-strong-baselines", target: "finding:mature-workflows-carry-state" },
  { id: "relation:article-smaller-core-transcript-finding", type: "documents", source: "article:smaller-core-strong-baselines", target: "finding:transcript-not-task-database" },
  { id: "relation:article-smaller-core-context-finding", type: "documents", source: "article:smaller-core-strong-baselines", target: "finding:more-context-not-safer" },
  { id: "relation:article-smaller-core-unknown-finding", type: "documents", source: "article:smaller-core-strong-baselines", target: "finding:unknown-operational-state" },
  { id: "relation:article-smaller-core-portability-finding", type: "documents", source: "article:smaller-core-strong-baselines", target: "finding:provider-portability-not-equivalence" },
  { id: "relation:article-smaller-core-attention-finding", type: "documents", source: "article:smaller-core-strong-baselines", target: "finding:attention-is-admission-resource" },
  { id: "relation:article-smaller-core-task-runtime-decision", type: "documents", source: "article:smaller-core-strong-baselines", target: "decision:no-task-runtime" },
  { id: "relation:article-smaller-core-context-decision", type: "documents", source: "article:smaller-core-strong-baselines", target: "decision:no-context-kernel" },
  { id: "relation:article-smaller-core-effect-decision", type: "documents", source: "article:smaller-core-strong-baselines", target: "decision:shrink-effect" },
  { id: "relation:article-smaller-core-attention-decision", type: "documents", source: "article:smaller-core-strong-baselines", target: "decision:decision-request-host-local" },
  { id: "relation:article-future-computing", type: "documents", source: "article:the-future-will-not-wait", target: "project:computing" },
  { id: "relation:article-world-world", type: "documents", source: "article:link-edge-boundary", target: "project:world" },
  { id: "relation:article-world-decision", type: "documents", source: "article:link-edge-boundary", target: "decision:unify-world" },
  { id: "relation:article-world-question", type: "documents", source: "article:link-edge-boundary", target: "question:world-boundary-value" },
  { id: "relation:article-runtime-runtime", type: "documents", source: "article:runtime-after-core", target: "project:runtime" },
  { id: "relation:article-runtime-finding", type: "documents", source: "article:runtime-after-core", target: "finding:runtime-commitment-boundary" },
  { id: "relation:article-runtime-structured-question", type: "documents", source: "article:runtime-after-core", target: "question:runtime-structured-effect" },
  { id: "relation:article-runtime-boundary-question", type: "documents", source: "article:runtime-after-core", target: "question:runtime-boundary-friction" },
  { id: "relation:article-host-host", type: "documents", source: "article:host-task-continuity", target: "project:host" },
  { id: "relation:article-host-finding", type: "documents", source: "article:host-task-continuity", target: "finding:host-state-above-session" },
  { id: "relation:article-host-decision", type: "documents", source: "article:host-task-continuity", target: "decision:extract-host" },
  { id: "relation:article-host-question", type: "documents", source: "article:host-task-continuity", target: "question:host-general-goal" },
  { id: "relation:article-release-runtime", type: "documents", source: "article:ordivon-runtime-release", target: "project:runtime" },
  { id: "relation:article-why-computing", type: "documents", source: "article:why-ordivon", target: "project:computing" },
  { id: "relation:article-why-host", type: "documents", source: "article:why-ordivon", target: "project:host" },
  { id: "relation:article-host-runtime", type: "documents", source: "article:host-task-continuity", target: "project:runtime" },
  { id: "relation:article-runtime-host", type: "documents", source: "article:runtime-after-core", target: "project:host" },
  { id: "relation:article-host-world", type: "documents", source: "article:host-task-continuity", target: "project:world" },
  { id: "relation:article-runtime-world", type: "documents", source: "article:runtime-after-core", target: "project:world" },
];

export const graphRelations: GraphRelation[] = [
  ...projectSystemRelations,
  ...projectQuestionRelations,
  ...researchRelations,
  ...articleRelations,
];
